### ISSUE TITLE
pytorch does not compatible with caffe2

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/pytorch#10249]
## Issue description

I seem not able to import torch together with caffe2 in the same process.

## Code example

```
>>> import torch
>>> from caffe2.python import workspace
```
or
```
>>> from caffe2.python import workspace
>>> import torch
```

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+08daed4
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 384.81
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (0.5.0a0-08daed4)
[pip] torchsample (0.1.3)
[pip] torchvision (0.2.1)
[conda] Could not collect

**Comment by SsnL** [comment]
what's the error message?

**Comment by CoinCheung** [comment]
```
>>> import torch
>>> from caffe2.python import workspace
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_hip
CRITICAL:root:Cannot load caffe2.python. Error: /usr/local/lib/python2.7/dist-packages/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZTIN6caffe27NetBaseE
```
or 
```
>>> from caffe2.python import workspace
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so: undefined symbol: THRefcountedMapAllocator
```

**Comment by Kongsea** [comment]
The same error as you.

**Comment by hcx1231** [comment]
I also have the same error as you

**Comment by CoinCheung** [comment]
This problem seems to be brought by importing concurrently caffe2 and the latest pytorch of v0.5xxx. I install back pytorch v0.4 and this problem is solved.

**Comment by AidasK** [comment]
Same error with pytorch 0.4.1:
```
conda create -n caffe2py35 python=3.5
source activate caffe2py35
conda install -c caffe2 caffe2
conda install -c conda-forge onnx
conda install -c pytorch pytorch
```

```
import torch
from caffe2.python import core
```
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(/Users/aidas/miniconda2/envs/caffe2py35/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-darwin.so, 10): Symbol not found: __ZN3fLB27FLAGS_caffe2_keep_on_shrinkE
  Referenced from: /Users/aidas/miniconda2/envs/caffe2py35/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-darwin.so
  Expected in: /Users/aidas/miniconda2/envs/caffe2py35/lib/python3.6/site-packages/torch/lib/libcaffe2.dylib
 in /Users/aidas/miniconda2/envs/caffe2py35/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-darwin.so
```

**Comment by ezyang** [comment]
@AidasK I have to double check, but I think PyTorch 0.4.1 might be installing `libcaffe2.so`, which is causing the problem. Can you try building PyTorch master with `FULL_CAFFE2` and see if it resolves your problem?

**Comment by jiapei100** [comment]
I still meet the following ERROR messages:



```
-- Configuring done
CMake Error: install(EXPORT "Caffe2Targets" ...) includes target "caffe2" which requires target "nnpack" that is not in the export set.
CMake Error: install(EXPORT "Caffe2Targets" ...) includes target "caffe2" which requires target "cpuinfo" that is not in the export set.
-- Generating done
-- Build files have been written to: ....../pytorch/build
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --full-caffe2 nccl caffe2 nanopb libshm gloo THD c10d'
```

**Comment by hduong** [comment]
Tried PyTorch master with FULL_CAFFE2, but still seeing the same error:
`>>> import onnx_caffe2.backend
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: /home/paperspace/anaconda3/envs/deeplearning/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6caffe27NetBaseE
`

Any workaround?
