### ISSUE TITLE
CUDA Extension Build Failure on Windows and MSVC 2017

### ISSUE THREAD

**Issue by JackHunt** [pytorch/pytorch#11004]
## Issue description

Building a custom CUDA extension fails with the following error on MSVC 2017:
`<env_lib_dir>\site-packages\torch\lib\include\pybind11\cast.h(1393): error: expression must be a pointer to a complete object type`

However, I have not observed the error with multiple GCC versions on Linux.

## Code example
Here is an MWE.

setup.py
```
import os
from setuptools import setup
from torch.utils.cpp_extension import CppExtension, CUDAExtension, BuildExtension

setup(name='exten', ext_modules=[
    CUDAExtension('exten_cuda', ['exten_cuda.cpp', 'exten_cuda_kernel.cu'])
    ], cmdclass={'build_ext': BuildExtension})
```

exten_cuda.cpp
```
std::vector<at::Tensor> exten_cuda_forward(at::Tensor a);
std::vector<at::Tensor> exten_cuda_backward(at::Tensor a);

std::vector<at::Tensor> exten_forward(at::Tensor a) {
  return exten_cuda_forward(a);
}

std::vector<at::Tensor> exten_backward(at::Tensor a) {
  return exten_cuda_backward(a);
}

// Do Python bindings.
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("forward", &exten_forward, "Extension forward CUDA");
  m.def("backward", &exten_backward, "Extension backward CUDA");
}
```

exten_cuda_kernel.cu
```
#include <torch/torch.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <vector>

std::vector<at::Tensor> exten_cuda_forward(at::Tensor a) {
  // Do nothing.

  // Return empty vector (just for compile error demo).
  return {};
}

std::vector<at::Tensor> exten_cuda_backward(at::Tensor a) {
  // Do nothing.

  // Return empty vector (just for compile error demo).
  return {};
}
```

## System Info
```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Education
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 7.1.0
CMake version: version 3.12.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 399.07
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch                   0.4.1           py37_cuda92_cudnn7he774522_1  [cuda92]  pytorch
[conda] torchvision               0.2.1                     <pip>
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- OS: Windows 10 x64
- PyTorch version: 0.4.1
- Python version: 3.7
- CUDA/cuDNN version: 9.2
- GPU models and configuration: GTX 1060 6GB
- MSVC version (if compiling from source): 15.7.5
- CMake version: 3.12.0
- Versions of any other relevant libraries:  setuptools 0.2.1

**Comment by shrubb** [comment]
Same here (shrubb/box-convolutions#17). @JackHunt have you solved this?
@peterjc123 I thought `TORCH_EXTENSION_NAME` is defined automatically by `CUDAExtension` in compiler flags, isn't it?

**Comment by peterjc123** [comment]
Hi, I tried the code and reproduced the issue here. I was able to solve it by replacing the header `torch/torch.h`(deprecated) with `ATen/ATen.h` or `torch/script.h`. But if I try to use `torch/extension.h` in the cuda sources, this error will occur. I'm not sure why it would happen, but the error thrown by the compiler is real, which prevent we do `*p` where `typeof p = void *` in `pybind11/cast.h #L1439`.

**Comment by shrubb** [comment]
Thanks for the investigation!

**Comment by qwesdfok** [comment]
I met the same problem. As peterjc123 said, the code can be modified by the following to resolve the compile error.
explicit operator type&() { return (*this).value; } 
// which was "explicit operator type&() { return *(this->value); }"

**Comment by ezyang** [comment]
In general, you can avoid these issues by making sure you define CUDA kernels in files that don't depend on Python (this is usually not too hard to do)

**Comment by qwesdfok** [comment]
@ezyang I use custom C++/CUDA extension to accelerate some for-loop operations in python. So I have to compile it. And I don't know how to remove this pybind11/cast.h file without any influence. But after modified, it works.

**Comment by elnazsn1988** [comment]
@peterjc123 , can you specify where you changed these files/their names? i am hitting a semi related error while building detectron2 on a windows10 with CUDA 10.1, exiting due to : 
1 error detected in the compilation of "C:/Users/aesnj/AppData/Local/Temp/tmpxft_00007274_00000000-10_deform_conv_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

alot of investigation has brought me either to your solution or removing VS2019 and sticking to 2017, which as I have 2015-17-19 in one package am not sure how to do. Any and hall help/suggestions would be appreciated.

**Comment by peterjc123** [comment]
@elnazsn1988 Could you please elaborate a little bit? What does the error refer to? If you are talking about `error: expression must be a pointer to a complete object type`, then please ensure the protubuf headers are not included in the sources during nvcc compilation. (Usually, you can see where it is included in the log)

**Comment by Shaul-Z** [comment]
Same issue when building OpenCV 4.4.0 from source. 
When I build "ALL_BUILD" and "INSTALL" projects using VS2019 Windows10 I got 2000 somthing warnings (only warnings no errors at all) saying:
"Warning: field of class type without a DLL interface used in a class with a DLL interface" and 
"Warning: base class dllexport/dllimport specification differs from that of the derived class"
Pre install CUDA 10.1 with matching cudnn. GPU: RTX 2080.
When tring to build darknet for using YoloV3 it dosen't showind CUDA in cMake.

**Comment by henryiii** [comment]
I believe this was fixed in pybind11 some time ago?

**Comment by elephaint** [comment]
I am experiencing this issue on Pytorch 1.7 with Windows when trying to build a custom CUDA kernel. I also had the issue with Pytorch 1.6 but then manually applied the solution given by @qwesdfok to the pybind11 file. Hence, I'll simply reapply this trick to get it working but just wanted to document that the issue still persists.

`
PyTorch version: 1.7.0
Is debug build: No
CUDA used to build PyTorch: 11.0

OS: Microsoft Windows 10 Pro

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 11.0
GPU models and configuration: GPU 0: GeForce GTX 2080 Ti
Nvidia driver version: 451.82
cuDNN version: 8.0'

**Comment by henryiii** [comment]
I think this will be properly fixed when #46415 is ready.

**Comment by cristianPanaite** [comment]
Hello @JackHunt,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
