### ISSUE TITLE
UNSTABLE inductor / cuda12.1-py3.10-gcc9-sm86 / test

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#120841]
https://huggingface.co/ is in maintenance, so marking as unstable as it attempts to download weights from that site and fails, for example, https://hud.pytorch.org/pytorch/pytorch/commit/491c2b46657393a059eada0b9c67bea04efb8198.

The issue can be closed once the site is back up.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
The issue has been resolved

**Comment by jeanschmidt** [comment]
Issue seems to be happening again. It is wrong to trust on external weights that can change (seems to be the case). So I'll link to https://github.com/pytorch/pytorch/issues/124825

**Comment by clee2000** [comment]
bigbird failure got fixed (?) in #126414, closing

**Comment by jeanschmidt** [comment]
@clee2000 issue persist, seems that this test is actually flaky. Moving back to unstable.

**Comment by clee2000** [comment]
This issue is marking the entirety of the inductor workflow as flaky when its only one job.  I am closing this and making a more specific one for inductor_timm
