### ISSUE TITLE
forward differentiation cannot access ctx.saved_tensors

### ISSUE THREAD

**Issue by bsxfan** [pytorch/pytorch#121084]
### Summary
I implemented custom derivatives for a function, say `f`, by subclassing `torch.autograd.Function` and then tested this functionality by invoking `torch.func.grad(f)` and `torch.func.hessian(f)`. The former works, the latter crashes in my `torch.autograd.Function.jvp(ctx, ...)`, because `ctx.saved_tensors` is empty. I did implement `torch.autograd.Function.setup_context(ctx, ...)`, which does `ctx.save_for_backward(my_tensor)`. In `torch.autograd.Function.backward(ctx, ...)` the retrieval `my_tensor, = ctx.saved_tensors` does work as expected, so that `torch.func.grad(f)` works correctly. In contrast, my `jvp(ctx, ...)` implementation crashes at `my_tensor, = ctx.saved_tensors`, because the RHS is empty.

### Minimal example
```
import torch
from torch.func import grad, hessian

print('torch version:',torch.__version__)

class Parabola(torch.autograd.Function):
    
    generate_vmap_rule=True
    
    
    @staticmethod
    def forward(x, abc):
        a, b, c = abc
        y = a*x.square() + b*x + c
        dydx = 2*a*x + b
        return y, dydx
    
    @staticmethod
    def setup_context(ctx, inputs, outputs): # I was surpised to see this is called twice for every invocation of forward   
        y, dydx = outputs
        ctx.save_for_backward(dydx)
    
    @staticmethod
    def backward(ctx, Dy, dummy):
        dydx, = ctx.saved_tensors        # this works as expected
        return Dy*dydx, None
    
    @staticmethod
    def jvp(ctx, Dx, dummy):
        dydx, = ctx.saved_tensors # crashes here, becasause RHS is empty
        return Dx*dydx, None

abc = torch.randn(3)    
    

def f0(x):
    a, b, c = abc
    return a*x.square() + b*x + c

def f(x): 
    y, dydx = Parabola.apply(x, abc)
    return y

x = torch.tensor(torch.pi)

print('\n\ntesting grad:')
print(grad(f0)(x))
print(grad(f)(x))

print('\n\ntesting hessian:')
print(hessian(f0)(x))
print(hessian(f)(x))
```

### Output
```
torch version: 2.2.1


testing grad:
tensor(6.7154)
tensor(6.7154)


testing hessian:
tensor(1.7974)
Traceback (most recent call last):

  File ~\miniconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example.py:52
    print(hessian(f)(x))

  File ~\miniconda3\lib\site-packages\torch\_functorch\eager_transforms.py:1139 in wrapper_fn
    results = vmap(push_jvp, randomness=randomness)(basis)

  File ~\miniconda3\lib\site-packages\torch\_functorch\apis.py:188 in wrapped
    return vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\vmap.py:278 in vmap_impl
    return _flat_vmap(

  File ~\miniconda3\lib\site-packages\torch\_functorch\vmap.py:44 in fn
    return f(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\vmap.py:391 in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\eager_transforms.py:1130 in push_jvp
    output = _jvp_with_argnums(func, args, basis, argnums=argnums, has_aux=has_aux)

  File ~\miniconda3\lib\site-packages\torch\_functorch\vmap.py:44 in fn
    return f(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\eager_transforms.py:976 in _jvp_with_argnums
    result_duals = func(*duals)

  File ~\miniconda3\lib\site-packages\torch\_functorch\eager_transforms.py:500 in wrapper_fn
    vjp_out = _vjp_with_argnums(func, *args, argnums=argnums, has_aux=has_aux)

  File ~\miniconda3\lib\site-packages\torch\_functorch\vmap.py:44 in fn
    return f(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\eager_transforms.py:302 in _vjp_with_argnums
    primals_out = func(*primals)

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example.py:41 in f
    y, dydx = Parabola.apply(x, abc)

  File ~\miniconda3\lib\site-packages\torch\autograd\function.py:563 in apply
    return custom_function_call(cls, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:46 in __call__
    return super().__call__(autograd_function, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_ops.py:366 in __call__
    return wrapper()

  File ~\miniconda3\lib\site-packages\torch\_dynamo\eval_frame.py:489 in _fn
    return fn(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_dynamo\external_utils.py:17 in inner
    return fn(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_ops.py:362 in wrapper
    return self.dispatch(

  File ~\miniconda3\lib\site-packages\torch\_ops.py:294 in dispatch
    return dispatch_functorch(self, args, kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\pyfunctorch.py:218 in dispatch_functorch
    return interpreter.process(op, args, kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\pyfunctorch.py:132 in process
    return kernel(self, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:90 in custom_function_call_grad
    flat_out = Generated.apply(*operands)

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:106 in forward
    unwrapped_output = custom_function_call(autograd_function, *unwrapped_operands)

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:46 in __call__
    return super().__call__(autograd_function, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_ops.py:366 in __call__
    return wrapper()

  File ~\miniconda3\lib\site-packages\torch\_dynamo\eval_frame.py:489 in _fn
    return fn(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_dynamo\external_utils.py:17 in inner
    return fn(*args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_ops.py:362 in wrapper
    return self.dispatch(

  File ~\miniconda3\lib\site-packages\torch\_ops.py:294 in dispatch
    return dispatch_functorch(self, args, kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\pyfunctorch.py:218 in dispatch_functorch
    return interpreter.process(op, args, kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\pyfunctorch.py:161 in process
    return kernel(self, *args, **kwargs)

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:90 in custom_function_call_grad
    flat_out = Generated.apply(*operands)

  File ~\miniconda3\lib\site-packages\torch\autograd\function.py:293 in apply_jvp
    return self._forward_cls.jvp(self, *args)  # type: ignore[attr-defined]

  File ~\miniconda3\lib\site-packages\torch\_functorch\autograd_function.py:128 in jvp
    result = autograd_function.jvp(ctx, *tangents)

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example.py:30 in jvp
    dydx, = ctx.saved_tensors

ValueError: not enough values to unpack (expected 1, got 0)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2594
DeviceID=CPU0
Family=198
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2594
Name=Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
ProcessorType=3
Revision=15363

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] numpydoc==1.5.0
[pip3] torch==2.2.1
[conda] blas                      2.106                       mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] libblas                   3.9.0                     6_mkl    conda-forge
[conda] libcblas                  3.9.0                     6_mkl    conda-forge
[conda] liblapack                 3.9.0                     6_mkl    conda-forge
[conda] liblapacke                3.9.0                     6_mkl    conda-forge
[conda] mkl                       2020.4             hb70f87d_311    conda-forge
[conda] numpy                     1.24.2          py310hd02465a_0    conda-forge
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   2.2.1              py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
```

cc @svekars @brycebortree @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by bsxfan** [comment]
### Update: simpler example
I was worried that my problem was conflated with the possibility that the  automatically generated vectorization invoked by `generate_vmap_rule=True` was not playing well with my example. (Vectorization was needed because `torch.func.hessian` does vectorization.). I have now simplified the example by directly calling forward-mode AD instead. The same problem persists:

### Simplified example
```
import torch
from torch.func import grad
from torch.autograd import forward_ad as fwAD


class Parabola(torch.autograd.Function):
    
    
    @staticmethod
    def forward(x, abc):
        a, b, c = abc
        y = a*x.square() + b*x + c
        dydx = 2*a*x + b
        return y, dydx
    
    
    @staticmethod
    def setup_context(ctx, inputs, outputs):
        y, dydx = outputs
        ctx.save_for_backward(dydx)
        #ctx.dydx = dydx              # this also doesn't work
    
    @staticmethod
    def backward(ctx, Dy, dummy):
        dydx, = ctx.saved_tensors
        #dydx = ctx.dydx              # this also doesn't work
        return Dy*dydx, None
    
    @staticmethod
    def jvp(ctx, Dx, dummy):
        dydx, = ctx.saved_tensors
        #dydx = ctx.dydx              # this also doesn't work
        return Dx*dydx, None

abc = torch.randn(3)    
    

def f0(x):
    """
    Ordinary pytorch function for control.
    """
    a, b, c = abc
    return a*x.square() + b*x + c

def f(x): 
    """
    My custom function.
    """
    y, dydx = Parabola.apply(x, abc)
    return y

x = torch.tensor(torch.pi)

print('\n\ntesting grad:')
a,b,c = abc
print('control  :', 2*a*x+b)
print('rev ad f0:', grad(f0)(x))
print('rev ad f1:',grad(f)(x))

print('\n\ntesting forward:')
dx = torch.tensor(1/torch.pi)
print('control: jvp =',grad(f0)(x)*dx)

with fwAD.dual_level():
    x_dx = fwAD.make_dual(x, dx)
    y, dy = fwAD.unpack_dual(f0(x_dx))
print('fwd f0 : jvp =',dy)

with fwAD.dual_level():
    x_dx = fwAD.make_dual(x, dx)
    y, dy = fwAD.unpack_dual(f(x_dx))
print('fwd f  : jvp =',dy)
```

### Output
```
testing grad:
control  : tensor(4.3489)
rev ad f0: tensor(4.3489)
rev ad f1: tensor(4.3489)


testing forward:
control: jvp = tensor(1.3843)
fwd f0 : jvp = tensor(1.3843)
Traceback (most recent call last):

  File ~\miniconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example2.py:71
    y, dy = fwAD.unpack_dual(f(x_dx))

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example2.py:49 in f
    y, dydx = Parabola.apply(x, abc)

  File ~\miniconda3\lib\site-packages\torch\autograd\function.py:553 in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]

  File ~\miniconda3\lib\site-packages\torch\autograd\function.py:293 in apply_jvp
    return self._forward_cls.jvp(self, *args)  # type: ignore[attr-defined]

  File c:\users\niko\documents\python\repos\scratch\nc\torch_tools\bug_minimal_example2.py:31 in jvp
    dydx, = ctx.saved_tensors

ValueError: not enough values to unpack (expected 1, got 0)
```

### Workaround (failed)
As a workaround I tried (against recommendations) to directly save and retrieve my derivatives directly as `ctx.dydx`, (see comments in code), but this crashes too.

**Comment by soulitzer** [comment]
If you would like to use saved variables for forward you also need to save them with [ctx.save_for_forward ](https://github.com/pytorch/pytorch/blob/main/torch/autograd/function.py#L92). It seems that we are missing the documentation on this though, we should fix that.

You'll also need to mark the outputs that you don't want to compute derivatives for with
`ctx.mark_non_differentiable(dydx)`

**Comment by bsxfan** [comment]
Thanks! 
I added the two ctx calls suggested by @soulitzer to my second code example above:
```
    @staticmethod
    def setup_context(ctx, inputs, outputs):
        y, dydx = outputs
        ctx.save_for_backward(dydx)
        ctx.save_for_forward(dydx)
        ctx.mark_non_differentiable(dydx)

```
and I can confirm that basic forward differentation now works for my example---it runs without crashing and gives the correct derivatives.

As a caveat, `torch.func.hessian` still doesn't work for my example (returns zeros), because my implementation is not wired for repeated differentiation, the [docs](https://pytorch.org/tutorials/intermediate/custom_function_double_backward_tutorial.html) for which are also rather incomplete and confusing and not directly referenced from the main documentation.

**Comment by soulitzer** [comment]
Closing as the issue as per the title is resolved. I also created a separate issue tracking the double backward documentation issue, which I've closed tentatively after realizing that we do point to this doc in a few places. Feel free to comment/reopen that one with more specific details on improvements.
