### ISSUE TITLE
`import torch` fails on stock ubuntu if one uses XPU nightly binaries

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#135867]
### 🐛 Describe the bug

```bash
$ docker run --rm -it python:3.10 bash -c "pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu/; python -c 'import torch;print(torch.__version__)'"
Looking in indexes: https://download.pytorch.org/whl/nightly/xpu/
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/xpu/torch-2.5.0.dev20240912%2Bxpu-cp310-cp310-linux_x86_64.whl (803.0 MB)
...
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 packaging-22.0 pytorch-triton-xpu-3.1.0+91b14bf559 sympy-1.13.1 torch-2.5.0.dev20240912+xpu typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 323, in _load_global_deps
    raise err
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

### Versions

nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by atalman** [comment]
todo: validate with pytorch-test:

```
pip3 install torch --index-url https://download.pytorch.org/whl/test/xpu
```

**Comment by atalman** [comment]
In Validation workflows this is successful since this so file is part of the Docker:
https://github.com/pytorch/builder/actions/runs/10832393139/job/30056700962#step:12:5196

```
	libmkl_intel_lp64.so.2 => /opt/intel/oneapi/pytorch-gpu-dev-0.5/lib/libmkl_intel_lp64.so.2 (0x00007fe99d41e000)
	libmkl_gnu_thread.so.2 => /opt/intel/oneapi/pytorch-gpu-dev-0.5/lib/libmkl_gnu_thread.so.2 (0x00007fe99bb7d000)
	libmkl_core.so.2 => /opt/intel/oneapi/pytorch-gpu-dev-0.5/lib/libmkl_core.so.2 (0x00007fe997be5000)
```

**Comment by chuanqi129** [comment]
Hi @malfet @atalman, this is an expected failure. The linux xpu torch wheels need setup xpu support package env firstly. User need to install the xpu support package firstly (refer https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html) and activate the bundle env like this https://github.com/pytorch/builder/blob/main/check_binary.sh#L58-L60. For future, we will release some pypi packages for xpu bundle as the dependencies of torch xpu wheel.

**Comment by chuanqi129** [comment]
And the document also has been added in readme https://github.com/pytorch/pytorch?tab=readme-ov-file#intel-gpu-support

**Comment by EikanWang** [comment]
@malfet , thanks for raising this issue. The issue fixing is in our plan and definitely we should fix it. In our plan, we have two approaches as follows to support Intel GPU PyTorch wheel package run.

- PT 2.5: Install Intel GPU bundle by following [URL](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html) and activate Intel GPU bundle components by sourcing a particular script.
- Post PT2.5: We will provide python packages for these bundle components and be installed automatically when users install Intel GPU PyTorch. It means that users do not do any additional setup steps for Intel GPU run.

Does it make sense for you?

**Comment by dvrogozh** [comment]
If I understand correctly, manylinux_2 was introduced by [PEP-600](https://peps.python.org/pep-0600) which intentionally has high-level requirements with specifics left vague. In particular, it does not have a lists of allowed libraries to link with as it was in previous PEPs for manylinux1, manylinux2010 and manylinux2014, i.e. [513](https://peps.python.org/pep-0513/), [571](https://peps.python.org/pep-0571/), [599](https://peps.python.org/pep-0599/). Do I miss some other PEP in addition to PEP-600 which regulates that or does pytorch has additional requirements to satisfy here?

Below is a printout of formal checking of couple xpu packages with `auditwheel`. As of now these packages are not tagged as manylinux2 in any case it seems, but tool returns that `torch` complies to `manylinux_2_34_x86_64` and `triton` to `manylinux_2_17_x86_64`. Tool does not warn about missing shared libraries though there are few of them.

It's indeed worrisome to get errors noted above running installed packages. I wonder whether there is a formal specification we need to comply to here being it a PEP or internal pytorch requirement.

* `torch`
```
# auditwheel show torch-2.6.0.dev20240913+xpu-cp310-cp310-linux_x86_64.whl

torch-2.6.0.dev20240913+xpu-cp310-cp310-linux_x86_64.whl is consistent
with the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_3.0', 'GCC_3.4'}, libc.so.6 with versions {'GLIBC_2.4',
'GLIBC_2.2.5', 'GLIBC_2.28', 'GLIBC_2.3.4', 'GLIBC_2.14',
'GLIBC_2.17', 'GLIBC_2.16', 'GLIBC_2.34', 'GLIBC_2.9', 'GLIBC_2.6',
'GLIBC_2.3', 'GLIBC_2.11', 'GLIBC_2.7', 'GLIBC_2.10', 'GLIBC_2.32',
'GLIBC_2.3.2'}, libstdc++.so.6 with versions {'GLIBCXX_3.4.14',
'CXXABI_1.3.8', 'GLIBCXX_3.4.18', 'GLIBCXX_3.4.22', 'GLIBCXX_3.4.17',
'GLIBCXX_3.4.19', 'CXXABI_1.3', 'CXXABI_1.3.7', 'GLIBCXX_3.4.9',
'GLIBCXX_3.4', 'CXXABI_1.3.11', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4.21',
'GLIBCXX_3.4.11', 'CXXABI_1.3.5', 'GLIBCXX_3.4.20', 'CXXABI_1.3.3',
'CXXABI_1.3.2', 'CXXABI_1.3.9', 'GLIBCXX_3.4.5'}, libm.so.6 with
versions {'GLIBC_2.2.5', 'GLIBC_2.27', 'GLIBC_2.23'}, libpthread.so.0
with versions {'GLIBC_2.2.5', 'GLIBC_2.3.4', 'GLIBC_2.3.3',
'GLIBC_2.12', 'GLIBC_2.3.2'}, librt.so.1 with versions
{'GLIBC_2.2.5'}, libdl.so.2 with versions {'GLIBC_2.2.5',
'GLIBC_2.3.3'}, libgomp-24e2ab19.so.1 with versions {'OMP_1.0',
'GOMP_1.0', 'GOMP_4.0'}, libOpenCL.so.1 with versions {'OPENCL_1.0',
'OPENCL_1.1', 'OPENCL_1.2', 'OPENCL_2.1', 'OPENCL_2.0'}

This constrains the platform tag to "manylinux_2_34_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```
* `triton`
```
# auditwheel show pytorch_triton_xpu-3.1.0+91b14bf559-cp310-cp310-linux_x86_64.whl

pytorch_triton_xpu-3.1.0+91b14bf559-cp310-cp310-linux_x86_64.whl is
consistent with the following platform tag: "manylinux_2_17_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libdl.so.2 with versions
{'GLIBC_2.2.5'}, libm.so.6 with versions {'GLIBC_2.2.5'}, libc.so.6
with versions {'GLIBC_2.15', 'GLIBC_2.4', 'GLIBC_2.3.4', 'GLIBC_2.3',
'GLIBC_2.14', 'GLIBC_2.16', 'GLIBC_2.7', 'GLIBC_2.2.5', 'GLIBC_2.6'},
libpthread.so.0 with versions {'GLIBC_2.3.2', 'GLIBC_2.2.5',
'GLIBC_2.12'}, libstdc++.so.6 with versions {'CXXABI_1.3.5',
'CXXABI_1.3.7', 'CXXABI_1.3.3', 'GLIBCXX_3.4.19', 'GLIBCXX_3.4.9',
'CXXABI_1.3', 'GLIBCXX_3.4.5', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4.14',
'CXXABI_1.3.2', 'GLIBCXX_3.4', 'GLIBCXX_3.4.18', 'GLIBCXX_3.4.15',
'GLIBCXX_3.4.17'}, libgcc_s.so.1 with versions {'GCC_3.4', 'GCC_3.3',
'GCC_3.0'}, libz.so.1 with versions {'ZLIB_1.2.0'}, librt.so.1 with
versions {'GLIBC_2.2.5'}

This constrains the platform tag to "manylinux_2_17_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```

**Comment by dvrogozh** [comment]
One of the examples in [PEP-600](https://peps.python.org/pep-0600) (the one about libncurse) gives a good guidance I think from which it can be deduced how packages should behave. Basically requirement with limited system libraries package should link with is still there, but implicit and without definitive list.

On pytorch side I think it's reasonable to require that `python -c 'import torch; print(torch.xpu.is_available())'` always works without any library load errors and returns either `True` or `False`.

**Comment by EikanWang** [comment]
Hi @malfet , regarding the particular mkl-dependency issue, we have submitted a PR to refine it - https://github.com/pytorch/builder/pull/1988.

But the intel gpu bundle still needs to be sourced for PyTorch 2.5 to add the Intel GPU runtime libraries to the PATH.

We will check if there is a solution to mitigate the issue.

**Comment by malfet** [comment]
Retried it with latest nightly, and still see same "cannot open shared option", although on a different library:
```
$ docker run --rm -it python:3.10 bash -c "pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu/; python -c 'import torch;print(torch.__version__)'"
Collecting torch
...
Installing collected packages: mpmath, typing-extensions, sympy, packaging, networkx, MarkupSafe, fsspec, filelock, pytorch-triton-xpu, jinja2, torch
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 packaging-22.0 pytorch-triton-xpu-3.1.0+91b14bf559 sympy-1.13.1 torch-2.6.0.dev20240920+xpu typing-extensions-4.12.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 368, in <module>
    from torch._C import *  # noqa: F403
ImportError: libze_loader.so.1: cannot open shared object file: No such file or directory
```

**Comment by EikanWang** [comment]
@malfet , `libze_loader.so.1` is part of the Intel GPU driver. However, I suppose the docker image python:3.10 does not install the Intel GPU driver. I guess that's why the issue is still there. 

https://github.com/pytorch/pytorch/blob/main/.ci/docker/common/install_xpu.sh#L10

**Comment by chuanqi129** [comment]
@malfet could you please try it base on this docker image `pytorch/manylinux2_28-builder:xpu-main`, which has installed xpu driver. 
```
$ docker run --rm -it pytorch/manylinux2_28-builder:xpu-main bash -c "export PATH=/opt/python/cp310-cp310/bin:$PATH; pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu/; python -c 'import torch;print(torch.__version__)'"
Looking in indexes: https://download.pytorch.org/whl/nightly/xpu/
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/xpu/torch-2.6.0.dev20240925%2Bxpu-cp310-cp310-linux_x86_64.whl (852.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.2/852.2 MB 129.0 MB/s eta 0:00:00
Collecting filelock (from torch)
  Downloading https://download.pytorch.org/whl/nightly/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting typing-extensions>=4.8.0 (from torch)
  Downloading https://download.pytorch.org/whl/nightly/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/nightly/networkx-3.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 77.5 MB/s eta 0:00:00
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/nightly/Jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting fsspec (from torch)
  Downloading https://download.pytorch.org/whl/nightly/fsspec-2024.6.1-py3-none-any.whl (177 kB)
Collecting pytorch-triton-xpu==3.1.0+91b14bf559 (from torch)
  Downloading https://download.pytorch.org/whl/nightly/pytorch_triton_xpu-3.1.0%2B91b14bf559-cp310-cp310-linux_x86_64.whl (315.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 MB 191.8 MB/s eta 0:00:00
Collecting sympy==1.13.1 (from torch)
  Downloading https://download.pytorch.org/whl/nightly/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 46.3 MB/s eta 0:00:00
Requirement already satisfied: packaging in /opt/_internal/cpython-3.10.15/lib/python3.10/site-packages (from pytorch-triton-xpu==3.1.0+91b14bf559->torch) (24.1)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Downloading https://download.pytorch.org/whl/nightly/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 35.0 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: mpmath, typing-extensions, sympy, pytorch-triton-xpu, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 pytorch-triton-xpu-3.1.0+91b14bf559 sympy-1.13.1 torch-2.6.0.dev20240925+xpu typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
/opt/python/cp310-cp310/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:294: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
2.6.0.dev20240925+xpu
```

**Comment by kit1980** [comment]
Is this fixed?
Is milestone 2.5 still relevant?

**Comment by EikanWang** [comment]
@kit1980 , we mitigated this issue.

### PT 2.5:

#### W/O Fixing

The Intel GPU wheel page requires three steps to ensure the import torch runs properly.
- Install Intel GPU LTS or rolling driver
- Install Intel GPU bundle
- Source Intel GPU bundle

#### W/ Fixing

We have mitigated this issue. Users only need to install the Intel GPU driver—there’s no longer a need to go through the additional steps of installing and sourcing bundles to use import torch. The idea behind this mitigation is that users who don't have an Intel GPU won't need to install the Intel GPU wheel package. This makes the driver installation process more seamless and natural for users.
- Install Intel GPU LTS or rolling driver
- ~~Install Intel GPU bundle~~
- ~~Source Intel GPU bundle~~

### Post PT 2.5:
No steps are required to import torch
- ~~Install Intel GPU LTS or rolling driver~~
- ~~Install Intel GPU bundle~~
- ~~Source Intel GPU bundle~~

**Comment by atalman** [comment]
Test after installing a compiler:
```
apt-get install -y --no-install-recommends         build-essential         ca-certificates         ccache         cmake         curl         git         libjpeg-dev         libpng-dev 
```

Results:
```
python smoke_test.py --package torchonly                               
torch: 2.5.0+xpu
ATen/Parallel:
        at::get_num_threads() : 48
        at::get_num_interop_threads() : 48
OpenMP 201511 (a.k.a. OpenMP 4.5)
        omp_get_max_threads() : 48
Intel(R) oneAPI Math Kernel Library Version 2025.0.0-intel-for-pytorch-gpu-dev.4 Product Build 20240713 for Intel(R) 64 architecture applications
        mkl_get_max_threads() : 48
Intel(R) MKL-DNN v3.5.3 (Git Hash 66f0cb9eb66affd2da3bf5f8d897376f04aae6af)
std::thread::hardware_concurrency() : 96
Environment variables:
        OMP_NUM_THREADS : [not set]
        MKL_NUM_THREADS : [not set]
ATen parallel backend: OpenMP

Skip version check for channel None as stable version is None
Testing smoke_test_conv2d
Testing smoke_test_linalg on cpu
Testing smoke_test_compile for cpu and torch.float16
/root/miniconda3/lib/python3.12/site-packages/torch/xpu/__init__.py:60: UserWarning: XPU device count is zero! (Triggered internally at /pytorch/c10/xpu/XPUFunctions.cpp:50.)
  return torch._C._xpu_getDeviceCount()
/root/miniconda3/lib/python3.12/site-packages/torch/xpu/__init__.py:60: UserWarning: XPU device count is zero! (Triggered internally at /pytorch/c10/xpu/XPUFunctions.cpp:50.)
  return torch._C._xpu_getDeviceCount()
Testing smoke_test_compile for cpu and torch.float32
Testing smoke_test_compile for cpu and torch.float64
Picked CPU ISA VecAVX512 bit width 512
Testing smoke_test_compile with mode 'max-autotune' for torch.float32
```

**Comment by EikanWang** [comment]
@atalman , thanks for the test result.

**Comment by dvrogozh** [comment]
`torch.compile` part of the story might also need some fixes for XPU. See:
* https://github.com/pytorch/pytorch/issues/137518

**Comment by atalman** [comment]
@EikanWang I believe this break https://peps.python.org/pep-0599/#the-manylinux2014-policy

```
The wheel’s binary executables or shared objects may not link against externally-provided libraries except those in the following list:
libgcc_s.so.1
libstdc++.so.6
libm.so.6
libdl.so.2
librt.so.1
libc.so.6
libnsl.so.1
libutil.so.1
libpthread.so.0
libresolv.so.2
libX11.so.6
libXext.so.6
libXrender.so.1
libICE.so.6
libSM.so.6
libGL.so.1
libgobject-2.0.so.0
libgthread-2.0.so.0
libglib-2.0.so.0
````

**Comment by seemethere** [comment]
Chiming in here I'd say this issue is a show stopping issue for the xpu binaries for the 2.5 release.

All other accelerator types that PyTorch currently supports should be able at a baseline to `import torch` and run basic things like a `print(torch.__version__)`.

Here's a simple reproducer based on the current release candidates for all accelerator types:

```bash
#!/usr/bin/env bash

set -eou pipefail

test_can_version() {
  index=$1
  echo -n "+ ${index} ... "
  if ! docker run --rm -it python:3.10 bash -c "pip install --pre torch --index-url ${index}; python -c 'import torch;print(torch.__version__)'" >/dev/null 2>/dev/null; then
    echo "FAIL"
  else
    echo "pass"
  fi
}

test_can_version "https://download.pytorch.org/whl/test/cpu"
test_can_version "https://download.pytorch.org/whl/test/cu121"
test_can_version "https://download.pytorch.org/whl/test/rocm6.1"
test_can_version "https://download.pytorch.org/whl/test/xpu"
```

Output should look like:
```
+ https://download.pytorch.org/whl/test/cpu ... pass
+ https://download.pytorch.org/whl/test/cu121 ... pass
+ https://download.pytorch.org/whl/test/rocm6.1 ... pass
+ https://download.pytorch.org/whl/test/xpu ... FAIL
```

**Comment by chuanqi129** [comment]
This issue has been fixed in the latest xpu nightly wheel, please have a double check for it. @malfet @seemethere @atalman 
```shell
$ docker run --rm -it python:3.10 bash -c "pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu/; python -c 'import torch;print(torch.__version__)'"
Unable to find image 'python:3.10' locally
3.10: Pulling from library/python
cdd62bf39133: Pull complete 
a47cff7f31e9: Pull complete 
a173f2aee8e9: Pull complete 
01272fe8adba: Pull complete 
2503de423c42: Pull complete 
3f9262f6ef06: Pull complete 
fddd6c71e764: Pull complete 
Digest: sha256:aaacc373f21abcbc67a22d203dab7fb797c016cc4c1daa7d2dec359dcbf4aea1
Status: Downloaded newer image for python:3.10
Looking in indexes: https://download.pytorch.org/whl/nightly/xpu/
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/xpu/torch-2.6.0.dev20241011%2Bxpu-cp310-cp310-linux_x86_64.whl (852.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.3/852.3 MB 4.7 MB/s eta 0:00:00
Collecting fsspec
  Downloading https://download.pytorch.org/whl/nightly/fsspec-2024.6.1-py3-none-any.whl (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 78.8 MB/s eta 0:00:00
Collecting filelock
  Downloading https://download.pytorch.org/whl/nightly/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting sympy==1.13.1
  Downloading https://download.pytorch.org/whl/nightly/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 60.0 MB/s eta 0:00:00
Collecting typing-extensions>=4.8.0
  Downloading https://download.pytorch.org/whl/nightly/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting networkx
  Downloading https://download.pytorch.org/whl/nightly/networkx-3.3-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 83.9 MB/s eta 0:00:00
Collecting pytorch-triton-xpu==3.1.0+91b14bf559
  Downloading https://download.pytorch.org/whl/nightly/pytorch_triton_xpu-3.1.0%2B91b14bf559-cp310-cp310-linux_x86_64.whl (315.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 MB 13.0 MB/s eta 0:00:00
Collecting jinja2
  Downloading https://download.pytorch.org/whl/nightly/Jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 33.4 MB/s eta 0:00:00
Collecting packaging
  Downloading https://download.pytorch.org/whl/nightly/packaging-22.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 10.7 MB/s eta 0:00:00
Collecting mpmath<1.4,>=1.1.0
  Downloading https://download.pytorch.org/whl/nightly/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 78.4 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: mpmath, typing-extensions, sympy, packaging, networkx, MarkupSafe, fsspec, filelock, pytorch-triton-xpu, jinja2, torch
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 packaging-22.0 pytorch-triton-xpu-3.1.0+91b14bf559 sympy-1.13.1 torch-2.6.0.dev20241011+xpu typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/local/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:294: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:82.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
2.6.0.dev20241011+xpu
```
cc: @EikanWang

**Comment by dvrogozh** [comment]
@chuanqi129 : this works now for me without complaining on missing `libze_loader.so.1`. Can you, please, point to the PR which fixed the issue? Also, please, provide xpu nightly build version starting from which issue got resolved.

**Comment by malfet** [comment]
Thank you for your work. I can confirm it works with latest nightly.
And +1 on @dvrogozh asks: please mention changes that resulted in a fix.

**Comment by chuanqi129** [comment]
Hi @malfet @dvrogozh the issue is fixed by the new PTI version 0.9.1 public release, after that the nightly build docker image has installed the latest PTI version by default. So there is no source code side change. But we need to fix the xpu support package version in case future release break it. Refer PR https://github.com/pytorch/pytorch/pull/138189, which also need to cherry-pick to  release 2.5.1 I think.

**Comment by EikanWang** [comment]
@malfet , @atalman , @seemethere , we have fixed the issue. It would be appreciated if you could check the current XPU behavior as expected.
