### ISSUE TITLE
[triton 3.2] std::bad_alloc: torch.compile breaks with Triton built from source

### ISSUE THREAD

**Issue by mobicham** [pytorch/pytorch#140423]
### 🐛 Describe the bug

torch.compile breaks with Triton built from source (as of Nov 12):

How to reproduce: 
1) Build Triton from the master branch
2) Run torch.compile with a model containing Triton modules, in my case, <a href="https://github.com/mobicham/ao/blob/gemlite_integration_mobicham/torchao/_models/llama/benchmarks_gemlite_int8.sh">this script from ao</a>:

The same script works fine with triton==3.1.0:

```
 Time to load model: 2.09 seconds
Compiling Model
/opt/conda/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be remo
ved. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
Traceback (most recent call last):
  File "/root/zmore/ao/torchao/_models/llama/generate.py", line 711, in <module>
    main(
  File "/root/zmore/ao/torchao/_models/llama/generate.py", line 538, in main
    generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/zmore/ao/torchao/_models/llama/generate.py", line 132, in generate
    generated_tokens, _ = decode_n_tokens(model, next_token.view(batch_size, -1), input_pos, new_tokens-1, callback=callback, **sampling_kwargs)
  File "/root/zmore/ao/torchao/_models/llama/generate.py", line 71, in decode_n_tokens
    next_token, next_prob = decode_one_token(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 554, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1401, in __call__
    return self._torchdynamo_orig_callable(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 546, in __call__
    return _compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 979, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 705, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 740, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 659, in transform
    tracer.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2909, in run
    super().run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in run
    while self.step():
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1027, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3100, in RETURN_VALUE
    self._return(inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3085, in _return
    self.output.compile_subgraph(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1164, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1401, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1448, in call_user_compiler
    return self._call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1497, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1478, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 2275, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1398, in compile_fx
    return compile_fx(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1675, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1105, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1081, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 528, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 780, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 196, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1495, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1564, in _fw_compiler_base
    return inner_compile(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 572, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 100, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 724, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1479, in load
    compiled_graph = compile_fx_fn(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 635, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 942, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 2028, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1950, in compile_to_module
    return self._compile_to_module()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1956, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1895, in codegen
    self.scheduler.codegen()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 3457, in codegen
    return self._codegen()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 3536, in _codegen
    self.get_backend(device).codegen_node(node)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
    return self._triton_scheduling.codegen_node(node)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codegen/simd.py", line 1204, in codegen_node
    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codegen/simd.py", line 1399, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 3106, in codegen_kernel
    triton_meta["configs"] = [config_of(signature)]
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codegen/triton_utils.py", line 176, in config_of
    return AttrsDescriptorWrapper(divisible_by_16, equal_to_1)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/runtime/hints.py", line 55, in AttrsDescriptorWrapper
    res = AttrsDescriptor.from_dict(kwargs)
  File "/root/zmore/triton/python/triton/backends/compiler.py", line 167, in from_dict
    attrs_descriptor = _descriptor_table[data["cls"]]()
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
KeyError: 'cls'
```

### Versions

Collecting environment information...
PyTorch version: 2.6.0.dev20241028+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: glibc-2.35

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA H100 80GB HBM3
Nvidia driver version: 555.58.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.6.77
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] optree==0.11.0
[pip3] pytorch-triton==3.1.0+cf34004b8a
[pip3] torch==2.6.0.dev20241028+cu121
[pip3] torchao==0.7.0+git03c3889c
[pip3] torchaudio==2.3.1
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.19.0
[pip3] triton==3.2.0+git9d6736a5

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @bertmaher @int3 @davidberard98 @nmacchioni @chenyang78 @embg @peterbell10 @aakhundov

**Comment by mobicham** [comment]
I tried the latest nightly build, it breaks with another error:
```
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 1763, in __init__
    self._init(nodes)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 1815, in _init
    self.dead_node_elimination()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 2169, in dead_node_elimination
    can_eliminate = not node.has_side_effects() and not active_buffers
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 842, in has_side_effects
    return hasattr(self.node, "has_side_effects") and self.node.has_side_effects()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/ir.py", line 6274, in has_side_effects
    return get_schema_info(self.op_overload).is_mutable()
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
MemoryError: std::bad_alloc
```

**Comment by davidberard98** [comment]
Many of these issues have been fixed since october 28. Can you try with a newer version? I expect that the first issue will have been fixed, but I haven't seen the second one

**Comment by davidberard98** [comment]
@mobicham

1. If you're able to, it would be super helpful if you can help verify whether this is related to #140590, where we see a std::bad_alloc upon calling into a pybind op. One strategy: if you are able to run with `lldb` or `gdb` and set `catch throw` (for gdb; `breakpoint set -E c++` for lldb) and get a backtrace for where the std::bad_alloc comes from, that would help us understand if it's the same issue. (note: you might have to continue through a bunch of unrelated thrown exceptions until you get to the actual failure). Another strategy - if you are able to build pytorch (and maybe domain libraries) locally, the issue might go away; at least personally, me and one other person have been unable to reproduce outside of the nightly builds.
2. If you're not able to confirm for us, could you provide some details on how to run your script? In particular I don't have the llama model in the checkpoints directory. Alternatively, if you have a simpler script that reproduces the same issue that would also be great.

**Comment by mobicham** [comment]
@davidberard98 thank you for your input!
I just tried again today and it's finally working properly with the following versions:
```
torch: 2.6.0.dev20241112+cu121
triton: triton-3.2.0+git0bd30a2f 
```

**Comment by mobicham** [comment]
Sorry to reopen, but I get `std::bad_alloc` again, it seems that it happens on some machines. The one I used above was a 4090 and it worked, today I am tried on another machine with an H100 SXM4 and I et the error.
I traced it back to triton autotuning: if you remove autotuning, it works. Wrapping the kernel call in a `custom_op` doesn't resolve the issue. I made a minimal example to reproduce the error:

```Python
import torch
import triton
import triton.language as tl
from collections import OrderedDict

def get_config():
	configs = []
	configs.append(triton.Config({'BLOCK_SIZE': 1024}, num_stages=1, num_warps=1))
	configs.append(triton.Config({'BLOCK_SIZE': 1024}, num_stages=2, num_warps=1))
	configs.append(triton.Config({'BLOCK_SIZE': 512}, num_stages=2, num_warps=2))
	configs.append(triton.Config({'BLOCK_SIZE': 256}, num_stages=4, num_warps=2))
	return configs

@triton.autotune(
    configs=get_config(),
    key = ['n_elements'],
)

@triton.jit
def kernel(x_ptr, y_ptr, output_ptr, n_elements, BLOCK_SIZE: tl.constexpr):

    pid = tl.program_id(axis=0)  

    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)

    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    y = tl.load(y_ptr + offsets, mask=mask)
    output = x + y

    tl.store(output_ptr + offsets, output, mask=mask)


def op(x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    output = torch.empty_like(x)
    assert x.is_cuda and y.is_cuda and output.is_cuda
    n_elements = output.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta['BLOCK_SIZE']), )
    kernel[grid](x, y, output, n_elements)
    return output



class CustomLayer(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return op(x, x)

model = torch.nn.Sequential(OrderedDict([
          ('l1', CustomLayer()),
          ('l2', CustomLayer()),
          ('l3', CustomLayer()),
          ('l4', CustomLayer()),
        ]))



x = torch.randn((1024,), dtype=torch.float16, device='cuda') * 0.01

#Warm-up autotuning
y = model(x)

model.forward = torch.compile(model.forward, mode='reduce-overhead', fullgraph=True)

#Fails
y = model(x)
``` 


Error trace
```
File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2235, in CUDAGraphTreeManager.add_function(self, model, inputs, static_input_i
dxs, stack_traces, mode, constants, placeholders, mutated_input_idxs)
   2233 # container needs to set clean up when fn dies
   2234 get_container(self.device_index).add_strong_reference(fn)
-> 2235 return fn, fn(inputs)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:1929, in CUDAGraphTreeManager.run(self, new_inputs, function_id)
   1927 assert self.graph is not None, "Running CUDAGraph after shutdown"
   1928 self.mode = self.id_to_mode[function_id]
-> 1929 out = self._run(new_inputs, function_id)
   1931 # The forwards are only pending following invocation, not before
   1932 if self.mode == CompilationMode.FORWARD:

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2037, in CUDAGraphTreeManager._run(self, new_inputs, function_id)
   2031         self.apply_checkpoint_execution_state_in_allocator()
   2033     with dynamo_timed(
   2034         "CUDAGraphTreeManager.run_eager",
   2035         log_pt2_compile_event=True,
   2036     ):
-> 2037         out = self.run_eager(new_inputs, function_id)
   2039     return out
   2041 assert not isinstance(self.current_node, CUDAWarmupNode)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2201, in CUDAGraphTreeManager.run_eager(self, new_inputs, function_id)
   2199 self.path_state = ExecutionState.WARMUP
   2200 self.update_generation()
-> 2201 return node.run(new_inputs)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2037, in CUDAGraphTreeManager._run(self, new_inputs, function_id)
   2031         self.apply_checkpoint_execution_state_in_allocator()
   2033     with dynamo_timed(
   2034         "CUDAGraphTreeManager.run_eager",
   2035         log_pt2_compile_event=True,
   2036     ):
-> 2037         out = self.run_eager(new_inputs, function_id)
   2039     return out
   2041 assert not isinstance(self.current_node, CUDAWarmupNode)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:2201, in CUDAGraphTreeManager.run_eager(self, new_inputs, function_id)
   2199 self.path_state = ExecutionState.WARMUP
   2200 self.update_generation()
-> 2201 return node.run(new_inputs)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:637, in CUDAWarmupNode.run(self, new_inputs)
    635 if config.triton.slow_path_cudagraph_asserts and not self.already_warm:
    636     refs = list(self.path_live_weakrefs())
--> 637     check_memory_pool(self.device_index, self.cuda_graphs_pool, refs)
    639 with torch.cuda.device(
    640     self.device_index
    641 ), disable_conv_cache_emptying(), clear_cublas_manager(), _use_cuda_memory_pool_manager(
    642     self.device_index, self.cuda_graphs_pool, self.stream
    643 ), get_history_recording():
    644     out = self.wrapped_function.model(new_inputs)

File /opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py:1734, in check_memory_pool(device, pool_id, live_storages_ptrs)
   1730 unique_storages = {stor.data_ptr() for stor in live_storages_ptrs if stor()}
   1732 # check if there is a divergence first, then do the expensive snapshot call after
   1733 # we know it will error
-> 1734 if torch._C._cuda_checkPoolLiveAllocations(device, pool_id, unique_storages):
   1735     return
   1737 # at this point we are past the fast-path. we have seen rare cases where a dead tensor is dead,
   1738 # but hasn't been gc'd yet, and gives false positive for allocated_not_in_live_storages

MemoryError: std::bad_alloc
```

Versions
```
In [2]: torch.__version__
Out[2]: '2.6.0.dev20241112+cu121'

In [3]: triton.__version__
Out[3]: '3.1.0'
```

**Comment by mobicham** [comment]
So I tried many nightly builds from November, the last one that works is `torch==2.6.0.dev20241101+cu121`, something is broken since `torch==2.6.0.dev20241102+cu121``

**Comment by aakhundov** [comment]
In the latest stack trace, I see CUDAGraph-related code. Wondering if this is expected. cc @eellison @davidberard98.

**Comment by davidberard98** [comment]
@mobicham are you able to get a gdb / lldb stacktrace?

**Comment by davidberard98** [comment]
I'm guessing this is #140590 based on the timeline (nov 1 nightly works, nov 2 doesn't). In those cases we see that the std::bad_alloc comes from pybind while converting types; there's one case where the failure happens during a pybind-ed torchscript function, one from an autograd function, and now (in this issue) in `_cuda_checkPoolLiveAllocations`.

**Comment by davidberard98** [comment]
btw @mobicham we haven't been able to repro this with pytorch built from source. So if you are able to build pytorch from source, I think this will probably unblock you

**Comment by mobicham** [comment]
Thanks @davidberard98 , for now I am using `torch==2.6.0.dev20241101+cu121` which works fine. 

This is what I get with **gdb** (`2.6.0.dev20241112+cu121`):

```
(gdb) run
Starting program: /opt/conda/bin/python test_torch.py
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f4bd1c84640 (LWP 2257)]
[New Thread 0x7f49c6dff640 (LWP 2258)]
[Detaching after vfork from child process 2259]
[Detaching after vfork from child process 2260]
[Detaching after vfork from child process 2261]
[New Thread 0x7f49affff640 (LWP 2262)]
[New Thread 0x7f49adafd640 (LWP 2263)]
[Detaching after vfork from child process 2264]
Traceback (most recent call last):
  File "/root/zmore/test_torch.py", line 70, in <module>
    y = model(x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 556, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 29, in inner
    @functools.wraps(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 721, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1132, in forward
    return compiled_fn(full_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 324, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 673, in inner_fn
    outs = compiled_fn(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 491, in wrapper
    return compiled_fn(runtime_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1686, in __call__
    return self.current_callable(inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1104, in run
    return compiled_fn(new_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 398, in deferred_cudagraphify
    fn, out = cudagraphify(model, inputs, new_static_input_idxs, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 428, in cudagraphify
    return manager.add_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2235, in add_function
    return fn, fn(inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1929, in run
    out = self._run(new_inputs, function_id)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2037, in _run
    out = self.run_eager(new_inputs, function_id)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 2201, in run_eager
    return node.run(new_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 637, in run
    check_memory_pool(self.device_index, self.cuda_graphs_pool, refs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1734, in check_memory_pool
    if torch._C._cuda_checkPoolLiveAllocations(device, pool_id, unique_storages):
MemoryError: std::bad_alloc
[Thread 0x7f49adafd640 (LWP 2263) exited]
[Thread 0x7f49affff640 (LWP 2262) exited]
[Thread 0x7f49c6dff640 (LWP 2258) exited]
[Thread 0x7f4bd1c84640 (LWP 2257) exited]
[Inferior 1 (process 2254) exited with code 01]
(gdb) 
```

**Comment by davidberard98** [comment]
@mobicham thanks for checking - however, to get a stacktrace from gdb I think you'll have to set `catch throw` (see comment here https://github.com/pytorch/pytorch/issues/140423#issuecomment-2479778319)

**Comment by mobicham** [comment]
Sorry for the delay @davidberard98 , I just tried with the nightly build and luckily it's working this time (`2.6.0.dev20241218+cu124`)
Really appreciate your support, thanks!
