### ISSUE TITLE
torch.compile + Huggingface GenerationMixin

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#141196]
### 🐛 Describe the bug

error: https://gist.github.com/xmfan/7374fab55bdf73ba2501de15dd9de709
```
ValueError: The following `model_kwargs` are not used by the model: ['bos_token_id', 'pad_token_id', 'eos_token_id', 'max_length', 'do_sample', 'top_p', 'top_k', 'temperature', 'num_return_sequences', 'num_beams', 'length_penalty', 'repetition_penalty'] 
```

`GenerationMixin.generate` contains the implementation of most HF generative models' `forward` pass. During `GenerationMixin.generate`, `GenerationMixin._validate_model_kwargs` is called, and it raises an exception if not all model kwargs passed are used by the model: https://github.com/huggingface/transformers/blob/40821a247823b35d7ff10ba490d0d930fe8f5afa/src/transformers/generation/utils.py#L1380-L1384. This error only appears if we do a top-level compile (it works if we directly wrap the HF model class with torch.compile), see repro below.

monkey patching some prints, the difference seems to be from different model_kwargs:
```python
# eager
model_kwargs={
 'attention_mask': ...,
 'd_vector': None,
 'input_tokens': None,
 'voice_dirs': None}
model_args={'attention_mask',
 'encoder_attention_mask',
 'encoder_hidden_states',
 'head_mask',
 'input_ids',
 'inputs_embeds',
 'kwargs',
 'labels',
 'output_attentions',
 'output_hidden_states',
 'past_key_values',
 'position_ids',
 'return_dict',
 'token_type_ids',
 'use_cache'}

# compile 
model_kwargs={
 'attention_mask': ...,
 'bos_token_id': 1024,
 'd_vector': None,
 'do_sample': True,
 'eos_token_id': 1025,
 'input_tokens': None,
 'length_penalty': 1.0,
 'max_length': 650,
 'num_beams': 1,
 'num_return_sequences': 1,
 'output_attentions': False,
 'pad_token_id': 1025,
 'repetition_penalty': 5.0,
 'temperature': 0.75,
 'top_k': 50,
 'top_p': 0.85,
 'voice_dirs': None}
model_args={
 'attention_mask',
 'encoder_attention_mask',
 'encoder_hidden_states',
 'head_mask',
 'input_ids',
 'inputs_embeds',
 'kwargs',
 'labels',
 'output_attentions',
 'output_hidden_states',
 'past_key_values',
 'position_ids',
 'return_dict',
 'token_type_ids',
 'use_cache'}
```

Repro 
install repo via frozen_requirements.txt: https://github.com/xmfan/coqui-ai-TTS/tree/empathy
```python
import torch
from TTS.api import TTS
import time

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=True)

# Run TTS
def fn():
    tts.tts(text="Hello from XTTS2. I am being tested for the torch.compile User Empathy Day on Nov 20th 2024.", speaker_wav="en_sample.wav", language="en")

@torch.compile(backend="eager")
def warmup(its=5):
    for i in range(its):
        start = time.time()
        fn()
        duration = time.time() - start
        print(f"warm up i={i} took {duration}s")

warmup()
```

### Versions

install the repo using `frozen_requirements.txt`

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames

**Comment by xmfan** [comment]
The difference in model_kwargs is due to this branch in transformers: https://github.com/huggingface/transformers/blob/40821a247823b35d7ff10ba490d0d930fe8f5afa/src/transformers/generation/utils.py#L1535-L154

```python
        # `torch.compile` can't compile `copy.deepcopy`, arguments in `kwargs` that are part of `generation_config`
        # will mutate the object with `.update`. As such, passing these arguments through `kwargs` is disabled -- an
        # exception will be raised in `_validate_model_kwargs`
        if not is_torchdynamo_compiling():
            generation_config = copy.deepcopy(generation_config)
            model_kwargs = generation_config.update(**kwargs)
            # If `generation_config` is provided, let's fallback ALL special tokens to the default values for the model
            if not using_model_generation_config:
                if generation_config.bos_token_id is None:
                    generation_config.bos_token_id = self.generation_config.bos_token_id
                if generation_config.eos_token_id is None:
                    generation_config.eos_token_id = self.generation_config.eos_token_id
                if generation_config.pad_token_id is None:
                    generation_config.pad_token_id = self.generation_config.pad_token_id
                if generation_config.decoder_start_token_id is None:
                    generation_config.decoder_start_token_id = self.generation_config.decoder_start_token_id
        else:
            model_kwargs = kwargs
```

**Comment by eellison** [comment]
no updates, looking this week

**Comment by eustlb** [comment]
Hey there,

The frozen-requirements.txt file pins Transformers to version 4.46.2. Copy-pasting _prepare_generation_config from the main branch seems to fix the issue (no more crashes, at least), which confirms that this problem was likely resolved in a version after 4.46.2.

Since coqui-ai/TTS is no longer actively maintained and doesn’t support the latest versions of Transformers, I’d suggest one of the following approaches:
	1.	Manually install a Transformers version >4.46.2 that resolves the issue while remaining compatible with the current Coqui TTS codebase.
	2.	Install Transformers in editable mode and copy-paste _prepare_generation_config from the main branch.

**Comment by StrongerXi** [comment]
@eustlb thank you!

I've confirmed the error goes away for `transformers>=4.50.0`, and the TTS project also updated their dependency to have `transformers>=4.47.0` [3 months ago](https://github.com/idiap/coqui-ai-TTS/blame/dev/pyproject.toml#L85), so we should be good here.

I ran into another error, but that'll be fixed by #153216, after that we still have some graph breaks and recompilation limit hits, notably from this:
```
W0508 16:30:22.270000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [66/8] torch._dynamo hit config.recompile_limit (8)
W0508 16:30:22.270000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [66/8]    function: '__call__' (/home/ryanguo99/.conda/envs/tts/lib/python3.10/site-packages/transformers/generation/logits_process.py:62)
W0508 16:30:22.270000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [66/8]    last reason: 66/1: Cache line invalidated because list.__getitem__(L['self'], 0) got deallocated
W0508 16:30:22.270000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [66/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0508 16:30:22.270000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [66/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
W0508 16:30:22.277000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [67/8] torch._dynamo hit config.recompile_limit (8)
W0508 16:30:22.277000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [67/8]    function: '__call__' (/home/ryanguo99/.conda/envs/tts/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py:497)
W0508 16:30:22.277000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [67/8]    last reason: 67/1: Cache line invalidated because list.__getitem__(L['self'], 0) got deallocated
W0508 16:30:22.277000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [67/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0508 16:30:22.277000 150408 site-packages/torch/_dynamo/convert_frame.py:964] [67/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
```

But the e2e perf has a consistent 40%+ speed up, for top-level compile over `tts.tts(...)` call. So I think we can close this issue.
