### ISSUE TITLE
Library not loaded: libmklml.dylib use c++ front

### ISSUE THREAD

**Issue by hggq** [pytorch/pytorch#14165]
192:build hzq$ cmake -DCMAKE_PREFIX_PATH=/Users/hzq/Documents/www/test/libtorch ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found torch: /Users/hzq/Documents/www/test/libtorch/lib/libtorch.dylib  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hzq/Documents/www/test/libtorch/example-app/build
192:build hzq$ make
Scanning dependencies of target example-app
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
[100%] Built target example-app
192:build hzq$ ./example-app 
**dyld: Library not loaded: @rpath/libmklml.dylib**
  Referenced from: /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.dylib
  Reason: image not found
Abort trap: 6

my os upate after : mac os mojave/  xcode 10.1/ cmake version 3.13.0-rc3
before macOS 10.13 High Sierra  test ok

**Comment by soumith** [comment]
cc: @pjh5 can you check with `otool -L` for this dependency and see if we need to copy this lib over as well in our binary scripts?

Also @t-vi was seeing the same issue in a different context

**Comment by t-vi** [comment]
Thanks. I think my case is a bit different as I do have the lib, it's just that between rpaths and things, the Python module (or its dependencies) don't look in the obvious place.

**Comment by pjh5** [comment]
Could you run the following command? Thatt flag is a lowercase L
`otool -l /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.dylib | grep LC_RPATH -A2`

**Comment by hggq** [comment]
192:build hzq$ otool -l /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.dylib | grep LC_RPATH -A2
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 104
         path /Users/administrator/nightlies/2018_11_19/wheel_build_dirs/libtorch_2.7/pytorch/build/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 160
         path /Users/administrator/nightlies/2018_11_19/wheel_build_dirs/libtorch_2.7/pytorch/third_party/ideep/mkl-dnn/external/mklml_mac_2018.0.3.20180406/lib (offset 12)
===================
 I didn't use Python, I want to use pure c++.

**Comment by hggq** [comment]
I haven't installed intel MKL

**Comment by houseroad** [comment]
Same problem here, seems that libcaffe2 is linked against libmklml, however, libmklml is not provided.

**Comment by houseroad** [comment]
After adding/copying libmklml to the right position, I hit another error: Library not loaded: libiomp5.dylib. And after adding/copying this lib file, I am able to run the program.

**Comment by hggq** [comment]
> After adding/copying libmklml to the right position, I hit another error: Library not loaded: libiomp5.dylib. And after adding/copying this lib file, I am able to run the program.

 Thank you. I just start learn .
 I think there are many people like me who want to use pure C++ as front-end development machine learning.

**Comment by hggq** [comment]
> cc: @pjh5 can you check with `otool -L` for this dependency and see if we need to copy this lib over as well in our binary scripts?
> 
> Also @t-vi was seeing the same issue in a different context
----------------------

Last login: Mon Nov 26 10:31:03 on ttys001
192:~ hzq$ otool -l /Users/hzq/Documents/www/test/libtorch/lib/libcaffe2.dylib | grep LC_RPATH -A2
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 104
         path /Users/administrator/nightlies/2018_11_19/wheel_build_dirs/libtorch_2.7/pytorch/build/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 160
         path /Users/administrator/nightlies/2018_11_19/wheel_build_dirs/libtorch_2.7/pytorch/third_party/ideep/mkl-dnn/external/mklml_mac_2018.0.3.20180406/lib (offset 12)
192:~ hzq$ ls /Users/administrator/nightlies
ls: /Users/administrator/nightlies: No such file or directory
192:~ hzq$ 

My computer doesn't have this administrator directory.

**Comment by Arnold1** [comment]
cool. could you add that in the doc -> https://pytorch.org/cppdocs/installing.html ? :)

**Comment by houseroad** [comment]
seems we don't have (good) instructions on how to build the libtorch from source.

cc: @soumith and @orionr

**Comment by Arnold1** [comment]
@houseroad thanks works now!

**Comment by Arnold1** [comment]
@houseroad i still see some issues when i copy that libs to libtorch/lib folder

**Comment by yngtodd** [comment]
Thanks @Arnold1, your approach worked for me. 

I compiled Pytorch from source, and the build steps described in the C++ frontend install [docs](https://pytorch.org/cppdocs/installing.html) did not work for me. Similar to what @SPark9625 pointed out, I did not have `libmklml.dylib` in my `/path/to/libtorch/lib`. However, that did not exist in my `/path/to/pytorch/torch/lib` despite having used the following when compiling Pytorch:

```
export CMAKE_PREFIX_PATH=[anaconda root directory]
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch

MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```
I must have messed up somewhere when compiling Pytorch. However, I can get the C++ frontend to work when I use the following:

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/path/to/pytorch/torch
make
```
I am on MacOS 10.14

**Comment by hggq** [comment]
Hi,already solution
download last zip file
https://download.pytorch.org/libtorch/cpu/libtorch-macos-latest.zip 
download intel MKL-DNN Latest release
https://github.com/intel/mkl-dnn/releases



> The solutions here didn't work for me. I ended up doing the following.
> 
>     1. Downloaded the a .tar.gz of the latest release of mklml for my platform
> 
>     2. Extract the .tar.gz.
> 
>     3. Copy the .dylib files from lib/ within the extracted folder to libtorch/lib/

**Comment by lizhengwei1992** [comment]
I have the same issue.
I fixed it by the follow solution:

Firstly, build mkl-dnn from [github](https://github.com/intel/mkl-dnn) using source codes;
Then copy **libiomp5.dylib** and **libmklml.dylib** to  **your_path/libtorch/lib/**;
Get it !

**Comment by aalhaimi** [comment]
No need to build `mkl-dnn`to get the libraries.. any of these assets would have the libraries needed in `libtorch/lib` precompiled for you. 
<img width="971" alt="screen shot 2019-01-01 at 6 44 25 pm" src="https://user-images.githubusercontent.com/4491274/50577417-b10bcd00-0df5-11e9-9a1e-21388a16b6cb.png">

**Comment by artidoro** [comment]
I am running in the same issue.
Is there a reason why the libtorch package cannot include `libmklml.dylib`?
Could there be extra documentation on using libtorch on mac in the meantime?

**Comment by pjh5** [comment]
MKL is a linear algebra library that is needed for decent performance on MacOS. Many Windows and Linux users that care about performance use GPUs or other linear algebra libraries for cpu. Since we don't set MKL as the default on these systems, we don't build the binaries against MKL so that users don't need to install MKL as a hard dependency

**Comment by reuben** [comment]
The latest releases no longer have mklml assets available. Does PyTorch publish libmklml.dylib somewhere? I don't understand why this bug is closed as it's clearly still a problem: the libtorch package on macOS depends on libmklml.dylib but doesn't include the dependency. If I understand @pjh5's comment correct, the dependency on mklml isn't even required, so why enable it just to ship incomplete packages?

**Comment by pjh5** [comment]
I remember there used to be a flag that controlled if ideep and mklml were included or not. Now it looks like they are unconditionally included in https://github.com/pytorch/pytorch/blob/master/caffe2/CMakeLists.txt#L80 . The mklml linked against by the libtorch binaries indeed comes from third_party . Currently, no wheel or macos libtorch includes any dependencies, other than what comes from pip or conda. @soumith , is there a reason why we don't include dependencies into the zips just like we do for the linux builds?

**Comment by lelayf** [comment]
I would suggest reopening this issue, having the exact same problem on MacOS. Also the `wget` in installation page points us to a version that will not work on MacOS, saving an extra investigation hoop from there could be useful.

**Comment by pjh5** [comment]
cc @kostmo

**Comment by soumith** [comment]
this indeed needs to be fixed, we should include mklml.dylib in the osx wheels, and add import smoke-tests that will trigger the issue.

**Comment by malik-ali** [comment]
For those still stuck on this, @gress2 and @hggq's answers still work but not using the latest release of mkl-dnn from https://github.com/intel/mkl-dnn/releases. You can use [version 0.20](https://github.com/intel/mkl-dnn/releases/tag/v0.20) and it will have the appropriate `libmklml.dylib` and `libiomp5.dylib` files in the lib/ folder. You can copy these into the libtorch/lib folder and it should hopefully work 

Posting this so other people don't have to also waste their time figuring this out.

**Comment by soumith** [comment]
this has been fixed in the v1.2 binaries, and I've verified it manually.
Please reopen the issue if you somehow still see this issue on v1.2.0 or nightly builds

**Comment by mdlockyer** [comment]
Looks like this still persists in 1.2.0. I ran into this same issue and had to follow @malik-ali instructions and download mkl-dnn v2.0 and copy `libiomp5.dylib` and `libmklml.dylib` into libtorch manually.

> dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /usr/local/libtorch/lib/libtorch.dylib
  Reason: image not found
Abort trap: 6

**Comment by hggq** [comment]
V1.2.0 already contains intel's new version of DNN libmkldnn.1.0.dylib, but it does not contain libmklml.dylib, possibly v1.2.0 also uses old code.

**Comment by sonNeturo** [comment]
Yes can confirm with 1.2:
`dyld: Library not loaded: @rpath/libmklml.dylib
Referenced from: path/libtorch/lib/libtorch.dylib
Reason: image not found
Abort trap: 6
`

**Comment by soumith** [comment]
sigh. we fixed it for the wheels, but not for libtorch I think. Will take a look.

**Comment by soumith** [comment]
@yf225 apparently this is fixed in latest MKL-DNN upgrade. It is pending land https://github.com/pytorch/pytorch/pull/22910

**Comment by reuben** [comment]
Seems to work for me with latest libtorch! Thanks for fixing this! \o/
