### ISSUE TITLE
[ued] Investigate diffuser pipeline transformer recompilations due to different width/height

### ISSUE THREAD

**Issue by StrongerXi** [pytorch/pytorch#150702]
### 🐛 Describe the bug

From a user: https://github.com/huggingface/diffusers/issues/10795#issuecomment-2745417752

> 2. Changing the pipeline resolution triggers a recompilation, this happens with both dynamic=None and dynamic=True and resolution affecting the compilation is the most annoying issue right now.

We should look into the root cause of this. The user's testing script is [here](https://github.com/AstraliteHeart/torch-compile-tests-for-diffusers/blob/main/test_resolution_switching.py), but I didn't see any recompilation with the following minimal repro (`dynamic=None` also recompiles only once):

Repro:
```python
import torch
from diffusers import (
    AuraFlowPipeline,
    GGUFQuantizationConfig,
    AuraFlowTransformer2DModel,
)

transformer = AuraFlowTransformer2DModel.from_single_file(
    "https://huggingface.co/city96/AuraFlow-v0.3-gguf/blob/main/aura_flow_0.3-Q2_K.gguf",
    quantization_config=GGUFQuantizationConfig(compute_dtype=torch.bfloat16),
    torch_dtype=torch.bfloat16,
)
pipeline = AuraFlowPipeline.from_pretrained(
    "fal/AuraFlow-v0.3",
    torch_dtype=torch.bfloat16,
    transformer=transformer,
).to("cuda")

pipeline.transformer = torch.compile(pipeline.transformer, fullgraph=True, dynamic=True)
pipeline("A cute pony", width=256, height=256, num_inference_steps=1)
pipeline("A cute pony", width=384, height=384, num_inference_steps=1)
pipeline("A cute pony", width=512, height=512, num_inference_steps=1)
```

### Versions

bb987492302, python 3.11

cc @chauhang @penguinwu @ezyang @bobrenjc93 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

**Comment by xmfan** [comment]
Could it be only on `PyTorch version (GPU?): 2.6.0+cu124 (True)`

**Comment by StrongerXi** [comment]
> Could it be only on `PyTorch version (GPU?): 2.6.0+cu124 (True)`

That's the setting for the original issue, but in this comment they've grabbed the nightly (2 weeks ago) and applied my tensor-subclass-related stack (which has now landed and tested with my repro above, and it shouldn't have anything to do with dynamic shapes).

**Comment by AstraliteHeart** [comment]
```bash
# pip install --pre torch==2.8.0.dev20250405+cu128 torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
# Successfully Successfully installed torch-2.8.0.dev20250405+cu128 torchaudio-2.6.0.dev20250405+cu128 torchvision-0.22.0.dev20250405+cu128
# pip install git+https://github.com/huggingface/diffusers.git
# Successfully installed diffusers-0.33.0.dev0
```

```python
pipeline.transformer = torch.compile(pipeline.transformer, fullgraph=True, dynamic=True)
pipeline("A cute pony", width=256, height=256, num_inference_steps=1)
pipeline("A cute pony", width=384, height=384, num_inference_steps=1)
pipeline("A cute pony", width=512, height=512, num_inference_steps=1)

print("1024x512")
pipeline("A cute pony", width=1024, height=512, num_inference_steps=1)
```

```bash
TORCH_LOGS="recompiles" python test.py
Loading pipeline components...
02:58:11.287000 1790554 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles] Recompiling function forward in XXX/lib/python3.10/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py:447
V0406 02:58:11.287000 1790554 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0406 02:58:11.287000 1790554 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: hidden_states.size()[3] == hidden_states.size()[2]  # duck sizing added this equality because these variables had the same size 32 (to avoid this specialization, set torch.fx.experimental._config.use_duck_shape = False)
```

I first launched the script and let it compile everything, then I added the 1024x512 resolution and relaunched the script, triggering a recompilation only when it reached the 1024x512 resolution.

**Comment by AstraliteHeart** [comment]
Trying 512x1024 after 1024x512 also triggers recompilation.

```
V0406 06:19:52.957000 1802448 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles] Recompiling function forward in XXX/lib/python3.10/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py:447
V0406 06:19:52.957000 1802448 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0406 06:19:52.957000 1802448 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: hidden_states.size()[3] == hidden_states.size()[2]  # duck sizing added this equality because these variables had the same size 32 (to avoid this specialization, set torch.fx.experimental._config.use_duck_shape = False)
```

**Comment by StrongerXi** [comment]
Ah I see, thanks for the repro, if you look closely at the recompile message it says:

> - 0/0: hidden_states.size()[3] == hidden_states.size()[2]  # duck sizing added this equality because these variables had the same size 32 (to avoid this specialization, set torch.fx.experimental._config.use_duck_shape = False)

So if you apply `torch.fx.experimental._config.use_duck_shape = False`, that should fix it. This recompilation probably can't be avoided by default (without this config change). cc @bobrenjc93 for dynamic shape, is duck shape on by default because it helps with dynamic shape simplification and potentially downstream optimizations?

And cc @anijain2305 @DN6 as this (and maybe `dyanmic=True`) is something we could experiment with diffuser pipeline and see what's the optimal default here, maybe we can localize this config change inside some higher-level API like `pipeline.compile` so users don't have to worry about it.

**Comment by AstraliteHeart** [comment]
@StrongerXi Thank you! I was sure I tried `torch.fx.experimental._config.use_duck_shape = False` but I went back and re-run all the tests in a new clean env and indeed it helps, but I was able to find a different failure case - going to 1536x1536 triggered

```python
site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles] Recompiling function forward in XXX/lib/python3.10/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py:447
V0408 05:26:15.543000 2071778 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0408 05:26:15.543000 2071778 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: (((-1)*(hidden_states.size()[2] // (2*self._modules['pos_embed'].patch_size))) + ((math.trunc(torch.sym_float(self._modules['pos_embed'].pos_embed_max_size) ** 0.5)) // 2)) != 0  # original_pe_indexes = original_pe_indexes[starth:endh, startw:endw]  # diffusers/models/transformers/auraflow_transformer_2d.py:84 in pe_selection_index_based_on_dim (_dynamo/utils.py:3322 in run_node)
```

alarmingly, I get this recompilation on each script restart

```python
import torch
import diffusers
from diffusers import (
    AuraFlowPipeline,
    GGUFQuantizationConfig,
    AuraFlowTransformer2DModel,
)

torch.fx.experimental._config.use_duck_shape = False

transformer = AuraFlowTransformer2DModel.from_single_file(
    "https://huggingface.co/city96/AuraFlow-v0.3-gguf/blob/main/aura_flow_0.3-Q2_K.gguf",
    quantization_config=GGUFQuantizationConfig(compute_dtype=torch.bfloat16),
    torch_dtype=torch.bfloat16,
)
pipeline = AuraFlowPipeline.from_pretrained(
    "fal/AuraFlow-v0.3",
    torch_dtype=torch.bfloat16,
    transformer=transformer,
).to("cuda")

pipeline.transformer = torch.compile(pipeline.transformer, fullgraph=True, dynamic=True)
pipeline("A cute pony", width=256, height=256, num_inference_steps=1)
pipeline("A cute pony", width=384, height=384, num_inference_steps=1)
pipeline("A cute pony", width=512, height=512, num_inference_steps=1)

print("1024x512")
pipeline("A cute pony", width=1024, height=512, num_inference_steps=1)

print("512x1024")
pipeline("A cute pony", width=512, height=1024, num_inference_steps=1)

print("1536x1536")
pipeline("A cute pony", width=1536, height=1536, num_inference_steps=1)
print("1536x768")
pipeline("A cute pony", width=1536, height=768, num_inference_steps=1)
```

i.e. each run of this script I (only) see recompilation after "1536x1536" and after "1536x768"

**Comment by StrongerXi** [comment]
``` 
- 0/0: (((-1)*(hidden_states.size()[2] // (2*self._modules['pos_embed'].patch_size))) + ((math.trunc(torch.sym_float(self._modules['pos_embed'].pos_embed_max_size) ** 0.5)) // 2)) != 0  # original_pe_indexes = original_pe_indexes[starth:endh, startw:endw]  # diffusers/models/transformers/auraflow_transformer_2d.py:84 in pe_selection_index_based_on_dim (_dynamo/utils.py:3322 in run_node)
```

@bobrenjc93 would you mind weighing in here? Unless the dynamism is inherent, ideally there should probably be:
1. _Some_ workaround that can prevent recompilation altogether, at the acknowledged inference latency cost.
2. A series of hints like `_config.use_duck_shape = False` so that users can eventually get to that workaround.

**Comment by bobrenjc93** [comment]
@AstraliteHeart can you try rewriting the tensor indexing with narrow instead per the "You are overspecializing" section of the following dynamic shapes guide: https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?tab=t.0#heading=h.44gwi83jepaj

cc @pianpwk @laithsakka this might be an interesting one to look at since it probably involves guard_size_oblivious and 0/1 specialization on a backed symint

**Comment by AstraliteHeart** [comment]
I gave it a shot and made some progress. 

With https://github.com/huggingface/diffusers/commit/85ea323fe95f8afe4b63a922482f011cd06c8581 I see a single quick recompilation when going to higher resolutions, which still happens on each script relaunch (separate bug?). 

Unfortunately my attempts to push it further were unsuccessful. 

```bash
V0409 21:34:47.518000 2258158 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles] Recompiling function forward in XXX/lib/python3.10/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py:447
V0409 21:34:47.518000 2258158 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0409 21:34:47.518000 2258158 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: math.trunc(torch.sym_float(self._modules['pos_embed'].pos_embed_max_size) ** 0.5) != (hidden_states.size()[3] // self._modules['pos_embed'].patch_size)  # return narrowed.flatten()  # diffusers/models/transformers/auraflow_transformer_2d.py:85 in pe_selection_index_based_on_dim (_dynamo/utils.py:3333 in run_node)
```

@sayakpaul @yiyixuxu any ideas on how to fix this right?

Also the good news is that while we get hit hard by https://github.com/pytorch/pytorch/issues/150706 this is somewhat production ready, you only need to load the compilation cache and do one extra recompilation after which you can enjoyt the compilation speedups.

**Comment by sayakpaul** [comment]
Thanks for the tag!

```
V0409 21:34:47.518000 2258158 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: math.trunc(torch.sym_float(self._modules['pos_embed'].pos_embed_max_size) ** 0.5) != (hidden_states.size()[3] // self._modules['pos_embed'].patch_size)  # return narrowed.flatten()  # diffusers/models/transformers/auraflow_transformer_2d.py:85 in pe_selection_index_based_on_dim (_dynamo/utils.py:3333 in run_node)
```

This seems like an obvious reason but then I don't have the full picture. Admittedly a random suggestion -- would keeping `h_p`, `w_p`, `h_max`, and `w_max` as tensors help avoid the issue?

> Also the good news is that while we get hit hard by https://github.com/pytorch/pytorch/issues/150706 this is somewhat production ready, you only need to load the compilation cache and do one extra recompilation after which you can enjoy the compilation speedups.

That is great news! Do you have a small snippet to show what needs to be done on the user front?

**Comment by AstraliteHeart** [comment]
@sayakpaul thank you for having a look! At this point most fixes are submitted so it's pretty simple. Here is the minimal repro:

```bash
pip install --pre torch==2.8.0.dev20250405+cu128 torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
pip install git+https://github.com/AstraliteHeart/diffusers.git@6bd6b7c360af25cdbc7f42a07cc228137d24bc3c
```

```python
import torch
import diffusers
from diffusers import (
    AuraFlowPipeline,
    GGUFQuantizationConfig,
    AuraFlowTransformer2DModel,
)

torch.fx.experimental._config.use_duck_shape = False

transformer = AuraFlowTransformer2DModel.from_single_file(
    "https://huggingface.co/city96/AuraFlow-v0.3-gguf/blob/main/aura_flow_0.3-Q2_K.gguf",
    quantization_config=GGUFQuantizationConfig(compute_dtype=torch.bfloat16),
    torch_dtype=torch.bfloat16,
)
pipeline = AuraFlowPipeline.from_pretrained(
    "fal/AuraFlow-v0.3",
    torch_dtype=torch.bfloat16,
    transformer=transformer,
).to("cuda")

pipeline.transformer = torch.compile(pipeline.transformer, fullgraph=True, dynamic=True)

pipeline("A cute pony", width=256, height=256, num_inference_steps=1)
# extra compilation here
pipeline("A cute pony", width=1536, height=1536, num_inference_steps=1)
```

```bash
TORCH_LOGS="recompiles" python test.py
```

You will see that second pipeline call triggering the recompilation with

```bash
V0410 05:10:59.433000 2295105 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles] Recompiling function forward in XXX/lib/python3.10/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py:447
V0410 05:10:59.433000 2295105 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0410 05:10:59.433000 2295105 site-packages/torch/_dynamo/guards.py:3050] [0/1] [__recompiles]     - 0/0: math.trunc(torch.sym_float(self._modules['pos_embed'].pos_embed_max_size) ** 0.5) != (hidden_states.size()[3] // self._modules['pos_embed'].patch_size)  # return narrowed.flatten()  # diffusers/models/transformers/auraflow_transformer_2d.py:85 in pe_selection_index_based_on_dim (_dynamo/utils.py:3333 in run_node)
```

you can run multiple pipelines with no recompilation as long as you stay under some specific resolution (probably the high res ones added in 0.3).



> This seems like an obvious reason but then I don't have the full picture. Admittedly a random suggestion -- would keeping h_p, w_p, h_max, and w_max as tensors help avoid the issue?

I am not sure if I followed your advice right but I tried:

```python
    def pe_selection_index_based_on_dim(self, h, w):
        # select subset of positional embedding based on H, W, where H, W is size of latent
        # PE will be viewed as 2d-grid, and H/p x W/p of the PE will be selected
        # because original input are in flattened format, we have to flatten this 2d grid as well.
        h_p, w_p = h // self.patch_size, w // self.patch_size
        original_pe_indexes = torch.arange(self.pos_embed.shape[1], device=self.pos_embed.device)
        h_max = torch.tensor(self.pos_embed_max_size, device=self.pos_embed.device).sqrt().floor().long()
        w_max = h_max  # Square grid assumption
        original_pe_indexes = original_pe_indexes.view(h_max, w_max)
        starth = (h_max // 2) - (h_p // 2)
        startw = (w_max // 2) - (w_p // 2)
        narrowed = torch.narrow(original_pe_indexes, 0, starth, h_p)
        narrowed = torch.narrow(narrowed, 1, startw, w_p)
        
        return narrowed.flatten()
```

which got me

```bash
torch._dynamo.exc.Unsupported: Data dependent operator
  Explanation: Operator `aten._local_scalar_dense.default` has a non-Tensor output whose value is dependent on the data of Tensor inputs.                                        
  Hint: Enable tracing of data-dependent output operators with `torch._dynamo.config.capture_scalar_outputs = True`                                                              
                                            
  Developer debug context: aten._local_scalar_dense.default  
```

and enabling `torch._dynamo.config.capture_scalar_outputs = True` got me

```bash
torch._dynamo.exc.UserError: Could not guard on data-dependent expression Eq(u0, -1) (unhinted: Eq(u0, -1)).  (Size-like symbols: none)                                          
                                                                                                                                                                                 
Caused by: original_pe_indexes = original_pe_indexes.view(h_max, w_max)  # diffusers/models/transformers/auraflow_transformer_2d.py:81 in pe_selection_index_based_on_dim (_prims
_common/__init__.py:930 in infer_size)  
```

I've tried a few different workarounds but they all still triggered the recompilation.

**Comment by sayakpaul** [comment]
> You will see that second pipeline call triggering the recompilation with

From https://github.com/pytorch/pytorch/issues/150702#issue-2973309427, I thought with `torch.compile(pipeline.transformer, fullgraph=True, dynamic=True)` it won't be an issue. But IIUC, this recompilation will trigger after certain high resolutions? 

> (probably the high res ones added in 0.3).

What is 0.3 here?

> I am not sure if I followed your advice right but I tried:

I was suggesting something like:

```py
    def pe_selection_index_based_on_dim(self, h, w):
        # select subset of positional embedding based on H, W, where H, W is size of latent
        # PE will be viewed as 2d-grid, and H/p x W/p of the PE will be selected
        # because original input are in flattened format, we have to flatten this 2d grid as well.
        patch_size = torch.tensor(self.config.patch_size)
        h, w = torch.tensor(h), torch.tensor(w)
        h_p, w_p = h // patch_size, w // patch_size
        original_pe_indexes = torch.arange(self.pos_embed.shape[1], device=self.pos_embed.device)
        h_max = torch.tensor(self.pos_embed_max_size, device=self.pos_embed.device).sqrt().floor().long()
        w_max = h_max  # Square grid assumption
        original_pe_indexes = original_pe_indexes.view(h_max, w_max)
        starth = (h_max // 2) - (h_p // 2)
        startw = (w_max // 2) - (w_p // 2)
        narrowed = torch.narrow(original_pe_indexes, 0, starth, h_p)
        narrowed = torch.narrow(narrowed, 1, startw, w_p)
        
        return narrowed.flatten()
```


> pip install git+https://github.com/AstraliteHeart/diffusers.git@6bd6b7c360af25cdbc7f42a07cc228137d24bc3c

Nice, would you like to upstream these in a PR to `diffusers`? We can help prioritize this as it affects the performance :) Cc: @DN6

Also just for the record, I don't think it's specifically tied to the GGUF checkpoint. I think (from the traces) it's an implementation issue in the modeling code.

**Comment by sayakpaul** [comment]
Thanks for the update. Then I am certainly out of options here. @StrongerXi do we have to consider rewriting the `view` op (the one deemed to be problematic)? 

Does a similar thing happen for Flux (has support for GGUF).

**Comment by AstraliteHeart** [comment]
Sent out a PR to `diffusers` that hopefully fixes this issue but would appreciate any feedback from `torch` folks on whether I am doing it right.

**Comment by AstraliteHeart** [comment]
With `torch.fx.experimental._config.use_duck_shape = False` and my fixes for [Rewrite AuraFlowPatchEmbed.pe_selection_index_based_on_dim to be torch.compile compatible huggingface/diffusers#11297](https://github.com/huggingface/diffusers/pull/11297) the original issue is fixed so unless there is something to be learned/fixed on torch side we can close this one.
