### ISSUE TITLE
I can't import PyTorch, libomp.dylib can't be loaded.

### ISSUE THREAD

**Issue by kaszperro** [pytorch/pytorch#20030]
## 🐛 Bug

I tried to install PyTorch, but I can't use it. It can't link dynamic library libomp.dylib

## To Reproduce

1. pipenv install torch torchvision
2. `from torch.utils.data import Dataset` 

```
Traceback (most recent call last):
  File "/Users/kaspersapala/Documents/Airly/new-pollution-forecast/Datasets/__init__.py", line 3, in <module>
    from torch.utils.data import Dataset
  File "/Users/kaspersapala/.local/share/virtualenvs/new-pollution-forecast-BSetKF9E/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/Users/kaspersapala/.local/share/virtualenvs/new-pollution-forecast-BSetKF9E/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/kaspersapala/.local/share/virtualenvs/new-pollution-forecast-BSetKF9E/lib/python3.7/site-packages/torch/lib/libshm.dylib
  Reason: image not found
```

## Expected behavior

Being able to use and import PyTorch

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Mac OS Mojave 
 - How you installed PyTorch (`conda`, `pip`, source): pipenv
 - Python version: 3.7.1

**Comment by kaszperro** [comment]
`brew install libomp` solves the problem.

**Comment by ezyang** [comment]
cc @JerryShih

**Comment by ezyang** [comment]
cc @pjh5 @kostmo

**Comment by JerryShih** [comment]
> `brew install libomp` solves the problem.

@ezyang 
How to add the libomp dependency in pytorch pip installation?

Will all pytorch dependent libraries be backed into wheel package?
If yes, I will add the libomp files like these code: https://github.com/pytorch/pytorch/blob/2356fac9a5205a2e11f1abf6105fdb3124246d41/setup.py#L738-L825

How about other dependent libraries? Are they all in third_party folder and built from source?

**Comment by ezyang** [comment]
pip doesn't know anything about brew, you can't ask it to brew install a package. Also, while this resolution "solves" the issue, I would love to better understand how this dependency came to be (in particular, why are we building binaries with a dependency on brew libraries? That sounds bad.)

In some cases where we can't assume end users have a library installed, we distribute the library with our binaries. However, I'm not sure that we should do this for libomp.dylib. cc @soumith

**Comment by soumith** [comment]
this is something that needs to be fixed. I can take a look at fixing binaries and re-uploading.
The problem is that our macos CI installs libomp over here: https://github.com/pytorch/pytorch/blob/0da0c4be48c675d61c39b4554131e1dbe9177cab/.circleci/verbatim-sources/header-section.yml#L294 , I think for CI / testing. But binary builds also pick it up and use it.

**Comment by pjh5** [comment]
I can remove this dependency for the binaries. I'll put out a PR soon

**Comment by dudongge** [comment]
brew install libomp solves the proble 
this solve my problem

**Comment by ruohoruotsi** [comment]
I agree with @ezyang that a pytorch installation via pip should not depend on brew. PyTorch is a dependency for my library and my users may or may-not have/care about brew. 

- So just to clarify, the solution was to remove the `brew install libomp` step && correctly package up the platform specific libraries of libomp (.dylib, .so, etc) ? Is that correct?

- If I'd like to grab the latest nightly with this fix...that'd be a `pip install torch_nightly -f blah.html` ?

**Comment by pjh5** [comment]
@ruohoruotsi all of that is correct

**Comment by jhorchler** [comment]
Just for reference: If using macports the issue can be worked around by creating a symlink  using `sudo ln -s /opt/local/lib/libomp/libomp.dylib` in `/usr/local/opt/libomp/lib/`.

**Comment by ruivapps** [comment]
> Just for reference: If using macports the issue can be worked around by creating a symlink using `sudo ln -s /opt/local/lib/libomp/libomp.dylib` in `/usr/local/opt/libomp/lib/`.

the issue should be fixed from PyTorch by looking libraries form system instead of only checking /usr/local/opt/

**Comment by gongenbo** [comment]
> `brew install libomp` solves the problem.

It work!

**Comment by adrienchaton** [comment]
when trying to upgrade pytorch from 1.0.1 to 1.1, I ran into the same issue and found this thread

the update on linux server worked fine but not on my macbook (OSX)

I tried brew install libomp but the brew formula could not be found, hence this did not fix the issue and I had to downgrade back to 1.0.1 on OSX to be able to import torch again

did anyone have the same issue regarding both the pip install of pytorch and the brew install of libomp ?

**Comment by alex-xnor** [comment]
@soumith 

> I can take a look at fixing binaries and re-uploading.

Is there still any plan to do this, or are new binary releases going to wait for the next PyTorch release?

**Comment by kaszperro** [comment]
> when trying to upgrade pytorch from 1.0.1 to 1.1, I ran into the same issue and found this thread
> 
> the update on linux server worked fine but not on my macbook (OSX)
> 
> I tried brew install libomp but the brew formula could not be found, hence this did not fix the issue and I had to downgrade back to 1.0.1 on OSX to be able to import torch again
> 
> did anyone have the same issue regarding both the pip install of pytorch and the brew install of libomp ?

You need to install brew first, go to [brew site](https://brew.sh) and follow install instructions.

**Comment by adrienchaton** [comment]
thanks for your reply, I had brew installed but it was not enough up to date
so I updated everything and now it works

note for other users, when I did brew install libomp, it went through but other applications did not work anymore (Spyder IDE) ; at this moment my OS was still 10.11 (Capitan) and I had to upgrade to 10.12 (Sierra) to be able to solve the problem

so from my experience, I would recommend upgrading to Sierra at least before installing pytorch 1.1 and libomp (I use pip and brew for all install)

**Comment by soumith** [comment]
uploaded new binaries that remove dependency on `libomp.dylib`

**Comment by sukuya** [comment]
Now I get ```-unsupported option '-fopenmp' ``` error.

**Comment by alex-xnor** [comment]
@sukuya That sounds like a different problem, since it sounds like you're trying to compile PyTorch yourself, but this issue concerned a problem with the pre-compiled binaries.

**Comment by torrmal** [comment]
this issue still present in torch 1.1.0.post2, do you know when the fix will be available on stable release?

**Comment by alex-xnor** [comment]
@torrmal How are you making sure that you are using 1.1.0.post2? In my testing the changes introduced by 1.1.0.post2 fixed this problem completely, so I wonder whether you have a 1.1.0 non-post2 lying around somewhere that's getting picked up inadvertently.

**Comment by sukuya** [comment]
> @sukuya That sounds like a different problem, since it sounds like you're trying to compile PyTorch yourself, but this issue concerned a problem with the pre-compiled binaries.

@alex-xnor  I was compiling a c++ program which used prebuilt ```libtorch``` and I get those errors.

**Comment by pjh5** [comment]
@sukuya  can you make a new issue with more details on your problem? In particular, can you include the cmake/makefile that you are running and the compiler command that you are using?

**Comment by GPPyeye** [comment]
> `brew install libomp` solves the problem.

Thx bro I've solved my problem

**Comment by leedrake5** [comment]
Does anyone have a suggestion for when brew install libomp doesn't work? I've reinstalled, relinked, but to no avail.

**Comment by matthewchuang97987536** [comment]
put this in terminal,hope it works. It took me 2hrs to fix this and I hope you can fix it faster, jeeez...

install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_cvxcore.cpython-37m-darwin.so

**Comment by PearlW1** [comment]
> `brew install libomp` solves the problem.

Don't run  `brew install libomp`, it destroyed my environment, then i create a new env, install other configuration, so sad.

**Comment by callmejliu** [comment]
I also have the same issue when Launching Web UI with arguments:... Anyone have the same issue being solved? 
I tried v1.5, 2.0 and 2.1 also have the .yaml file installed in the same folder. 

Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --skip-torch-cuda-test --no-half-vae --use-cpu interrogate
Traceback (most recent call last):
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/launch.py", line 356, in <module>
    start()
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/launch.py", line 347, in start
    import webui
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/modules/paths.py", line 5, in <module>
    import modules.safe
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/modules/safe.py", line 9, in <module>
    import torch
  File "/Users/jeffreyhomeimac/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Users/jeffreyhomeimac/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libomp.dylib
  Referenced from: /Users/jeffreyhomeimac/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  Reason: no suitable image found.  Did find:
	/Users/jeffreyhomeimac/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Users/jeffreyhomeimac/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
JEFFREYs-MBP-2:stable-diffusion-webui jeffreyhomeimac$

**Comment by RobertKoval** [comment]
For C++ project, after installing libomp using `brew install libomp` I still got an error:

```
dyld[12444]: Library not loaded: @rpath/libomp.dylib
  Referenced from: <E4E2FFCA-031E-3974-A7B0-45408D7F4956> /Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libtorch_cpu.dylib
  Reason: tried: '/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/Users/runner/work/_temp/anaconda/envs/wheel_py38/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/anaconda/envs/wheel_py38/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```

I manage to fix it by adding additional path to libtorch_cpu.dylib using this command:
`install_name_tool -add_rpath /opt/homebrew/opt/libomp/lib <YOUR_PATH_TO_THE_DOWNLOADED_LIB>libtorch/lib/libtorch_cpu.dylib`

**Comment by Iainmon** [comment]
> For C++ project, after installing libomp using `brew install libomp` I still got an error:
> 
> ```
> dyld[12444]: Library not loaded: @rpath/libomp.dylib
>   Referenced from: <E4E2FFCA-031E-3974-A7B0-45408D7F4956> /Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libtorch_cpu.dylib
>   Reason: tried: '/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/Users/runner/work/_temp/anaconda/envs/wheel_py38/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/_temp/anaconda/envs/wheel_py38/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/pytorch/pytorch/pytorch/build/lib/libomp.dylib' (no such file), '/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/rkoval/Dev/Piu_Piu_vision_Cpp/lib/libtorch/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
> ```
> 
> I manage to fix it by adding additional path to libtorch_cpu.dylib using this command: `install_name_tool -add_rpath /opt/homebrew/opt/libomp/lib <YOUR_PATH_TO_THE_DOWNLOADED_LIB>libtorch/lib/libtorch_cpu.dylib`

This worked for me. Thank you!
