### ISSUE TITLE
High CPU usage by torch.Tensor

### ISSUE THREAD

**Issue by movchan74** [pytorch/pytorch#22866]
## 🐛 Bug

Pytorch >= 1.0.1 uses a lot of CPU cores for making tensor from numpy array if numpy array was processed by np.transpose. The bug is not appears on pytorch 1.0.0. Nightly build has the same bug.

## To Reproduce

1. Install Pytorch >= 1.0.1
2. Run following code 
```
import torch 
import numpy as np
def preprocessing(batch, transpose=True):
    if transpose:
        batch = batch.transpose(0, 3, 1, 2)
    return batch

for i in range(1000):
    a = np.random.rand(8, 224, 224, 3)
    a = preprocessing(a, transpose=True)
    a = a.astype(np.float32)
    a = torch.Tensor(a)
    a = a.cuda()
```
3. Open htop and enjoy 2500% CPU utilization by the process that is running the code.

This code (without np.transpose) works just fine - not more than 100% CPU utilization
```
for i in range(1000):
    a = np.random.rand(8, 224, 224, 3).astype(np.float32)
    a = preprocessing(a, transpose=False)
    a = a.astype(np.float32)
    a = torch.Tensor(a)
    a = a.cuda()
```

Same abnormal behavior with torch.permute if you call it before tensor.cuda().
```
for i in range(1000):
    a = np.random.rand(8, 224, 224, 3).astype(np.float32)
    a = preprocessing(a, transpose=False)
    a = a.astype(np.float32)
    a = torch.Tensor(a)
    a = a.permute((0, 3, 1, 2))
    a = a.cuda()
```

torch.permute after tensor.cuda() works just fine  - not more than 100% CPU utilization
```
for i in range(1000):
    a = np.random.rand(8, 224, 224, 3).astype(np.float32)
    a = preprocessing(a, transpose=False)
    a = a.astype(np.float32)
    a = torch.Tensor(a)
    a = a.cuda()
    a = a.permute((0, 3, 1, 2))
```

## Expected behavior

I'm expecting utilization not more than 100%. 

## Environment

```
PyTorch version: 1.0.1
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN RTX

Nvidia driver version: 418.39
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.15.1
[pip3] torch==1.0.1
[pip3] torchvision==0.2.1
[conda] Could not collect
```

## Additional context

I've tried the same code on other server. On this server CPU usage is not increased so drastically but still shows 200% utilization with np.transpose and not more than 100% without.

**Comment by SsnL** [comment]
`torch.Tensor` is the legacy constructor. Use `torch.as_tensor` for copy-free construction from a NumPy array.

**Comment by colesbury** [comment]
@SsnL, I think the issue is the `cuda()` call. `torch.Tensor(a)` isn't copying here. Agree that `torch.as_tensor` is the preferred style, but I don't think it affects performance.

**Comment by SsnL** [comment]
@colesbury Thanks, you are right :).

**Comment by colesbury** [comment]
@movchan74 using more CPU isn't a bug (it's a feature). You can control the CPU parallelization with either `OMP_NUM_THREADS=1` environment variable or `torch.set_num_threads()`.

Is there a slow down? On multi-socket systems you generally want to limit the number of threads to a single socket. Try `OMP_NUM_THREADS=12`.

**Comment by colesbury** [comment]
For future reference, this behavior is independent of using NumPy. It has to do with the fact that a CPU->CUDA copy of a non-contiguous Tensor requires a temporary contiguous copy. This temporary copy (non-contiguous->contiguous) is now parallelized if the Tensor is large enough. It wasn't parallelized in 1.0.0. You can see this behavior with:

```python
import torch
x = torch.randn(8, 224, 224, 3).permute(0, 3, 1, 2)
while True:
   x.cuda()
```

**Comment by vraivon** [comment]
> torch.set_num_threads()

is there some way to set number of threads while using libtorch？

**Comment by colesbury** [comment]
@vraivon use `torch::set_num_threads`

**Comment by vraivon** [comment]
@colesbury but it will get the error: ‘set_num_threads’: is not a member of 'torch'

**Comment by colesbury** [comment]
@vraivon, oh in PyTorch 1.1.0 you have to use `at::set_num_threads` instead. (In PyTorch 1.2 it will be available as `torch::set_num_threads`)

**Comment by vraivon** [comment]
@colesbury in pytorch it's ok, but how to set this in c++ while using libtorch? I have tried to use omp_set_num_threads(), but there’s no effect.

**Comment by AravindChandradoss** [comment]
@colesbury @vraivon I also have similar [issue](https://github.com/pytorch/pytorch/issues/24244) Did you find any way to fix this? I have full CPU usage although training is on GPU. 

I tried 
`set_num_threads()` and
`OMP_NUM_THREADS=1`

 Still CPU usage is full on all 8 cores.

Thanks

**Comment by TomorrowIsAnOtherDay** [comment]
@AravindChandradoss  Try : torch.set_num_threads(1)
```python
import torch
torch.set_num_threads(1)
x = torch.randn(8, 224, 224, 3).permute(0, 3, 1, 2)
while True:
   x.cuda()
```

**Comment by TomorrowIsAnOtherDay** [comment]
I don't think the current setting is sensible for running multiple experiments at a machine with 8 GPUs.
I want to start 8 experiments at the same time but I find that the first experiment has already used all the CPUs.
While I was writing the code in tensorflow with the GPU environment, I did not have any issues about CPU usage.

**Comment by TomorrowIsAnOtherDay** [comment]
Another problem is that when I had 8 experiments started, it's hard for me to edit the code as these experiments had occupied all the CPU resources. 
Why tensorflow does not have this issue?

**Comment by lastlap** [comment]
I had a similar problem of high cpu usage. [This](https://discuss.pytorch.org/t/cpu-usage-extremely-high/52172/5. ) solved it for me. Set pin_memory=False in DataLoader.

**Comment by SsnL** [comment]
@lastlap the memory pinning bug was fixed in 1.3 btw.

**Comment by lastlap** [comment]
@SsnL Oh ok I'm using 1.1.0

**Comment by zhaoxuyan** [comment]
> @AravindChandradoss
> 
> Try : torch.set_num_threads(1)
> 
> ```python
> import torch
> torch.set_num_threads(1)
> x = torch.randn(8, 224, 224, 3).permute(0, 3, 1, 2)
> while True:
>    x.cuda()
> ```

解决了！非常感谢

**Comment by zhihaocheng** [comment]
Still the same problem, and I do not use dataloader. When I set threads to 1, the cpu usage decrease to 100%. But when I want to use multi-threads, the usage of cpu again out of control.
