### ISSUE TITLE
Can't compile with gcc 6.4 and cuda 9

### ISSUE THREAD

**Issue by svenstaro** [pytorch/pytorch#2972]
When compiling pytorch 0.2 with gcc 6.4 and cuda 9 on Arch Linux I get these issues: [log.txt](https://github.com/pytorch/pytorch/files/1356097/log.txt)

The error is:

```
/build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/THC/generic/THCTensorMathPairwise.cu(66): error: more than one operator "!=" matches these operands:
            function "operator!=(const __half &, const __half &)"
            function "operator!=(half, half)"
            operand types are: half != half
```

I'm the cuda and pytorch maintainer in Arch and this is currently blocking a rebuild so help is highly appreciated.

**Comment by ngimel** [comment]
Defining __CUDA_NO_HALF_OPERATORS__ for cuda files should fix that, but it is already defined in CMakeLists https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/CMakeLists.txt#L46, so I don't understand why you are seeing this. Try ```export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"``` before building.

**Comment by svenstaro** [comment]
I compile with this line:

```
  CC=gcc-6 \
  CXX=g++-6 \
  CFLAGS="${CFLAGS/-fno-plt/}" \
  CXXFLAGS="${CFLAGS/-fno-plt/}" \
  WITH_CUDA=1 \
  CUDA_HOME=/opt/cuda \
  WITH_CUDNN=1 \
  CUDNN_LIB_DIR=/opt/cuda/lib64 \
  CUDNN_INCLUDE_DIR=/opt/cuda/include \
  TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__" \
  python setup.py build --verbose
```

and now I get this result:

```
Grabbing  src/nccl.h                          > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/include/nccl.h
Compiling src/libwrap.cu                      > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/libwrap.o
Compiling src/core.cu                         > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/core.o
Compiling src/all_gather.cu                   > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/all_gather.o
Compiling src/all_reduce.cu                   > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/all_reduce.o
Compiling src/broadcast.cu                    > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/broadcast.o
Compiling src/reduce.cu                       > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/reduce.o
Compiling src/reduce_scatter.cu               > /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/reduce_scatter.o
src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

6 errors detected in the compilation of "/tmp/tmpxft_000048d4_00000000-11_all_gather.compute_61.cpp1.ii".
make[3]: *** [Makefile:123: /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/all_gather.o] Error 1
make[3]: *** Waiting for unfinished jobs....
src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

6 errors detected in the compilation of "/tmp/tmpxft_00004908_00000000-11_broadcast.compute_61.cpp1.ii".
make[3]: *** [Makefile:123: /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/broadcast.o] Error 1
6 errors detected in the compilation of "/tmp/tmpxft_000048ee_00000000-11_all_reduce.compute_61.cpp1.ii".
make[3]: *** [Makefile:123: /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/all_reduce.o] Error 1
6 errors detected in the compilation of "/tmp/tmpxft_00004923_00000000-11_reduce.compute_61.cpp1.ii".
make[3]: *** [Makefile:123: /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/reduce.o] Error 1
6 errors detected in the compilation of "/tmp/tmpxft_00004935_00000000-11_reduce_scatter.compute_61.cpp1.ii".
make[3]: *** [Makefile:123: /build/python-pytorch/src/pytorch-0.2.0-py2-cuda/torch/lib/build/nccl/obj/reduce_scatter.o] Error 1
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
make[2]: *** [CMakeFiles/nccl.dir/build.make:61: lib/libnccl.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/nccl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by ngimel** [comment]
Until nccl subtree in pytorch is updated, you can't compile nccl from source, you should be installing precompiled nccl packages http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/. Don't know how it would work with arch linux, though.

**Comment by soumith** [comment]
nccl subtree is now updated in pytorch master.

**Comment by svenstaro** [comment]
Alright, so that works now but the bug is still valid as the first error occurs if `CUDA_NO_HALF_OPERATORS` is not manually set.

**Comment by soumith** [comment]
hmm okay we'll investigate further. Maybe with the FindCUDA.cmake that we have, CUDA 9.0 does not get reported correctly and maybe this logic is not executing:

https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/CMakeLists.txt#L45-L47

**Comment by icyblade** [comment]
The [latest](https://github.com/pytorch/pytorch/tree/2675ff73fd7611c30cff666554be41555e68ccc2) 2675ff73fd7611c30cff666554be41555e68ccc2 pytorch survives the compilation.
However, there's a `torch/lib/libATen.so.1: undefined symbol: THNN_CudaTanh_updateGradInput` error raised when `import torch`.

**Comment by ngimel** [comment]
Looks like this is https://github.com/pytorch/pytorch/pull/3096 the breaking PR. I'm facing the same issue.

**Comment by soumith** [comment]
this is likely fixes with
python setup.py clean

**Comment by ngimel** [comment]
My bad. I was sure I ran clean, but apparently I did not.

**Comment by ezyang** [comment]
I also got the same issue, and a clean fixed it (rm'ing `torch/lib/build` was not enough.)

**Comment by powderluv** [comment]
Ran into the same issue with top of master using Cuda9/Cudnn7. 
I was able to fix it with TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__" ./install.sh

**Comment by svenstaro** [comment]
In case it helps anybody, here is the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-pytorch) I use to build the official package for Arch Linux. It should be quite straightforward to read.

**Comment by soumith** [comment]
@ngimel should we add `__CUDA_NO_HALF_OPERATORS__` by default?

**Comment by ngimel** [comment]
Yes.

**Comment by expelliarms** [comment]
Same problem with CUDA 8. I am trying to build pytorch v0.1.12. None of the above mentioned seems to solve the issue. Please help
