### ISSUE TITLE
DistributedDataParallel don't work at nightly build(1.6.0.dev20200408+cu101)

### ISSUE THREAD

**Issue by meixitu** [pytorch/pytorch#36268]
## 🐛 Bug
I have single Machine, and 4 GPUS.

nn.parallel.DistributedDataParallel can't run at nightly build

This code can run correctly with Pytorch 1.4

Traceback (most recent call last):
  File "lstm_toy.py", line 72, in <module>
    model = nn.parallel.DistributedDataParallel(model,find_unused_parameters=True,check_reduction=True)        
  File "/usr/local/anaconda3/envs/torch1.5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 305, in __init__
    self._ddp_init_helper()
  File "/usr/local/anaconda3/envs/torch1.5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 382, in _ddp_init_helper
    expect_sparse_gradient)
RuntimeError: Model replicas must have an equal number of parameters.

## To Reproduce

Run below code in Command line:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import time
import os
import sys
import traceback

os.environ['CUDA_VISIBLE_DEVICES'] ='0,1,2,3'
import faulthandler
faulthandler.enable()

from gpu_mem_track import MemTracker
import inspect

frame = inspect.currentframe()
gpu_tracker = MemTracker(frame)


torch.backends.cudnn.benchmark = True

BATCH_SIZE = 4
INPUT_DIM = 2048
OUTPUT_DIM = 5000
EPOCHS = 10000
HIDDEN_DIM = 2048
N_LAYERS=5
SEQ_LEN = 2000

class Net(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, hidden_layers):
        super(Net, self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.hidden_layers = hidden_layers

        self.lstm = nn.LSTM(input_dim, hidden_dim, hidden_layers,batch_first=True)
        self.h2o = nn.Linear(hidden_dim, output_dim)

    def forward(self, x,y):
        self.lstm.flatten_parameters()
        h_t, _ = self.lstm(x)
        output = self.h2o(h_t)
        loss = F.mse_loss(output, y)
        return loss

X_data = torch.randn((BATCH_SIZE,SEQ_LEN, INPUT_DIM)).cuda()
Y_data = torch.rand((BATCH_SIZE,SEQ_LEN, OUTPUT_DIM)).cuda()

model = Net(INPUT_DIM, HIDDEN_DIM, OUTPUT_DIM, N_LAYERS)
if 0:
    model = nn.DataParallel(model)
    model.cuda()
else:
    torch.distributed.init_process_group(backend='nccl',init_method='tcp://localhost:'+str(np.random.randint(100,60000)),rank=0,world_size=1)
    model.cuda()
    model = nn.parallel.DistributedDataParallel(model,find_unused_parameters=True,check_reduction=True)        
```

## Environment
PyTorch version: 1.6.0.dev20200408+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 435.21
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.13.3
[conda] torch                     1.6.0.dev20200408+cu101          pypi_0    pypi
[conda] torchvision               0.6.0.dev20200408+cu101          pypi_0    pypi
[conda] warprnnt-pytorch          0.1                      pypi_0    pypi

## Additional context

Thanks
Meixitu

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by zhangguanheng66** [comment]
Add hight priority label because of the nightly build. Maybe not be a bug on our side.

**Comment by ezyang** [comment]
We should check if 1.5 is affected by this too

**Comment by mrshenli** [comment]
cc @osalpekar

**Comment by meixitu** [comment]
> We should check if 1.5 is affected by this too

Actually, I tried an 1.5 nightly build, I forget this version. But DistributedDataParallel does not work

**Comment by seemethere** [comment]
@meixitu Can you try to reproduce with the latest `v1.5.0-rc3`?

You can install this with `conda` using:
```
conda install -y -c pytorch-test pytorch cudatoolkit=10.1
```

Or with `pip` using:
```
pip install -f https://download.pytorch.org/whl/test/test.html torch==1.5.0+cu101
```

**Comment by meixitu** [comment]
@seemethere 
    I got the same error.
![image](https://user-images.githubusercontent.com/32910309/79145879-39f21200-7d76-11ea-82e6-a3d8ed8183ee.png)

![image](https://user-images.githubusercontent.com/32910309/79145991-7291eb80-7d76-11ea-9752-342815c59f99.png)


Thanks
Meixitu

**Comment by mrshenli** [comment]
@meixitu 

Thanks for reporting. #36523 should fix the crash for this use case. But I want to mention that this is not a recommended use case for DDP. We plan to retire this single-process-multiple-device (SPMD) DDP mode in future releases, and suggest to use one DDP instance per device. 

1. This SPMD mode is known to be slower then having one DDP instance per device due to GIL contention across threads in `parallel_apply` and additional overhead introduced by scatter/gather in every forward. 
2. This adds a lot of code complexity in DDP.
3. Having two different modes in DDP could be confusing for users and also requires additional ctor arguments. 

BTW, `check_reduction` flag is also deprecated. 

Is there any reason for your application to use single-process DDP?

**Comment by meixitu** [comment]
@mrshenli ,
    Thanks for your fix.
    **I only have one machine, which have several CPUS and GPUS.**
    I have no idea about how to use one DDP instance per device, I just searched how to use DDP by website.
    Do you have recommended example code for my setting(one DDP instance per device due to GIL )? I am glad to try it.
Thanks
Meixitu

**Comment by mrshenli** [comment]
Yes, please check out this [starter example](https://pytorch.org/docs/master/notes/ddp.html#example). You can spawn multiple processes either using command line or using multi-processing.

**Comment by mrshenli** [comment]
#36939 reminds me that it is not that we don't have a test to cover this error, it seems that we didn't launch those tests (e.g., `test_gloo_backend_1gpu_module_device_ids_torch_device_list`) due to we don't have such test envs. 

@gchanan @ezyang I recall that we used to have a 4-GPU CI env. Do we still have that today?

**Comment by mrshenli** [comment]
@ezyang pointed out that `pytorch_linux_xenial_cuda10_1_cudnn7_py3_multigpu_test` has 4 GPUs.

**Comment by mrshenli** [comment]
@rohan-varma is investigating why our multi-gpu test didn't expose this error earlier.

**Comment by mrshenli** [comment]
Closed by #36523

**Comment by leimao** [comment]
@mrshenli 
I tried the PyTorch 1.5.0 which was just formally released a few days ago. The official tutorial ["GETTING STARTED WITH DISTRIBUTED DATA PARALLEL"](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) (looks like you are the author) failed using PyTorch 1.5.0 but worked in PyTorch 1.4.0. Was your patch included in the PyTorch 1.5.0?

**Comment by gchanan** [comment]
@leimao this did not make the 1.5 release; that's not clear above.

@mrshenli can you confirm that the tutorial doesn't work in 1.5?

**Comment by mrshenli** [comment]
@leimao Thanks for reporting!

@gchanan I confirm that the DDP tutorial is broken with v1.5.

The fix is simple, just replace 

```python
if __name__ == "__main__":
    run_demo(demo_basic, 2)
    run_demo(demo_checkpoint, 2)
```

with 

```python
if __name__ == "__main__":
    run_demo(demo_basic, 8)
    run_demo(demo_checkpoint, 8)
```

Two more comments:

1. This tutorial works with master due to #36503
2. Let me take this chance to revamp that DDP tutorial a bit.

**Comment by mrshenli** [comment]
Updated version:

1. tutorial: https://github.com/pytorch/tutorials/pull/973
2. example: https://github.com/pytorch/examples/pull/763

**Comment by adrianosantospb** [comment]
I have got the same issue on my code. To solve it, I have used the following code (downgrade the version): 

`pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by mrshenli** [comment]
Hey @adrianosantospb which version were you using? This should have been fixed on master/nightly. I just tried the sample code above and it works for me.

But, It's true that the fix was not included in 1.5.0. 

BTW, do you mind share some more details of your use case? What is the reason for using single-process multi-device (SPMD) mode of DDP? We are considering retiring this mode in future releases. If applications need SPMD, `DataParallel` is the way to go.

**Comment by adrianosantospb** [comment]
Hi, @mrsalehi . Using SPMD we have got improved multigpu speed substantially instead of DataParallel mode.

**Comment by mrshenli** [comment]
Hi @adrianosantospb, the recommended mode of DDP is Multi-Process-Single-Device (i.e., create multiple processes and let each process to exclusively work on one device), it should be even faster than SPMD mode of DDP. [This](https://pytorch.org/docs/master/notes/ddp.html#example) is an example.

**Comment by adrianosantospb** [comment]
Great, @mrsalehi . I will try it.

**Comment by adrianosantospb** [comment]
Hi, @mrsalehi . Just to notify you that I have done the test using:

`model = torch.nn.parallel.DistributedDataParallel(model, find_unused_parameters=True)`

The DDP is faster then DataParallel. But the Pytorch V 1.5.0 problem remain.

**Comment by mrshenli** [comment]
Hi @adrianosantospb 

Yes, the fix (#36503) didn't get into v1.5.0, as that was too close to the release date. We managed to land it soon after the v1.5.0 release and is now available on master.

**Comment by stephenroller** [comment]
Sorry @mrshenli, just wanted to say that SPMG is really useful in ranking ranking applications, where we frequently use the other items in the batch as negative samples. SPMG can help you pump up the negative candidates significantly higher than could fit on a single GPU, and this sometimes has very strong implications on performance. So I'm sorta sad to see this case go. I know @williamFalcon also utilizes this trick.

Happy to talk on WorkChat about this more

**Comment by mrshenli** [comment]
Hey @stephenroller 

Thanks for the the comment. I see. If SPMG is used in many existing applications, then we probably should not delete it just yet. It is currently fixed on master and we can keep the feature there with the warning message in the next few releases. cc @ngimel @zhaojuanmao 

Happy to chat more on WorkChat too. :) One question I had is why do we need to increase the number of negative candidates in each process? What if they are scattered across multiple processes?

**Comment by williamFalcon** [comment]
agree with @stephenroller - this mode in lightning is called ddp2. this is hugely useful in NLP and self superviser learning research where larger number of negative samples are critical.

**Comment by jinfagang** [comment]
So how does this fix?

```
RuntimeError: Model replicas must have an equal number of parameters.

```
