### ISSUE TITLE
torch.cat fails with torch.jit.script and torch.cuda.amp.autocast

### ISSUE THREAD

**Issue by johannesschaeufele** [pytorch/pytorch#38958]
## 🐛 Bug

Using `torch.cat` inside a Module with `torch.jit.script` and `torch.cuda.amp.autocast` leads to an assertion failure. The same seems to hold for `torch.stack` (and potentially even more functions).

## To Reproduce

1. Run the following python program:
```python
import torch
import torch.nn as nn
import torch.cuda.amp as amp


class Model(nn.Module):
    def forward(self):
        a = torch.randn(1)
        b = torch.randn(1)
        c = torch.cat((a, b), 0)

        return c


print(torch.__version__)

model = Model()
model_jit_script = torch.jit.script(model)

with amp.autocast(False):
    model()
    model_jit_script()

with amp.autocast(True):
    model()
    print("Relevant variant:", flush=True)
    model_jit_script()
```
2. Observe (sample) output:
```
1.6.0.dev20200523
Relevant variant:
Traceback (most recent call last):
  File "mcve.py", line 27, in <module>
    model_jit_script()
  File "/home/install/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "mcve.py", line 10, in forward
        a = torch.randn(1)
        b = torch.randn(1)
        c = torch.cat((a, b), 0)
            ~~~~~~~~~ <--- HERE

        return c
RuntimeError: false INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1590217668866/work/aten/src/ATen/core/boxing/KernelFunction_impl.h":40, please report a bug to PyTorch. Tried to call KernelFunction::callBoxed() on a KernelFunction that can only be called with KernelFunction::call().
```

## Expected behavior

No assertion is thrown and all variants behave the same.

## Environment

```
PyTorch version: 1.6.0.dev20200523
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Arch Linux
GCC version: (GCC) 10.1.0
CMake version: version 3.17.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.82
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0.dev20200523
[pip] torchvision==0.7.0.dev20200523
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.0                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.6.0.dev20200523 py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch-nightly
[conda] tensorflow                2.1.0           mkl_py37h80a91df_0  
[conda] tensorflow-base           2.1.0           mkl_py37h6d63fb7_0  
[conda] torchvision               0.7.0.dev20200523      py37_cu102    pytorch-nightly
```

cc @suo @mcarilli

**Comment by jamesr66a** [comment]
This seems primarily to be a bad interaction between AMP and the dispatcher. @mcarilli @ezyang @smessmer can you guys take a look?

**Comment by ezyang** [comment]
TensorList strikes again...

**Comment by ezyang** [comment]
At a wild guess: this patch should fix it:

```
diff --git a/aten/src/ATen/autocast_mode.cpp b/aten/src/ATen/autocast_mode.cpp
index 7d85211e9c..7809b7d323 100644
--- a/aten/src/ATen/autocast_mode.cpp
+++ b/aten/src/ATen/autocast_mode.cpp
@@ -487,9 +487,9 @@ TORCH_LIBRARY_IMPL(aten, Autocast, m) {
   KERNEL_UNBOXED_ONLY(ADD_NS(tensordot), "tensordot", Tensor (const Tensor &, const Tensor &, IntArrayRef, IntArrayRef), promote)
   KERNEL_UNBOXED_ONLY(ADD_NS(dot), "dot", Tensor (const Tensor &, const Tensor &), promote)
   KERNEL(ADD_NS(equal), "equal", bool (const Tensor &, const Tensor &), promote)
-  KERNEL_UNBOXED_ONLY(ADD_NS(cat), "cat", Tensor (TensorList, int64_t), promote)
-  KERNEL_UNBOXED_ONLY(ADD_NS(cat), "cat.names", Tensor (TensorList, Dimname), promote)
-  KERNEL_UNBOXED_ONLY(ADD_NS(_cat), "_cat", Tensor (TensorList, int64_t), promote)
+  KERNEL(ADD_NS(cat), "cat", Tensor (TensorList, int64_t), promote)
+  KERNEL(ADD_NS(cat), "cat.names", Tensor (TensorList, Dimname), promote)
+  KERNEL(ADD_NS(_cat), "_cat", Tensor (TensorList, int64_t), promote)
   KERNEL_UNBOXED_ONLY(ADD_NS(stack), "stack", Tensor (TensorList, int64_t), promote)
 
   m.impl_UNBOXED("binary_cross_entropy", &at::autocast::binary_cross_entropy_banned);
```

@smessmer not sure if we should just rush "get rid of unboxed only" or start adding some checks to reject incorrect invocations of unboxed only.

**Comment by ezyang** [comment]
Diff is not quite right but I have a fix. PR coming soon.

**Comment by johannesschaeufele** [comment]
The same should probably also be done for `torch.stack` as it seems to suffer from the same issue.

**Comment by mcarilli** [comment]
@johannesschaeufele The errors you see are caused by a (fixable) implementation detail of how autocast registers its op wrappers.  However, autocast interaction with jit scripting is very much WIP.

If you script a module, then run the module under autocast, you may get lucky.  Ops untouched by jit should still receive autocasting according to the autocast cast lists (e.g. likely gemms and convs, because afaik they aren't fused).  However, running under autocast remains numerically dangerous, because for other ops, jit may create fusion(s) that should output fp32 (e.g. if it fuses `exp` as an epilogue), but the fusions are new, so autocast won't recognize or cast for them.  The numerical danger is unrelated and additional to the failure you observe.

We're still thinking about the right way autocast and scripting should interact.  For example, autocast could be enabled at scripting time (eg around, or within portions of the model, when `model_jit_script = torch.jit.script(model)` is called), and the scripting logic made aware whether it's in an autocast context or not, so it includes (and potentially fuses) the right casts in fused ops.  This is a substantial effort, and presently master doesn't have this capability.

Best recommendation right now is, don't run a scripted model under autocast.  If you must use autocast and jit together, try tracing instead.  Run the model under autocast at trace time.  The tracing will include the eager casting decisions autocast makes, and casts will be baked into the resulting jitted module.

After tracing, because the autocast casts are already baked in, you don't need to run the model under autocast in the training loop.  In fact if you do, you might see more of the original failures, at least until the offending implementation detail is fixed.
