### ISSUE TITLE
can't load pytorch forum 

### ISSUE THREAD

**Issue by ryh95** [pytorch/pytorch#3987]
I want to visit discuss.pytorch.org, but most of the times I got **Cannot load app**

I can use google normally, I don't know how to contact with the discuss administrator.

Hope guys that encounter same problem can help me.

Thanks!

**Comment by mbabatunde** [comment]
Can you give some further information on the error you're getting?
Browser info, OS info, network, etc?
Can you post a screenshot of what your getting?

I'm currently not facing any issues on macOS 10.13 with Safari, Chrome, and Firefox

**Comment by ryh95** [comment]
on **Ubuntu 16.04** with **chrome 61.0.3163.100**
it looks like this

![2017-12-03 21-13-34](https://user-images.githubusercontent.com/8979086/33525650-01dc517c-d86f-11e7-88a7-0cadc09bac9d.png)

and with **firefox 57.0** got this
![2017-12-03 21-18-21](https://user-images.githubusercontent.com/8979086/33525694-cfecb2be-d86f-11e7-9f29-4cd23c889575.png)

I can surf the internet normally using google so it's weird to me

**Comment by musicpiece** [comment]
Seems like you have this extension called Mozilla, and I think that's why the forum is banned.

**Comment by ryh95** [comment]
umm...
the maker of the firefox is Mozilla

**Comment by zou3519** [comment]
Could you try the following (in a terminal):
`ping discuss.pytorch.org`
`ping google.com`
and report back what you get?

**Comment by ryh95** [comment]
Hi @zou3519 
thanks for your suggestions 
I tried to ping google 
but failed 
then I noticed that in order to use google I used ShadowsocksR and SwitchOmiga on my chrome
I add *.pytorch.org to my SwitchOmiga 
then the pytorch forum is ok
surfing the net in China is troublesome
thank you all guys, the problem is solved!

**Comment by Naruto-Sasuke** [comment]
Why not try lantern...

**Comment by juditacs** [comment]
I am experiencing the same issue on two different Linux notebooks (Arch and Manjaro) and several different locations in Hungary. It only happens in Firefox, Chromium loads the website just fine.

**Comment by ixaxaar** [comment]
This problem persists.
A `Ctrl-Shift-F5`, should do the trick for firefox.
https://github.com/mdn/sw-test/issues/24#issuecomment-342773963
