### ISSUE TITLE
Unable to build cuda extension with pytorch 1.5

### ISSUE THREAD

**Issue by lawpdas** [pytorch/pytorch#40663]
Hi, I tried to build an extension [correlation layer](https://github.com/NVIDIA/flownet2-pytorch/tree/master/networks/correlation_package). This extension can be built with pytorch1.4. However, I cannot build it with pytorch1.5 and nightly.

The error message:
```
...
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'build_ext': BuildExtension
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/space/Public/anaconda3/envs/nightly/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

```

cc @malfet @yf225 @glaringlee

**Comment by 522730312** [comment]
Did you set -std=c++14 in setup.py?

**Comment by lawpdas** [comment]
I have changed it from c++11 to c++14. It does not work.

**Comment by glaringlee** [comment]
@lawpdas
Do you have ninja installed?

**Comment by lawpdas** [comment]
@glaringlee Yes, ninja 1.9.0 has been installed in my conda environment.

**Comment by nnuk** [comment]
Stuck with same error kindly help. PyTorch 1.5.

**Comment by glaringlee** [comment]
@lawpdas @nnuk 
I tried with the latest pytorch code in master branch with ubuntu16.02+gcc7+cuda9.2+cudnn7, it works fine for me.
Can you guys try pytorch 1.5.1 or just clone the code from master? 
We do have some libs issues in pytorch 1.5 though I am not sure whether that is related.

**Comment by nnuk** [comment]
@glaringlee  Actually I have PyTorch 1.5.1 and I am working with VS Code , Windows 10.

**Comment by glaringlee** [comment]
Can you guys post your cuda version, complier and version, and related env parameters?

@nnuk can you try latest master brunch?

There is a similar error which is solved by upgrading cuda version.
https://github.com/pytorch/vision/issues/1893

**Comment by nnuk** [comment]
Cuda -> 10.1
cudnn -> 7.0
PyTorch -> 1.5.1
Visual Studio Code -> 1.46.1
Python 3.7
OS Windows 10.

**Comment by glaringlee** [comment]
@nnuk can you try pytorch in master brunch?
@peterjc123 any thoughts on this? I saw a similar issue pytorch/vision#1893 and solved by upgrade cuda 10.1 to newer version.

**Comment by lawpdas** [comment]
@glaringlee I built it with pytorch1.5.1 and nightly. Both them are installed by `conda install'.
cuda10.1
python3.7
ubuntu18.04
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

I also tried to clone the latest pytorch from master, but I got another error when I built it : (

**Comment by malfet** [comment]
@lawpdas can you please share a full build log (including output from configure)?

**Comment by lawpdas** [comment]
I cannot build pytorch source code with cuda10.2 #40909, but I can build pytorch with cuda10.0 successfully.
However, the problem remains unsolved.
[log.txt](https://github.com/pytorch/pytorch/files/4883340/log.txt)

**Comment by lawpdas** [comment]
I cannot build pytorch source code with cuda10.2 #40909, but now I can build pytorch with cuda10.0.
By using master version and setting -std=c++14 in setup.py, this extension has been built successfully.
Thanks!
