### ISSUE TITLE
Linux libtorch c++ cmake not compatible with newer versions of cuDNN (for Caffe2)

### ISSUE THREAD

**Issue by rick-heig** [pytorch/pytorch#40965]
## 🐛 Bug

When building C++ examples with libtorch and CUDA the build scripts no longer work with newer versions of cuDNN.

```
$ cmake -DCMAKE_PREFIX_PATH=/home/user/pytorch/libtorch ..

-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v?  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at /home/user/pytorch/libtorch/share/cmake/Caffe2/public/cuda.cmake:170 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /home/user/pytorch/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/user/pytorch/libtorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
```

The reason is because `libtorch/share/cmake/Caffe2/public/cuda.cmake` uses a regular expression on `/usr/include/cudnn.h` to infer the version but for cuDNN v8 and above the version is in `/usr/include/cudnn_version.h` which is included by `/usr/include/cudnn.h`, however the regular expression in `cuda.cmake` now cannot find the version anymore because it does not apply/follow the include (e.g, run the C preprossor `cpp`) or check the cudnn_version.h file.

## To Reproduce

Tested on Ubuntu 18.04
1. Install CUDA 10.2
2. Install cuDNN 8.0.1
3. Use libtorch libtorch-cxx11-abi-shared-with-deps-1.5.1 (The one for CUDA 10.2)
4. Use CMake to build a simple example

## Possible fix

Check `cudnn_version.h` if it exists (for versions >= 8) along `cudnn.h` (for versions < 8) in libtorch/share/cmake/Caffe2/public/cuda.cmake to determine the cuDNN version.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): used libtorch downloaded as a zip from site
 - Build command you used (if compiling from source): -
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2 / 8.0.1
 - GPU models and configuration: Nvidia Quadro M2000M
 - Any other relevant information: -

cc @ezyang @gchanan @zou3519 @malfet @csarofeen @ptrblck

**Comment by rick-heig** [comment]
A quick and dirty edit of `libtorch/share/cmake/Caffe2/public/cuda.cmake` at line 148

Replacing : `file(READ ${CUDNN_INCLUDE_PATH}/cudnn.h CUDNN_HEADER_CONTENTS)`
By : `file(READ ${CUDNN_INCLUDE_PATH}/cudnn_version.h CUDNN_HEADER_CONTENTS)`

Allows me the get the expected result : 
```
cmake -DCMAKE_PREFIX_PATH=/home/user/pytorch/libtorch ..
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.0.1  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  5.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/pytorch/example-app/build
```

So a possible fix would be to append the contents of `cudnn_version.h` to `CUDNN_HEADER_CONTENTS` if the file `cudnn_version.h` exists so that the regular expressions that follow can extract the version.

**Comment by malfet** [comment]
This is already fixed in master and available in `release/1.6` branch:
https://github.com/pytorch/pytorch/blob/e173278348b329fa9c5e92018f959b3d95d26258/cmake/public/cuda.cmake#L148-L152

**Comment by fei-shan** [comment]
Hello, I realize that in cuda.cmake it still checks cudnn version even with no version available.  

[https://github.com/pytorch/pytorch/blob/e173278348b329fa9c5e92018f959b3d95d26258/cmake/public/cuda.cmake#L173-L175](url)

**Comment by xiepip** [comment]
> 

Hi @fei-shan ，I meet the same issue on you
May I know how you fix that?

**Comment by jinfagang** [comment]
@malfet The issue seems still exist on pytorch 1.11

I build FasterTransformer met this problem on CUDA 10.2 CUDNN 8.0

**Comment by malfet** [comment]
@jinfagang hmm, can you share some logs as well as links where you've installed CUDNN from? And does it have cuddn.h and/or cudnn_version.h?

**Comment by qn757275373** [comment]
> Hello, I realize that in cuda.cmake it still checks cudnn version even with no version available.
> 
> > https://github.com/pytorch/pytorch/blob/e173278348b329fa9c5e92018f959b3d95d26258/cmake/public/cuda.cmake#L173-L175
Hi @fei-shan ，I meet the same issue on you
May I know how you fix that?
