### ISSUE TITLE
Cuda assert fails: device-side assert triggered at /pytorch/torch/lib/THC/THCTensorSort.cu:61

### ISSUE THREAD

**Issue by rajarsheem** [pytorch/pytorch#4144]
I have a RNN module:
```python
class RNN(nn.Module):
    """ RNN that handles padded sequences """

    def __init__(self, input_size, hidden_size, bidirectional=False):
        super(RNN, self).__init__()
        self.bidirectional = bidirectional
        self.gru = nn.GRU(input_size, hidden_size, batch_first=True, bidirectional=bidirectional)

    def forward(self, seq, seq_length):
        """ seq => [batch_size, seq_length, feats], seq_length => [batch_size]. Both are Variables """
        print(seq_length.size())
        # input()
        seq_length, idx_sort = torch.sort(seq_length, 0, descending=True)
        _, idx_unsort = idx_sort.sort(0)
        seq = seq[idx_sort]
        # print(seq_length)
        seq = pack_padded_sequence(seq, seq_length.data.cpu().numpy(), batch_first=True)
        o, s = self.gru(seq)
        s = s.squeeze()
        o, _ = pad_packed_sequence(o, batch_first=True)
        # print(o.squeeze().data.cpu().numpy())
        # print(s.squeeze().data.cpu().numpy())
        o = o[idx_unsort]
        s = s[idx_unsort]
        # print(o.squeeze().data.cpu().numpy())
        if self.bidirectional:
            s = torch.cat([s[0], s[1]], dim=-1)
        # print(o.size(), s.size())
        # input()
        return o, s
```
When I call it **twice** with a batch of sequences and their lengths, I get an error at the 2nd call:
```
seq_length, idx_sort = torch.sort(seq_length, 0, descending=True)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/THCTensorSort.cu:61
```

**Comment by soumith** [comment]
what version of pytorch are you on? `print(torch.__version__)`

**Comment by rajarsheem** [comment]
Hi, It's ```0.3.0.post4```

**Comment by soumith** [comment]
also, run the program with:

`CUDA_LAUNCH_BLOCKING=1 python [yourmainfile]`

and see if a different stack trace is reported

**Comment by rajarsheem** [comment]
Yes, different.
```s = torch.cat([s[0], s[1]], dim=-1)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/THCGeneral.c:844```

**Comment by soumith** [comment]
but is there more stack trace? at the python level?

**Comment by rajarsheem** [comment]
Yes the full one:
```
Traceback (most recent call last):
File "/home/ramitra2/work/model.py", line 95, in forward
    u_p, _ = self.context_gru(seq, seq_length)
  File "/home/ramitra2/.conda/envs/deep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ramitra2/work/model.py", line 32, in forward
    s = torch.cat([s[0], s[1]], dim=-1)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/THCGeneral.c:844
```

**Comment by soumith** [comment]
I think this might be a user-error. Please verify that `idx_unsort` has all values within bounds of the sizes of `s` and the sizes of `o`. The line I suspect is       

```
o = o[idx_unsort]
s = s[idx_unsort]
```
I think it is doing an out-of-bounds indexing

**Comment by rajarsheem** [comment]
Resolved. I was doing the indexing on the wrong dimension of ```s```. It was supposed to be done on dim 1.
But a suggestion: better stack trace will facilitate easier debugging.

**Comment by soumith** [comment]
@rajarsheem because of the nature of the CUDA API (asynchronous) and device asserts not allowing much control, this is the best we can do at the moment.

**Comment by morawi** [comment]
Hi, I am having the same problem, caused at the line:
`test_loss += criterion(output, target).item() `

*** RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THCUNN/SoftMaxCommon.cuh:431

```
In[23]:train_set.labels
Out[23]: array([-1, -1, -1, ..., -1, -1, -1])
In[24]: len(train_set.labels)
Out[24]: 100000
In[25]:train_set.data.shape
Out[25]: (100000, 3, 96, 96)

```
Oh, and I am using small batch-size (25):

```
In[26]:train_loader.batch_size
Out[26]:25
```

The problem is, in fact, in the dataset, but I am not able to pinpoint it.
The code snippet where the error showed is the following:

```
model.eval()
    test_loss = 0   
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += criterion(output, target).item()

```

**Comment by soumith** [comment]
@morawi labels should not be `-1`, they should be within range of [0, n_classes]

**Comment by morawi** [comment]
@soumith totally agree; thus, I have replaced the -1's with some random numbers within the range `[0, n_classes]` , something like:
`train_set.labels = 1+ np.random.randint(n_classes, size=len(train_set.labels), dtype='uint8')`

That did not solve the problem. To enable the run, I have disabled getting the loss, via `loss.item()`, in both training and testing .

**Comment by morawi** [comment]
To avoid such error, it would be nice to have `criterion(output, target)` throw an exception if the size of `output` does not match the size of `target`.

**Comment by AlexTS1980** [comment]
It is certainly related to the mismatch between labels tensor size and the model's architecture (not necessarily at the output stage).

I was first training Mask R-CNN with 2 positive classes and then 3, but forgot to change the number of classes in each module:

```
box_predictor = FastRCNNPredictor(in_channels = 128, num_classes=4)
mask_predictor = MaskRCNNPredictor(in_channels=256, dim_reduced=256, num_classes=4)

```

**Comment by Mitesh0630** [comment]
> @rajarsheem because of the nature of the CUDA API (asynchronous) and device asserts not allowing much control, this is the best we can do at the moment.

I am also getting this error please help to solve this 

Traceback (most recent call last):
  File "/home/hardik/Downloads/STRNN-master/train_torch.py", line 202, in <module>
    total_loss += run(batch_user, batch_td, batch_ld, batch_loc, batch_dst, step=1)
  File "/home/hardik/Downloads/STRNN-master/train_torch.py", line 183, in run
    J.backward()
  File "/home/hardik/Downloads/STRNN-master/myvenv/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/hardik/Downloads/STRNN-master/myvenv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:649: indexSelectSmallIndex: block: [0,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by Mitesh0630** [comment]
@soumith please help in the above code
