### ISSUE TITLE
Type mismatch error with torch.nn.functional.grid_sample() under AMP

### ISSUE THREAD

**Issue by jh-jeong** [pytorch/pytorch#42218]
## 🐛 Bug

Found training a model with `grid_sample(input, grid)` throws the following error under AMP:
```
RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has c10::Half and grid has float
``` 
- This also happens in a form `(input, grid) = (float, c10:Half)`, depending on the model definition.
- I'm not sure, however, how could I reproduce this error in a minimal code snippet.
- Casting both `(input, grid) -> (input.float(), grid.float())` could bypass this issue.

## To Reproduce

1. Construct a complex model including `grid_sample()`
1. Run it under `with autocast()`:

## Expected behavior

AMP is expected to handle every native functions properly in an autocast-enabled region.

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.87.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.4
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0
[pip] torchlars==0.1.2
[pip] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.0.15           py38ha843d7b_0
[conda] mkl_random                1.1.0            py38h962f231_0
[conda] numpy                     1.18.1           py38h4f9e942_0
[conda] numpy-base                1.18.1           py38hde5b4d6_1
[conda] pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchlars                 0.1.2                    pypi_0    pypi
[conda] torchvision               0.7.0                py38_cu101    pytorch
```

cc @mcarilli

**Comment by mcarilli** [comment]
`grid_sample` used to be an FP32list function in `apex.amp` to avoid slow FP16 atomics in old versions of Pytorch.  The slow atomics were fixed in recent Pytorches, so I removed `grid_sample` from the FP32list in `torch.cuda.amp`.  However, I should have moved it to the promote list, because it takes multiple inputs that must be the same dtype.

The [cast lists](https://pytorch.org/docs/stable/amp.html#op-specific-behavior) are partially based on experience so thanks for raising the issue.

**Comment by sniklaus** [comment]
Is there a workaround that we could use until 1.6.1 is released? Would it make sense to have an if statement that checks if one of the two tensors is half precision but the other one not and then cast the other one to half precision?

**Comment by Leerw** [comment]
@mcarilli same issue

**Comment by phongnhhn92** [comment]
@mcarilli I still have this issue with Pytorch 1.6. Is there any way to fix this ?

**Comment by danieledema** [comment]
Hi all, I have the exact same issue. any idea if there is a workaround waiting for the fix?

**Comment by mcarilli** [comment]
Working on permanent fix this week.  In the meantime you can probably work around by casting grid_sample's inputs to float().

**Comment by alwynmathew** [comment]
Is this fix? I still get same error in pytorch 1.7.1

**Comment by masudbaki** [comment]
Disable GPU..this problem will go away with it

**Comment by Leerw** [comment]
> Disable GPU..this problem will go away with it

GOOD JOKE🤣

**Comment by rubencart** [comment]
Same for me, pytorch 1.7.1, but the other way around (input is float and grid c10::Half).
```python
RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has float and grid has c10::Half
```

**Comment by hongsukchoi** [comment]
Work around:
I just made the input to be float to match the dtype before grid_sampling.

**Comment by danansheng** [comment]
> Work around:
> I just made the input to be float to match the dtype before grid_sampling.

hi，how do i complete this work? the input is complicated.

**Comment by sidml** [comment]
@danansheng 
The issue is resolved in nightly branch, perhaps you can use it.
The following branch works for me:
`wget https://download.pytorch.org/whl/nightly/cu111/torch-1.10.0.dev20210731%2Bcu111-cp37-cp37m-linux_x86_64.whl`
`pip install torch-1.10.0.dev20210731+cu111-cp37-cp37m-linux_x86_64.whl`

**Comment by danansheng** [comment]
> @danansheng
> The issue is resolved in nightly branch, perhaps you can use it.
> The following branch works for me:
> `wget https://download.pytorch.org/whl/nightly/cu111/torch-1.10.0.dev20210731%2Bcu111-cp37-cp37m-linux_x86_64.whl`
> `pip install torch-1.10.0.dev20210731+cu111-cp37-cp37m-linux_x86_64.whl`

thanks,but i can only use torch version 1.5.0
