### ISSUE TITLE
Failed to build with CUDA 11 on Windows when system protobuf is used:  Ambiguous operator overload.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#42939]
## Bug

Get the following error when building with CUDA.
```
D:/roaster-scratch/pytorch/build\caffe2/proto/caffe2.pb.h(151): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "c10::operator+(int, c10::BFloat16)"
            function "c10::operator+(c10::BFloat16, int)"
            function "c10::operator+(int, c10::Half)"
            function "c10::operator+(c10::Half, int)"
            operand types are: const caffe2::ExternalDataProto_SourceType + int

D:/roaster-scratch/pytorch/build\caffe2/proto/caffe2.pb.h(186): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "c10::operator+(int, c10::BFloat16)"
            function "c10::operator+(c10::BFloat16, int)"
            function "c10::operator+(int, c10::Half)"
            function "c10::operator+(c10::Half, int)"
            operand types are: const caffe2::TensorProto_DataType + int

D:/roaster-scratch/pytorch/build\caffe2/proto/caffe2.pb.h(211): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "c10::operator+(int, c10::BFloat16)"
            function "c10::operator+(c10::BFloat16, int)"
            function "c10::operator+(int, c10::Half)"
            function "c10::operator+(c10::Half, int)"
            operand types are: const caffe2::TensorProto_StorageType + int

D:/roaster-scratch/pytorch/build\caffe2/proto/caffe2.pb.h(239): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "c10::operator+(int, c10::BFloat16)"
            function "c10::operator+(c10::BFloat16, int)"
            function "c10::operator+(int, c10::Half)"
            function "c10::operator+(c10::Half, int)"
            operand types are: const caffe2::TensorBoundShape_DimType + int

D:/roaster-scratch/pytorch/build\caffe2/proto/caffe2.pb.h(272): error: more than one operator "+" matches these operands:
            built-in operator "arithmetic + arithmetic"
            function "c10::operator+(int, c10::BFloat16)"
            function "c10::operator+(c10::BFloat16, int)"
            function "c10::operator+(int, c10::Half)"
            function "c10::operator+(c10::Half, int)"
            operand types are: const caffe2::DeviceTypeProto + int

5 errors detected in the compilation of "D:/roaster-scratch/pytorch/caffe2/operators/utility_ops.cu".
utility_ops.cu
-- Removing D:/roaster-scratch/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_utility_ops.cu.obj
"C:/Program Files/CMake/bin/cmake.exe" -E remove D:/roaster-scratch/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_utility_ops.cu.obj
CMake Error at torch_cuda_generated_utility_ops.cu.obj.Release.cmake:281 (message):
  Error generating file
  D:/roaster-scratch/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_utility_ops.cu.obj


ninja: build stopped: subcommand failed.
```

Problematic lines in generated proto header:
```
constexpr int ExternalDataProto_SourceType_SourceType_ARRAYSIZE = ExternalDataProto_SourceType_SourceType_MAX + 1;
constexpr int TensorProto_DataType_DataType_ARRAYSIZE = TensorProto_DataType_DataType_MAX + 1;
constexpr int TensorProto_StorageType_StorageType_ARRAYSIZE = TensorProto_StorageType_StorageType_MAX + 1;
constexpr int TensorBoundShape_DimType_DimType_ARRAYSIZE = TensorBoundShape_DimType_DimType_MAX + 1;
constexpr int DeviceTypeProto_ARRAYSIZE = DeviceTypeProto_MAX + 1;
```
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/5203025/90060939-04efcf00-dd18-11ea-97a3-2db68eb3e21e.png">

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win Server 2019
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+msvc2019
 - CUDA/cuDNN version: 11.0/8

cc @malfet @seemethere @walterddr @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
@xkszltl can you please share the full CMake configuration logs? (I.e. what version of Visual Studio compiler are you using?)
What I'm trying to understand, is how much your config is different from the configuration used in https://app.circleci.com/pipelines/github/pytorch/pytorch/199738/workflows/6261d282-cae7-4592-bdda-11944e408ae1/jobs/6673371

**Comment by peterjc123** [comment]
How is this issue different from https://github.com/pytorch/pytorch/issues/42549? Isn't this already fixed in master?

**Comment by xkszltl** [comment]
@malfet 
This is the script (except we USE_CUDA=ON set manually): https://github.com/xkszltl/Roaster/blob/1f97fe6b75803fd0880a84c387f5497ee3b1c99f/win/pkgs/pytorch.ps1#L125-L174

@peterjc123 
The PR you mentioned alters protoc output on the fly, but that code path relies on `CAFFE2_LINK_LOCAL_PROTOBUF`, and doesn't work for us because we use system protobuf.

**Comment by malfet** [comment]
@xkszltl what version of protoc compiler are you using?

**Comment by xkszltl** [comment]
@malfet 3.12.4, build from source.

**Comment by xkszltl** [comment]
How's the issue?
I recently upgrade to protobuf 3.13.0 and this issue is still there.

**Comment by peterjc123** [comment]
Maybe we should patch the files even if the system protobuf is used. What do you think, @malfet @ezyang ?

**Comment by ezyang** [comment]
Yes, I think I agree with you.

**Comment by peterjc123** [comment]
@xkszltl Would you please test whether https://github.com/pytorch/pytorch/pull/44583 fixes your problem?

**Comment by xkszltl** [comment]
Testing...I think it should.
Could you also propose the fix to upstream (protobuf), as it's a general ambiguity.

**Comment by xkszltl** [comment]
@peterjc123 
Seems it fixes this issue so please merge, but we also end up with another one: https://github.com/pytorch/pytorch/issues/44599

**Comment by mszhanyi** [comment]
@peterjc123 , thank your fix to this issue, I'm assign the owner to you
