### ISSUE TITLE
Vulkan Api Backend Build Error with GCC

### ISSUE THREAD

**Issue by MP5A3** [pytorch/pytorch#48483]
## To Reproduce

1. ccmake config with USE_VULKAN_API=1
2. ninja build

## Environment

Currently using gcc-10.2.0

## Additional context

many errors:
e.g.:
```
../aten/src/ATen/native/vulkan/ops/Tensor.h:390:19: error: ‘class at::native::vulkan::ops::vTensor::View::State’ is private within this context
  390 |       const View::State::Bundle&);
```
```
../aten/src/ATen/native/vulkan/api/Pipeline.h:119:41: error: declaration of ‘typedef class at::native::vulkan::api::Handle<VkPipeline_T*, at::native::vulkan::api::destroy_Pipeline> at::native::vulkan::api::Pipeline::Factory::Handle’ changes meaning of ‘Handle’ [-fpermissive]
  119 |     typedef Handle<VkPipeline, Deleter> Handle;
```

**Comment by iou2much** [comment]
any update on this, please?

**Comment by MP5A3** [comment]
> any update on this, please?

Hi, there's other issue related to Vulkan backend build, refer to https://github.com/pytorch/pytorch/pull/49572, I think I'll rebase to a build clean commit, thanks.

**Comment by iou2much** [comment]
Thanks. I've merged https://github.com/pytorch/pytorch/pull/48484 to the master. and it was built successfully.

**Comment by AshkanAliabadi** [comment]
@malfet @IvanKobzarev What are your suggestions for a PyTorch CI job (using GCC) to which we can add our Vulkan unit tests to ensure that GCC breaking changes are caught early?

**Comment by Yoline777** [comment]
Get the same error. How to fix it

**Comment by Yoline777** [comment]
I upadate to pytorch 1.8.2 still get the error.
`error: ‘class at::native::vulkan::ops::vTensor::View::State’ is private within this context
       const View::State::Bundle&);`
