### ISSUE TITLE
ONNX export of Pytorch models is buggy.

### ISSUE THREAD

**Issue by anirudhacharya** [pytorch/pytorch#5146]
While exporting pytorch models to ONNX format using torch_onnx.export, sometimes it generates the wrong serialized file. The generated onnx file cannot be imported into any of the other frameworks like caffe2 or mxnet. When I try to import it, I get the following error message -

> Traceback (most recent call last):
> File "alon.py", line 33, in 
> prepared_backend = onnx_caffe2.backend.prepare(model)
> File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx_caffe2/backend.py", line 439, in prepare
> super(Caffe2Backend, cls).prepare(model, device, **kwargs)
> File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/backend/base.py", line 53, in prepare
> onnx.checker.check_model(model)
> File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 154, in check_model
> check_graph(model.graph)
> File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 127, in check_graph
> check_node(node)
> File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx/checker.py", line 40, in check_node
> 'NodeProto of type {} did not pass defs schema check.'.format(str(node.op_type)))
> ValueError: NodeProto of type ReduceMean did not pass defs schema
> check.

Even when I try to run  the onnx model checker on the generated model, I get the following errors -
```bash
import onnx
model = onnx.load("toy_model.onnx")
onnx.checker.check_model(model)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/onnx-1.0.1-py2.7-macosx-10.9-x86_64.egg/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Attribute 'axes' is expected to have field 'ints'

==> Context: Bad node spec: input: "5" output: "6" op_type: "ReduceMean" attribute { name: "axes" i: 2 type: INT } attribute { name: "keepdims" i: 0 type: INT } doc_string: "alon.py(18): forward\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/nn/modules/module.py(325): __call__\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/jit/__init__.py(236): traced_inner\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/jit/__init__.py(259): wrapper\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/jit/__init__.py(241): forward\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/nn/modules/module.py(325): __call__\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/jit/__init__.py(217): trace\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/onnx/__init__.py(116): _export\n/Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages/torch/onnx/__init__.py(75): export\nalon.py(27): <module>\n"
```
Installation Details
- OS: MacOS Sierra
- PyTorch version: 
```bash
conda list | grep torch
pytorch                   0.3.0           py27_cuda0.0_cudnn0.0he480db7_4    pytorch
torchvision               0.2.0            py27hfc0307a_1    pytorch
```
- How you installed PyTorch (conda, pip, source): conda
- Python version: 2.7

Following is the code that creates the model
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import torch.onnx as torch_onnx

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3,3), stride=1, padding=0, bias=False)

    def forward(self, inputs):
        x = self.conv(inputs)
        x = x.view(x.size()[0], x.size()[1], -1)
        return torch.mean(x, dim=2)

input_shape = (3, 100, 100)
model_onnx_path = "toy_model.onnx"
model = Model()
model.train(False)

dummy_input = Variable(torch.randn(1, *input_shape))
torch_onnx.export(model, 
                  dummy_input, 
                  model_onnx_path, 
                  verbose=True)
```

Code that tries to import it into mxnet/caffe -
```python
import onnx
import onnx_caffe2.backend
# Load the ONNX ModelProto object. model is a standard Python protobuf object
model = onnx.load(model_onnx_path)
prepared_backend = onnx_caffe2.backend.prepare(model)
```
and
```python
import onnx_mxnet, mxnet
sym, params = onnx_mxnet.import_model(model_onnx_path)
```
I think this a bug with Pytorch's export to ONNX functionality, do acknowledge if you think the same.

**Comment by ezyang** [comment]
Thanks for the report. This was fixed in b42f1638351259675edc6aa234c1304a98e2c3ce; please try a source build of PyTorch!

**Comment by anirudhacharya** [comment]
When might this change go out as a release, so that I might be able to install it as opposed to building it from source?

**Comment by cswwp** [comment]
how fix it?

**Comment by cswwp** [comment]
i had build from source to install pytorch, but it still show this error, 
  File "<stdin>", line 1, in <module>
  File "/home/parker/anaconda2/envs/caffe2/lib/python3.6/site-packages/onnx_caffe2/backend.py", line 439, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/home/parker/anaconda2/envs/caffe2/lib/python3.6/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/home/parker/anaconda2/envs/caffe2/lib/python3.6/site-packages/onnx/checker.py", line 154, in check_model
    check_graph(model.graph)
  File "/home/parker/anaconda2/envs/caffe2/lib/python3.6/site-packages/onnx/checker.py", line 127, in check_graph
    check_node(node)
  File "/home/parker/anaconda2/envs/caffe2/lib/python3.6/site-packages/onnx/checker.py", line 40, in check_node
    'NodeProto of type {} did not pass defs schema check.'.format(str(node.op_type)))
ValueError: NodeProto of type Reshape did not pass defs schema check.

how fix it?
