### ISSUE TITLE
[minor] torch.cuda.is_available() == False, but still complains about driver mismatch

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#52675]
Maybe if `CUDA_VISIBLE_DEVICES` is empty, then it could return False immediately. I'm specifically nulling out `CUDA_VISIBLE_DEVICES` to prevent any CUDA-related code from running completely.

```shell
CUDA_VISIBLE_DEVICES= python -c "import torch; print(torch.cuda.is_available())"

# /prefix/miniconda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607369981906/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

**Comment by malfet** [comment]
Thank you for reporting. This should have been fixed by https://github.com/pytorch/pytorch/pull/51806 unless returned error codes are different with your version of CUDA.
Can you please run `python3 -m torch.utils.collect_env` and share its output here.

**Comment by vadimkantorov** [comment]
```
Collecting environment information...
/vadim/prefix/miniconda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607369981906/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 14.04 LTS (x86_64)
GCC version: (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Clang version: 3.5-1ubuntu1 (trunk) (based on LLVM 3.5)
CMake version: version 2.8.12.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 418.43
cuDNN version: /usr/local/stow/cuda-7.5.18/lib/cuda-7.5.18/lib64/libcudnn.so.7.0.64
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.8.2                py38_cu102    pytorch
```

**Comment by vadimkantorov** [comment]
Maybe differently from https://github.com/pytorch/pytorch/pull/51806, the driver exists, it's just it's outdated. But in any case, I don't want any warnings because I disabled CUDA

**Comment by malfet** [comment]
Hmm, I believe it is a correct behavior:
if some download pytorch with CUDA support 10.2, but only has 10.1 driver available on the system, we should print a warning explaining why CUDA acceleration is not working correctly. 

In my opinion, since CUDA_VISIBLE_DEVICES` is CUDA driver specific issue and not part of any API, PyTorch better not hardcode any assumptions on its functionality.

On the other hand, change should be very localized, so please do not hesitate to share a PR.

**Comment by vadimkantorov** [comment]
> we should print a warning explaining why CUDA acceleration is not working correctly.

well, precisely for this reason I set CUDA_VISIBLE_DEVICES and was very surprised to still see the warning given out by the guard function :)



> On the other hand, change should be very localized, so please do not hesitate to share a PR.

ok!

**Comment by malfet** [comment]
> well, precisely for this reason I set CUDA_VISIBLE_DEVICES and was very surprised to still see the warning given out by the guard function :)

`CUDA_VISIBLE_DEVICES` is interpreted by `libcuda.so`, CUDA runtime (aka `libcudart.so`) knowns nothing about it, so it first tries to initialize CUDA driver, and returns `cudaErrorInsufficientDriver` if version is incompatible, even before visible devices variable can be interpreted.

And unfortunately, workaround you are proposing would not work for some users, who like me define CUDA_VISIBLE_DEVICE to large value to disable cuda (for example `CUDA_VISIBLE_DEVICES=16`)

**Comment by vadimkantorov** [comment]
Is there a way to disable CUDA in such a way that it will not try to initialize the driver? (instead of CUDA_VISIBLE_DEVICES)

**Comment by vadimkantorov** [comment]
e.g. something like `TORCH_USE_CUDA=OFF python -c "import torch; print(torch.cuda.is_available())"`. maybe such a runtime switch already exists?

**Comment by vadimkantorov** [comment]
cc @ptrblck

**Comment by ptrblck** [comment]
I don't fully understand the use case here.
Masking the device works properly assuming your setup isn't invalid/broken:
```
CUDA_VISIBLE_DEVICES=0 python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.device_count())"
True
1
CUDA_VISIBLE_DEVICES="" python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.device_count())"
False
0
```

In your setup it seems your CUDA setup is broken and PyTorch will not be able to use the GPU at all.
Masking the device would thus still raise the warning about your invalid setup, but should not use the GPU.
Are you asking to silence the valid warning? Why wouldn't CPU-only binaries work in your setup (since your driver is too old to execute GPU workloads using the CUDA-enabled PyTorch binaries)?

**Comment by vadimkantorov** [comment]
Trying to recall the usecases:

1) Have a machine with zero free CUDA memory, e.g. the CUDA context can't be created. Wanting to still use torch.cuda.is_available() / torch.cuda.get_device_count() even if a context can't be created - for simplicity of some CPU-only debugging

2) In academic setting we have a cluster of machines with the same OS. some machines have GPU, some machines don't. We often install a persistent conda env on some network drive and then use these dependencies. It's easier to just have a single CUDA-enabled pytorch installed, and not swap the envs. It's useful to just be able to disable CUDA-driver loading / context creating with a env. variable which would let a CUDA-enabled pytorch to just return that we have 0 cuda devices and not actually load any of CUDA-libraries or at least to not call any functions in them

**Comment by ptrblck** [comment]
Thanks for the explanation!

1. This point seems to have different requirements. The usage of some `torch.cuda`calls to check for available devices etc. without creating as CUDA context makes sense and is tracked here: https://github.com/pytorch/pytorch/issues/83973. Masking the device via `CUDA_VISIBLE_DEVICES` would also work as long as the driver itself is not raising any errors (which means as long as your setup isn't invalid).
2. This use case is more tricky as you are expecting the GPU binaries to work in any CPU environment without raising any warnings or errors. Are these warnings blocking your workflow and if so, would it be possible to just silence the warning itself (instead of trying to rip out all CUDA support in the binaries via an env variable)?

**Comment by vadimkantorov** [comment]
1. Yep, and my proposal is to add in those calls: torch.cuda.is_available and torch.cuda.get_device_count a shortcut that would check some env. vars (TORCH_DISABLE_CUDA or CUDA_VISIBLE_DEVICES="") and to return early before any driver interaction or cuda context was attempted to be created
2. Yep, I silenced those warnings in practice, but if such an env var is supported, then in the beginning of the program we can easily disable CUDA if no devices are available and easily avoid CUDA context creation and occupying that useless CUDA mem for cpu-only debugging 

An important usecase is also to easily switch to CPU-only DDP for debugging.

**Comment by vadimkantorov** [comment]
Would also be good for preventing `triton` from being marked as available and CUDA driver interaction if all CUDA devices are switched off: https://github.com/pytorch/pytorch/pull/94823/files#diff-ea2b2df4a1e32c2c731fff8926e0f52485583b57cc3991f00cc185ee7eb333bbR5

**Comment by vadimkantorov** [comment]
related: https://github.com/pytorch/pytorch/issues/99982

**Comment by jataylo** [comment]
Might be worth retesting this @vadimkantorov 

I dont see this on ROCm side at least: (Relating to https://github.com/pytorch/pytorch/pull/143570)

**Triton backend initializing cuda:**
```
import torch
import triton
driver = triton.runtime.driver
target = driver.active.get_current_target()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/amd/driver.py", line 497, in get_current_target
    device = self.get_current_device()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 955, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 320, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

**cuda.is_available test:**
```
torch.version.hip
'6.2.41134-65d174c3e'
torch.cuda.is_available()
False
```

**Comment by vadimkantorov** [comment]
In this issue, it was also the problem that CUDA driver / CUDA libs were broken. So the feature request was for torch.cuda.is_available() to become a not-cuda-touching guard if requested with some env variable, even in CUDA-enabled torch builds...
