### ISSUE TITLE
AssertionError when running nn.GRU or nn.LSTM on CUDA.

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#5667]
Got it on compute 3.0 GPU, on branch 0.3.1, built from source with system NCCL 1.3.5, CUDA 9.1 and cuDNN 7.1.
This is enough to get it, on my configuration:
```python
m = nn.GRU(10,10).cuda()
data = Variable(torch.randn(10,10,10)).cuda()
m(data)
```
[Stack trace](https://gist.github.com/VladislavZavadskyy/b223c1a704f067ea00f4397e308756a9)

**Comment by zou3519** [comment]
I'm running CUDA 9.0, cuDNN 7, 0.3.1post2 (from conda), and have not been able to reproduce.
Have also tried the same configuration above on the master branch, but I'll try more machines.

**Comment by leomao** [comment]
I have encountered the same issue too.
The version is pytorch 0.3.1 built from source with nccl 2.1.4, cuda 9.1.85 and cudnn 7.1.1.

Executing
```python
import torch.nn as nn
l = nn.LSTM(10, 10).cuda()
```
will get following error:
```
Traceback (most recent call last):
  File "lstm_test.py", line 3, in <module>
    l = nn.LSTM(10, 10).cuda()
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/usr/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError
```

**Comment by leomao** [comment]
More information:
I also built pytorch master with nccl 2.1.4, cuda 9.1.85 and cudnn 7.1.1.
This issue is not present on the master branch.

**Comment by ngimel** [comment]
Cudnn 7.1 changed some outputs, so pytorch  3.1 does not work with cudnn 7.1. This is fixed in master.

**Comment by Fenugreek** [comment]
I have encountered the same issue too. 

Running up-to-date ArchLinux (rolling release, no version numbers), using their `python-pytorch-cuda 0.3.1-2` package, which uses `cudnn 7.1.1-1` and `python 3.6`.

Same result and error message as @leomao . Writing here since issue is still tagged "needs reproduction".  For me, I get the error for vanilla nn.RNN also.

**Comment by SsnL** [comment]
Fixed on master

**Comment by abhinavbh08** [comment]
I am also encountering the same issue. I am also using nn.RNN module. How can I solve it?

**Comment by Fenugreek** [comment]
To help @abhinavbh08 a bit more: the issue has been fixed in the master branch of the source code on github, but not in the current 0.3.1 release. To complie and use the code from the master branch, you can

```
# Follow instructions at this URL:
https://github.com/pytorch/pytorch#from-source
 ```

Another workaround is to use the QRNN type of RNN, which does not produce the error and works fine for me:
[https://github.com/salesforce/pytorch-qrnn](https://github.com/salesforce/pytorch-qrnn)

**Comment by RoyiAvital** [comment]
So if I use PyTorch 0.3.1 from Anaconda default channel, which CuDNN should I use?
The option are CuDNN 7.1.2 (Which requires CUDA 9.0) or CuDNN 7.0.5?

**Comment by EntilZha** [comment]
I am also running on arch with pytorch 0.3.1/cudnn 7.1, and ran into this issue. I don't mind compiling from source, but haven't updated my code for 0.4. Is it possible to build a version from some point/commit in master which is 0.3.X compatible, but includes the fix?

**Comment by ngimel** [comment]
Easiest is building from 0.3.X source with cudnn 7.0, if you do need 7.1 (why?) then you have to fix the 0.3.1 yourself by applying a fix similar to https://github.com/pytorch/pytorch/pull/5439/files. You can't apply #5439 directly because in 0.3.x cudnn rnn bindings were still in python, and they were moved to C++ for 0.4.

**Comment by varshaneya** [comment]
I am getting the same assertion error on Ubuntu server 16.04 with cuDNN version 6.0.21, pytorch version 0.3.1 and CUDA version 8.0. Where is the problem lying? Is it cuDNN or with pytorch 0.3.1?

**Comment by ntomita** [comment]
@varshaneya FYI, had same issue with the same configuration. Installed pytorch 0.3.0 solved the issue on my case.

**Comment by varshaneya** [comment]
The latest stable release of pytorch (0.4.1) works fine with anaconda.

**Comment by ntomita** [comment]
Good to know, thanks!

**Comment by davidalbertonogueira** [comment]
@pencoa , have you fixed it? I'm facing the same error.

**Comment by olivernina** [comment]
@ntomita I confirmed that updating to 0.3.0 fixes the problem. Thanks
