### ISSUE TITLE
Annoying warning with nn.MaxPool2d

### ISSUE THREAD

**Issue by mravanelli** [pytorch/pytorch#60053]
Hi, thank you very much for pytorch 1.9!
I'm trying to update SpeechBrain (https://github.com/speechbrain/speechbrain) to support pytorch 1.9.
Everything seems to work, but I noticed an annoying warning when using  nn.MaxPool2d:

```
import torch
import torch.nn as nn

m = nn.MaxPool2d(3, stride=2)
m = nn.MaxPool2d((3, 2), stride=(2, 1))
input = torch.randn(20, 16, 50, 32)
output = m(input)
```

```
UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448238472/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
```

Note that it only appears when using nn.MaxPool2d (nn.MaxPool1d and  nn.AvgPool1d have no warning).
Any idea?

cc @zou3519 @albanD @mruberry @jbschlosser

**Comment by gchanan** [comment]
Thanks for reporting, I was able to reproduce this.

**Comment by ngimel** [comment]
Likely #56459

**Comment by jbschlosser** [comment]
See also: https://github.com/pytorch/pytorch/issues/57949

**Comment by meganset** [comment]
This issue is marked closed, but does not look fixed.
I noticed the warning from the c++ side, but it is still there in python as well.

```
>>> import torch
>>> m=torch.nn.MaxPool2d(3)
>>> m=torch.nn.MaxPool2d(3,stride=1)
>>> t=torch.arange(16).to(torch.float).view(1,4,4)
>>> m(t)
/home/t/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
tensor([[[10., 11.],
         [14., 15.]]])

>>> torch.__version__
'1.9.0'
```

From libtorch:

```
 auto m=torch::nn::MaxPool2d(3);
 auto t=torch::arange(16).to(torch::kFloat).view({1,4,4});
 std::cerr << m(t) << "\n";

[W TensorImpl.h:1156] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
(1,.,.) = 
  10
[ CPUFloatType{1,1,1} ]
```

**Comment by meganset** [comment]
Ok, I misunderstood: 
the spurious warning is in the 1.9.0 release, but fixed now in the nightly build.

**Comment by pmeier** [comment]
Would be nice if this could make it into `1.9.1`.

**Comment by joaqo** [comment]
Having same issue, agreed that it would be nice if it made it into `1.9.1`.

**Comment by pbldmngz** [comment]
This annoying warning still persists. 
```python
return reader.readtext(self.__image_to_byte_array(image), detail=0)
```
```
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
c:\venv\python39\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally 
at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
```
I'm using a laptop with no GPU, I hope is not part of the problem.

**Comment by pmeier** [comment]
@pbldmngz this was fixed in #60059, but there has been no release since.
