### ISSUE TITLE
ONNX problem with BatchNormalization in FlowNet (pytorch variant)

### ISSUE THREAD

**Issue by epiception** [pytorch/pytorch#6300]
Hi,
I faced this problem when exporting the pytorch model for FlowNetS with BatchNorm, mainly when checking the IR 

The pytorch model is,  https://github.com/ClementPinard/FlowNetPytorch

PyTorch version: 0.4.0a0+2e156f3 (No GPU, CPU only)
The repo steps I followed,

1. Cloned the model: https://github.com/ClementPinard/FlowNetPytorch
git clone https://github.com/ClementPinard/FlowNetPytorch.git

2. Downloaded pretrained weights for the BatchNorm variant, and placed it in the main repo folder:
https://drive.google.com/drive/folders/16eo3p9dO_vmssxRoZCmWkTpNjKRzJzn5

3. Script to create onnx file (again in the same folder), check IR, recreate error:

        import torch
        from torch.autograd import Variable
        import torch.onnx
        
        import onnx
        from onnx_tf.backend import prepare
        
        import models
        
        model = models.FlowNetS
        
        # Original model trained on GPU, mapped for CPU
        data = torch.load("./flownets_bn_EPE2.459.pth.tar", map_location=lambda storage, loc: storage)
        
        # dummy input
        dummy_input = Variable(torch.randn(10, 6, 224, 224))
        
        state_dict = model.flownets_bn(data = data)
        torch.onnx.export(state_dict, dummy_input, "flownet.onnx", verbose=True)
        
        #no error here
        model = onnx.load("flownet.onnx")
        
        # Check that the IR is well formed
        onnx.checker.check_model(model)

Traceback message,
Traceback (most recent call last):
  File "onnx_example.py", line 29, in <module>
    onnx.checker.check_model(model)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input index 3 must be set to consumed for operator BatchNormalization

==> Context: Bad node spec: input: "64" input: "2" input: "3" input: "4" input: "5" output: "65" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "momentum" f: 0.9 type: FLOAT } doc_string: "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py(1206): batch_norm\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.py(49): forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(359): _slow_forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(369): __call__\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py(91): forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(359): _slow_forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(369): __call__\n/media/epiception/Windows/Ganesh/Datasets/Weights/flownet/FlowNetPytorch/models/FlowNetS.py(86): forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(359): _slow_forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(369): __call__\n/usr/local/lib/python2.7/dist-packages/torch/jit/__init__.py(286): forward\n/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py(371): __call__\n/usr/local/lib/python2.7/dist-packages/torch/jit/__init__.py(253): get_trace_graph\n/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py(133): _export\n/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py(84): export\n/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py(21): export\nonnx_example.py(23): <module>\n"

Thank You!

**Comment by arogozhnikov** [comment]
Just tested, given example fails even with simle BatchNorm2d. Below is the minimal example for reproduction:
```python
import torch
from torch.autograd import Variable
import torch.onnx
import onnx
# from onnx_tf.backend import prepare

dummy_input = Variable(torch.randn(10, 6, 224, 224))
model = torch.nn.BatchNorm2d(num_features=6)
torch.onnx.export(model, dummy_input, "flownet.onnx", verbose=True)

#no error here
onnx_model = onnx.load("flownet.onnx")
# Check that the IR is well formed
onnx.checker.check_model(onnx_model)
```

**Comment by StuvX** [comment]
onnx.checker.check_model is throwing the same error for resnet

**Comment by bddppq** [comment]
This is a recent change in onnx https://github.com/onnx/onnx/commit/f4acf281eff7afe81f29f014edaa87e4c04c01a3 that removed the in-place annotations in onnx level. This change is not included in our last onnx release but we have made the corresponding change to pytorch master to pair with onnx master. So If you can install onnx from the onnx repo current master, this issue should be solved.

**Comment by SsnL** [comment]
Close as this is fixed on onnx side.

**Comment by StuvX** [comment]
Sorry, how am I supposed to install onnx from the onnx master? I tried pip install onnx -U but it is up to date, I can't see how to build from source any other way. Apologies if this should be raised in the ONNX issues or has been covered elsewhere.

**Comment by StuvX** [comment]
For anybody wondering how to install onnx from master (as I was), git clone onnx then pip install ./onnx

good luck!

**Comment by silaskuo** [comment]
@bddppq , when do plan to to move this change to the release? Thanks.

**Comment by epiception** [comment]
@StuvX did you face any problems with pybind11?
I'm facing this issue after cloning and running pip install ./onnx 
/tmp/pip-_y4wFf-build/onnx/cpp2py_export.cc:1:31: fatal error: pybind11/pybind11.h: No such file or directory
compilation terminated.
Does it require installing pybind11 from source? pip install pybind11 does not solve this for me.

**Comment by silaskuo** [comment]
@epiception : actually I met the same problem as you. Did you try git clone --recursive https://github.com/onnx/onnx.git ? You need to add --recursive here.

**Comment by epiception** [comment]
Thanks @silaskuo. Guess I missed it. Works, and no errors using check_model as well.

**Comment by hanzhaogang** [comment]
> git clone onn
hi I tried pip install ./onnx in the downloaded onnx-master directory, but got a cMake error:
    CMake Error at CMakeLists.txt:17 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

can u please advice?

**Comment by Ananyaaa** [comment]
@hanzhaogang, have you resolved the problem?

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

I am also facing similar issues.
