### ISSUE TITLE
Post-install issue: Anaconda3, Ubuntu 16.04 Python 3.6 Caffe2

### ISSUE THREAD

**Issue by shirishr** [pytorch/pytorch#6562]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
PyTorch or Caffe2: **Caffe2**
OS:**Ubuntu 16.04**
PyTorch version:
How you installed PyTorch (conda, pip, source): **PyTorch not installed in this environment at this time**
Python version:**3.6**
CUDA/cuDNN version:**9.0/7.0**
GPU models and configuration: **GeForce 1050Ti**
GCC version (if compiling from source):**5.4**
CMake version:**3.9.0-rc5**
Build command you used (if compiling from source):
Versions of any other relevant libraries:
Native Python in Ubuntu 16.04 is Python2 (2.7) and Python3 (3.5)

Anaconda3 installed (Version4.5.0)
Created an environment conda create --name caffe36 python==3.6
source activate caffe36
conda install -c caffe2 caffe2-cuda9.0-cudnn7
python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" results in **success**
python -c 'from caffe2.python import workspace' 2>/dev/null && echo "Success" || echo "Failure" results in **success**

Thanks to @pjh5 for guding me [through](https://github.com/pytorch/pytorch/issues/6464) this :100: 

Now comes the post-install issue

Am following a tutorial from [https://github.com/caffe2/tutorials](https://github.com/caffe2/tutorials
)
A notebook called **Basics.ipynb** or **CIFAR10_Part1.ipynb**

After running the very first cell... I see messages

WARNING:root:This caffe2 python run **does not** have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory

Caffe2 install was with conda install -c caffe2 caffe2-cuda9.0-cudnn7

other packages keras, tensorflow successfully run on GPU, why does caffe2 fail?

**My updates**
This looks like a repeat of #2264
I have installed NCCL 2.1.15 after reading #2264. The warning This caffe2 python run **does not** have GPU support remains

**Comment by pjh5** [comment]
I think this tutorial https://caffe2.ai/docs/tutorials#null__multi-gpu-training-with-caffe2 should use the GPU. I don't think Predictor can use GPU at this point in time. 

To confirm, are you still getting any warnings when you run Caffe2?

**Comment by shirishr** [comment]
@pjh5,
No, I am not getting any warnings in the notebooks that I am running from [https://github.com/caffe2/tutorials](https://github.com/caffe2/tutorials)

I am documenting everything I did to overcome errors / warnings for future readers who may come across similar errors / warnings. Hopefully it will benefit all.

I will try and run multi-gpu-training notebook in the next few hours and post an update.

I will close this thread / issue thereafter. Please bear with me and tahnk you for your help!

**Comment by shirishr** [comment]
@pjh5, @zou3519 

I ran **python char_rnn.py --gpu -- train_data /path/to/shakespeare.txt**
I get an error:

Entering interactive debugger. Type "bt" to print the full stacktrace. Type "help" to see command listing.
[enforce fail at common_cudnn.h:102] version_match. cuDNN compiled (7102) and runtime (7005) versions mismatch 


When I run **cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2**
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 4

so I am confused : I have cuDNN 704 according to cudnn.h
caffe2 example char_rnn sees cuDNN runtime of 7005 and it is compiled with cuDNN 7102

Can you help?

**Comment by pjh5** [comment]
Can you try CuDNN 7.1 ?

**Comment by shirishr** [comment]
@pjh5,
I just did that.
I am getting a different error message.

[enforce fail at context_gpu.h:155] . Encountered CUDA error: no kernel image is available for execution on the device Error from operator: 
output: "LSTM/i2h_w" name: "" type: "XavierFill" arg { name: "shape" ints: 400 ints: 91 } device_option { device_type: 1 cuda_gpu_id: 0 }

??

**Comment by rogerwwww** [comment]
Hi @shirishr @pjh5 
I've just encountered the same error. Our configurations are the same except I am using python2.7. 
I was running
`python caffe2/python/operator_test/relu_op_test.py`
and the error occurred:

RuntimeError: [enforce fail at context_gpu.h:155] . Encountered CUDA error: no kernel image is available for execution on the device Error from operator:
input: "X" output: "Y" name: "" type: "Relu" device_option { device_type: 1 } engine: ""

**Comment by pjh5** [comment]
Looks like https://github.com/caffe2/caffe2/issues/2390 . I haven't reproduced this myself yet unfortunately.

**Comment by shirishr** [comment]
@pjh5,

I had also posted same issue with anaconda team. 
Their response is:

https://github.com/ContinuumIO/anaconda-issues/issues/9174#issuecomment-382397929

**Comment by pjh5** [comment]
@shirishr there must be a difference between the CuDNN package that we build Caffe2 against and the installation on your machine. It seems like using the same version should fix it buy maybe there's another problem. Can you try installing from source? Use the scripts/build_anaconda.sh script as described here https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#anaconda-install-path

**Comment by shirishr** [comment]
@pjh5, I will rebuild a conda environment from scratch. Can you confirm if one should follow:


Install with GPU Support==>For Ubuntu 16.04==>wget "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/**cuda-repo-ubuntu1604_8.0.61-1_amd64.deb**"
and 
CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/**v5.1**/cudnn-8.0-linux-x64-v5.1.tgz"

This makes the combination **cuda 8.0 - cudnn 5.1**

Whereas my efforts so far have been via anaconda as:

conda install -c caffe2 caffe2-cuda9.0-cudnn7 (as per https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt)

Which would have led to combination of **cuda 9.0 - cudnn 7.0**

Please advice

**Comment by shirishr** [comment]
@rogerwwww,

Others have reported similar errors:

https://github.com/facebookresearch/Detectron/issues/260

**Comment by rogerwwww** [comment]
Hi @shirishr 
I solved this via building caffe2 from source. Though the issue still exists, I can run the code now anyway.

**Comment by shirishr** [comment]
@rogerwwww,

Roger did just follow from here?: 

https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#anaconda-install-path

Ubuntu+Build from source==>Clone & Build:

# Clone Caffe2's source code from our Github repository
git clone --recursive https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init

# Create a directory to put Caffe2's build files in
mkdir build && cd build

# Configure Caffe2's build
# This looks for packages on your machine and figures out which functionality
# to include in the Caffe2 installation. The output of this command is very
# useful in debugging.
cmake ..

# Compile, link, and install Caffe2
sudo make install

I may have confused the issue in my previous comment to @pjh5 where I am asking about cuda 9.0 - cudnn 7.0 v/s cuda 8.0 + cudnn 5.1.

@pjh5 my apologies. Since CUDA 9.0 and cnDNN 7.1.2 is already installed I should just build caffe2 from source.

**Comment by rogerwwww** [comment]
Hi @shirishr ,
Sorry for my late reply. Yes I followed the instructions in that link. 
Wish you have already built Caffe2 successfully 😃

**Comment by pjh5** [comment]
@shirishr those links to specific CUDA and CuDNN packages are merely suggestions. You should find the packages you want from Nvidia's website and download them manually, without using wget.

**Comment by shirishr** [comment]
@pjh5,
You are working on a pytorch+caffe2 combined installation git. Aren't you.
I would rather wait for it and install pytorch and caffe2 together. I am closing this issue.

**Comment by pjh5** [comment]
@shirishr you can try out the early versions if you want (currently only CPU-only version available). Please let me know all the errors you come across
```
conda install -c caffe2 pytorch-caffe2
```
