### ISSUE TITLE
BUG (potential crash) with `state_dict()` implementation and overload

### ISSUE THREAD

**Issue by lkct** [pytorch/pytorch#72778]
### 🐛 Describe the bug

`nn.Module.state_dict()` is defined as:
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L1283-L1295
and implemented as: (first few lines)
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L1312-L1319

### BUG 1
Code to reproduce:
```python
from collections import OrderedDict
from torch.nn import Linear

m = Linear(1, 1)
print(m.state_dict())  # works
print(m.state_dict(OrderedDict()))  # fails
```
Output:
```
OrderedDict([('weight', tensor([[0.6800]])), ('bias', tensor([-0.6202]))])
Traceback (most recent call last):
  File "/home/lkct/trainer/work_dir/test.py", line 38, in <module>
    print(m.state_dict(OrderedDict()))  # fails
  File "/home/lkct/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1315, in state_dict
    destination._metadata[prefix[:-1]] = local_metadata = dict(version=self._version)
AttributeError: 'collections.OrderedDict' object has no attribute '_metadata'
```
Because with custom `destination` passed in, L1314 is skipped, and L1315 has no `_metadata` to work with.

### BUG 2
Assume Bug 1 is fixed. I'm directly commenting L1315 out because it is irrelevant to the following. (Temporarily comment the line in your torch library to run the next piece of code.)
Code to reproduce:
```python
from torch.nn import Linear

m = Linear(1, 1)
print(m.state_dict())  # works
print(m.state_dict('a'))  # fails
```
Output:
```
OrderedDict([('weight', tensor([[0.9686]])), ('bias', tensor([0.5913]))])
Traceback (most recent call last):
  File "/home/lkct/trainer/work_dir/test.py", line 38, in <module>
    print(m.state_dict('a'))  # fails
  File "/home/lkct/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1316, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/home/lkct/miniconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1273, in _save_to_state_dict
    destination[prefix + name] = param if keep_vars else param.detach()
TypeError: 'str' object does not support item assignment
```
The second overload at L1292 suggests a calling signature of `(prefix: str = ..., keep_vars: bool = ...) -> OrderedDict[str, Tensor]`. Therefore the code above should have `prefix='a', keep_vars=False` and return a `OrderedDict`. However, the `'a'` is assigned to `destination`, which is expected to be `None`.

### Suggestion for fix
I think the interface of `state_dict()` should be re-designed, considering the following:
1. The `destination` parameter is mainly for internal use. Do we need to expose it to the user?
1.1. If so, consider listing it in the second overload too. Also, note that `_metadata` may not be appearing in the `destination` given by the user.
1.2. The first overload also allows `state_dict()` to return any `Mapping` type based on the type of `destination`. However, `load_state_dict()` is too strict that only accept a `OrderedDict`. Refer to #72707. This should also be considered when deciding the use of `destination`.
2. Should we allow positional arguments which cause the ambiguation in Bug 2, or change the order of arguments? Either enforcing keyword arguments or moving `destination` to the end will do.

EDIT:
Changing the interface of `state_dict()` may impose severe compatibility issues, so it would also be great if the docs can be updated first to address these bugs.
These bugs can cause a crash when retrieving the state dict, which should be quite common. However, since no one noticed and fixed them, maybe people are not using using `state_dict()` this way, which means it probably has only a minor impact on compatibility.

### Versions

torch 1.12.0.dev20220213+cu113
Code is referenced from the newest commit in master branch as of writing.

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @kshitij12345

**Comment by lkct** [comment]
It suddenly occurred to me that since there're so many `@overload`s in pytorch, why is `state_dict()` found erroneous.
I searched through all the files in `torch` (the directory installed to python `site_packages`), except for `_C/*.pyi` which only annotates the `_C.*.so`, and found that `state_dict()` is indeed the only one that can go wrong. (Actually there're not many outside because the majority of `@overload`s appear in `_C`.)
In other places like `nn.ParameterList`, the `@overload`s look like this:
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/container.py#L460-L468
No matter which signature is used, the actual implementation sees `(self, idx)`.
Also in the docs of Python [typing](https://docs.python.org/3/library/typing.html), the example is:
```python
@overload
def process(response: None) -> None:
    ...
@overload
def process(response: int) -> tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response):
    <actual implementation>
```
where the implementation only sees `response`.

---

It's my understanding that `typing` annotations in python only provides a hint for type checker/intellisense, and the actual python interpreter still runs dynamically-typed. E.g. in `nn.ParameterList`:
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/container.py#L468-L477
the implementation only sees `idx` without typing, and needs to test the type itself.

---

Now take look at `state_dict()`:
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L1283-L1295
The two overloads can only guarantee that calling with both `m.state_dict({})` and `m.state_dict('a')` will pass the type checking, but for the python interpreter, it has no difference from
```python
def state_dict(self, arg1=None, arg2='', arg3=False): 
```
Therefore, even though `'a'` is intended for `prefix`, it still goes to the first argument `arg1` (`destination`).

---

Another example is `nn.Module.to()`
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L791-L804
It is the same that the implementation only sees `*args, **kwargs`, and the parsing is handled separately in
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L889
and therefore will not go wrong.

**Comment by lkct** [comment]
I've provided a quick fix above, but I still suggest reconsidering the design of the interface provided to the user.

**Comment by soulitzer** [comment]
Hey thanks for the report and the fix! curious if you had a repro for the crash?

**Comment by lkct** [comment]
Hi @soulitzer. Code snippet already provided above. You can search for "Code to reproduce" on the page.

**Comment by lkct** [comment]
> The destination argument should become private

Then it might be a good idea to split the two call signatures so that the user only sees the second. Something like this:
```python
def _state_dict_impl(self, destination, prefix, keep_vars):
    ...  # real things here

def state_dict(self, prefix, keep_vars):
    return self._state_dict_impl(None, prefix, keep_vars)
```

> Note that the typing overload will most likely have to stay as these are required by mypy since this is a "recursive" function.

This is also resolved by the above.

---

For BC, we can change to the above internally while keeping the interface (and overload) of `state_dict`. And we can give a `DeprecationWarning` if `destination` is not None. However, the value intended for `prefix` still can be passed into `destination` if not using keyword argument.

**Comment by albanD** [comment]
1. Only `str` is fine. It would make type a lot more complex for little benefit (the workaround of just converting to str before calling the function is simple).
2. Not sure what the new name for this should be tbh. "detached"? (cc @jbschlosser )  In any case, the two can be done in separate PRs. So no need to block the main improvement above on this.

**Comment by lkct** [comment]
got it.

**Comment by jbschlosser** [comment]
Sure, `detached=True` better describes what that flag does. Note that `detached == not keep_vars` so it's not quite a direct find / replace. Agree that we should do this in a follow-up PR.

**Comment by kcelia** [comment]
Hello, I still get this error: `TypeError: state_dict() got an unexpected keyword argument 'destination'` What should I do ?

**Comment by kcelia** [comment]
Please ignore my request, I realized that the issue comes from another library.
