### ISSUE TITLE
DDP window TCP bug [socket.cpp:558] [c10d] The client socket has failed to 

### ISSUE THREAD

**Issue by spyroot** [pytorch/pytorch#77523]
### 🐛 Describe the bug

Hi   

I have two window boxes, each host has a single GPU.  Both can communicate and I disabled the firewall etc.  
Both hosts added A recond in the DNS server.  I added both while troubleshooting.  added in both host's file

Master node.  (IP address 192.168.254.230)

```python
torch.distributed.init_process_group(
            backend="gloo",
            init_method="localhost:54321"   // I tried to 92.168.254.230 , actual hostname.
            world_size=2,
            rank=0)
```
Second node.
Master node.  (IP address 192.168.254.230)

```python
torch.distributed.init_process_group(
            backend="gloo",
            init_method="192.168.254.230:54321"
            world_size=2,
            rank=1)
```

In all cases, I see the error and both master and node never return from the init call.
Meanwhile, I run Wireshark and I see a TCP session and handshake on the same port  54321.

[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [win11.vmwarelab.edu]:54321 (system error: 10049 - The requested address is not valid in its context.).

```

>>> import torch
>>> print(torch.__version__)
1.11.0


If you need Wireshark PCAPI can send but I seek the last packet from the master ACK 


<img width="839" alt="image" src="https://user-images.githubusercontent.com/11797329/168544258-d191881d-ce10-4b87-a4d9-f6d3041d7874.png">


### Versions

1.11.0

**Comment by zhaojuanmao** [comment]
did you set env like this "export GLOO_SOCKET_IFNAME=eth0,eth1,eth2,eth3"?

**Comment by spyroot** [comment]
Yeah, I tried.  I doesn't I honestly gave up now trying nccl

**Comment by vanthonguyen** [comment]
Hi,
I have the same error on Windows 10 and Pytorch 1.11.3 when using ipv4 addresses.
When using ipv6, there was no warnings nor errrors. The proccess just hangs at init_process_group.
Master node:
```
os.environ['MASTER_ADDR'] = 'fe80::d8ea:4ce7:7c8a:cbcd'
os.environ['MASTER_PORT'] = '9999'
os.environ['RANK'] = '0'
os.environ['WORLD_SIZE'] = '2'
torch.distributed.init_process_group(backend="gloo")
```

Second node:
```os.environ['MASTER_ADDR'] = 'fe80::d8ea:4ce7:7c8a:cbcd'
os.environ['MASTER_PORT'] = '9999'
os.environ['RANK'] = '1'
os.environ['WORLD_SIZE'] = '2'
torch.distributed.init_process_group(backend="gloo")
```

The communication between twos nodes is good. If I kill the master process the process in the second node is terminated.

![error](https://user-images.githubusercontent.com/356018/173666817-7697e949-0a3b-4a0f-b47c-f83b75fd3937.png)

**Comment by anas-zafar** [comment]
@spyroot were you able to solve it?

**Comment by spyroot** [comment]
@anas-zafar, I like your dedication :))) merry xmass.     No, I couldn't fix it; several issues very deep in TCP stack IP, so I just dropped that.    ( I think they way getbyhostname and number of other API consumed in c10 ). 

The way I fixed my issue.    

a) Use docker, WSL2
b) Make sure it win 10, not win 11. ( The reason is in Win10, you can re-adjust networking and make the main interface i.e eth0 bridged).  

i.e, we have a WSL2 TCP stack, a windows TCP stack, and then you have a docker network. Hence you need to make sure the WSL2 bridged.   NCCL doesn't work if a connection is NATed.    ( I open several bugs unrelated to this issue but related NCCL and NAT traversal)

**Comment by surak** [comment]
The message is more like this:

```bash
INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_xegnwjw8/none_ykcxxa_v
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
[W socket.cpp:401] [c10d] The server socket cannot be initialized on [::]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : distrib.py
  min_nodes        : 2
  max_nodes        : 2
  nproc_per_node   : 4
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 10.13.27.125:7010
  rdzv_configs     : {'rank': 1, 'timeout': 900}
  max_restarts     : 0
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=10.13.27.125
  master_port=7010
  group_rank=0
  group_world_size=2
  local_ranks=[0, 1, 2, 3]
  role_ranks=[0, 1, 2, 3]
  global_ranks=[0, 1, 2, 3]
  role_world_sizes=[8, 8, 8, 8]
  global_world_sizes=[8, 8, 8, 8]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_xegnwjw8/none_ykcxxa_v/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_xegnwjw8/none_ykcxxa_v/attempt_0/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_xegnwjw8/none_ykcxxa_v/attempt_0/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_xegnwjw8/none_ykcxxa_v/attempt_0/3/error.json
INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_2pgxxx4c/none_jtrmt_c4
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=10.13.27.125
  master_port=7010
  group_rank=1
  group_world_size=2
  local_ranks=[0, 1, 2, 3]
  role_ranks=[4, 5, 6, 7]
  global_ranks=[4, 5, 6, 7]
  role_world_sizes=[8, 8, 8, 8]
  global_world_sizes=[8, 8, 8, 8]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_2pgxxx4c/none_jtrmt_c4/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_2pgxxx4c/none_jtrmt_c4/attempt_0/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_2pgxxx4c/none_jtrmt_c4/attempt_0/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_2pgxxx4c/none_jtrmt_c4/attempt_0/3/error.json
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:558] [c10d] The client socket cannot be initialized to connect to [jwb0475i.juwels]:7010 (errno: 97 - Address family not supported by protocol).
```

**Comment by TousenKaname** [comment]
Did you solve it?

**Comment by surak** [comment]
My issue was on huggingface accelerate not respecting command line parameters.

Mind the line above, which says `  rdzv_backend     : static`

So, c10d was not being used, despite the messaging. Fixed here: https://github.com/huggingface/accelerate/issues/1489

I still have issues with DDP in some special circumstances on infiniband over different racks of the supercomputers, but I will get to there in time. 

Do I delete my previous messages on this issue here?

**Comment by TousenKaname** [comment]
Thanks!
