### ISSUE TITLE
MPS backend built, but not available

### ISSUE THREAD

**Issue by GerardWalsh** [pytorch/pytorch#78343]
### 🐛 Describe the bug

When trying to run on M1 (MacBook Pro 13 inch), I get the following:|

```
>>> import torch
>>> print(f"PyTorch version: {torch.__version__}")
PyTorch version: 1.13.0.dev20220525
>>> print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
Is MPS (Metal Performance Shader) built? True
>>> print(f"Is MPS available? {torch.backends.mps.is_available()}")
Is MPS available? False
```

How can the backend be built, but not available?

### Versions

PyTorch version: 1.13.0.dev20220525
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.27.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14)  [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220525
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220525          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by recurrence** [comment]
I briefly checked the source and I suspect you need to be on macOS 12.3+

`MPSDevice::MPSDevice(): _mtl_device(nil) {
  // Check that MacOS 12.3+ version of MPS framework is available
  id mpsCD = NSClassFromString(@"MPSGraphCompilationDescriptor");
  if (![mpsCD instancesRespondToSelector:@selector(optimizationLevel)]) {
    // According to https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraphcompilationdescriptor/3922624-optimizationlevel
    // this means we are running on older MacOS
    return;
  }
  NSArray* devices = [MTLCopyAllDevices() autorelease];
  for (unsigned long i = 0 ; i < [devices count] ; i++) {
    id<MTLDevice>  device = devices[i];
    if(![device isLowPower]) { // exclude Intel GPUs
      _mtl_device = [device retain];
      break;
    }
  }
  assert(_mtl_device);
}`

**Comment by albanD** [comment]
Hi,

As mentioned above, we require macos 12.3+ 
There are some functionalities of MPS from that version of macos that we need. So you will need to update your OS to be able to run with the mps backend.

**Comment by GerardWalsh** [comment]
Resolved - Upgraded OS to 12.4.

**Comment by aceamarco** [comment]
Hello, I'm on MacOS 12.4 and am facing this same issue -- is it no longer working on 12.3+?

**Comment by aceamarco** [comment]
**Update:** For those encountering this issue with PyTorch 2.x on MacOS 12.3+, downgrading to PyTorch 1.x resolves the problem, as mentioned by others earlier.

You can downgrade using the following command:

```bash
pip install 'torch<2.0.0'
```

**Comment by rafaelvareto** [comment]
Is there a way to run PyTorch 2.5.1 with MPS enabled without upgrading the MacOS?

More precisely, I have a MacBook (macOS-12.7.6-arm64-arm-64bit) but I’m still facing the following error:

```bash
RuntimeError: The MPS backend is supported on MacOS 12.3+.
Current OS version can be queried using `sw_vers`.

>> sw_vers
ProductName:	macOS
ProductVersion:	12.7.6
BuildVersion:	21H1320
```

Basically, I have a OS version satisfying PyTorch requirements, still, it does not find a MPS device.
