### ISSUE TITLE
Weird warning using matrix exp for complex tensors

### ISSUE THREAD

**Issue by ferrine** [pytorch/pytorch#80948]
### 🐛 Describe the bug

Warning appears if you run this snippet
```python
torch.manual_seed(42)
tens = 0.5 * torch.randn(10, 3, 3, dtype=torch.complex64)
tens = (0.5 * (tens.transpose(-1, -2) + tens))
tens.imag = torch.matrix_exp(tens.imag)
```
The warning
```
/tmp/ipykernel_18699/1530108168.py:4: UserWarning: An output with one or more elements was resized since it had shape [4, 3, 3], which does not match the required output shape [1, 4, 3, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:24.)
  tens.imag = torch.matrix_exp(tens.imag)
```

It did not happen prior to 1.12 version

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 13.0.1
CMake version: version 3.23.1
Libc version: glibc-2.35

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.17.4-arch1-1-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1070
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.3
/usr/lib/libcudnn_adv_infer.so.8.3.3
/usr/lib/libcudnn_adv_train.so.8.3.3
/usr/lib/libcudnn_cnn_infer.so.8.3.3
/usr/lib/libcudnn_cnn_train.so.8.3.3
/usr/lib/libcudnn_ops_infer.so.8.3.3
/usr/lib/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.12.0
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] torch                     1.12.0                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @jianyuh @pearu @walterddr @IvanYashchuk @xwang233

**Comment by ferrine** [comment]
Yes it worries me because it is not deterministic and I have no idea what I am doing wrong.

**Comment by nikitaved** [comment]
It is a warning coming from a TensorIterator, @cpuhrsch . There is a method called `_compute_linear_combinations` or something like that (been a long time since I implemented that). The shapes are safely broadcastable because of the trailing 1 on the left, so I do not expect any correctness issues. TI these days does not allow broadcasting of outputs over inputs without any warnings.

**Comment by Lezcano** [comment]
I think this error comes from some size mismatch in the use of `matmul_out` within `matrix_exp`. This behaviour was corrected in https://github.com/pytorch/pytorch/pull/75197. Could you look into it @nikitaved?

**Comment by nikitaved** [comment]
Or that, I do not know. We could have a look. @cpuhrsch , are you taking this?

**Comment by mruberry** [comment]
I doubt @cpuhrsch meant to assign this to himself and I've unassigned him. This is a linear algebra / complex bug, because the user should not see this warning, and it's triggered because in the internals of these operations we are passing an incorrectly sized result tensor to the `out` parameter for an operation. We should identify where this is happening and correct it.

**Comment by malfet** [comment]
Can still reproduce it in latest nightly (1.13.0.dev20220711)

**Comment by nikitaved** [comment]
Will have a look!
