### ISSUE TITLE
Tensorboard SummaryWriter `add_histogram` fails with NumPy 1.24+

### ISSUE THREAD

**Issue by j3soon** [pytorch/pytorch#91516]
### 🐛 Describe the bug

The use of `np.greater(counts, 0, dtype=np.int32)` in `add_histogram` is deprecated a while ago, and the deprecation expired in Numpy 1.24+:

> The `dtype=` argument to comparison ufuncs is now applied correctly. That
> means that only `bool` and `object` are valid values and `dtype=object` is
> enforced.

Source: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

Minimal example:

```python
from torch.utils.tensorboard import SummaryWriter
import numpy as np
writer = SummaryWriter()
for i in range(10):
    x = np.random.random(1000)
    writer.add_histogram('distribution centers', x + i, i)
writer.close()
```

Error message with Numpy 1.24+:

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    writer.add_histogram('distribution centers', x + i, i)
  File "/home/johnson/venv/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 485, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime
  File "/home/johnson/venv/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 358, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/home/johnson/venv/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 386, in make_histogram
    cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater
```

This error does not occur in Numpy 1.23.5. Numpy should have print a deprecation warning about this:

```
DeprecationWarning: using `dtype=` in comparisons is only useful for `dtype=object` (and will do nothing for bool). This operation will fail in the future.
```

but I think PyTorch has suppressed the warning.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.25.1
Libc version: glibc-2.27

Python version: 3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro RTX 6000
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] numpydoc                  1.1.0                      py_0  
```

**Comment by ppwwyyxx** [comment]
(related: there are a few more numpy1.24 compatibility issues at https://github.com/pytorch/pytorch/issues/91329)

**Comment by prion502** [comment]
so how can use add_histogram function in numpy 1.24.1?

**Comment by j3soon** [comment]
@prion502 Since this issue has been resolved, I believe you can use [`add_histogram`](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_histogram) as before (i.e., as in NumPy < 1.24).

**Comment by SQRTQuin33** [comment]
@j3soon I was using Python 3.9, torch 1.9.1 (with CUDA 11.1) and numpy 1.24.2 to run something today and still ran into this exact problem, don't really know about pytorch 2.0+ though.
Thank you for the post though, otherwise might have cost me several more hours to figure this out.

**Comment by sainisatish** [comment]
I have this issue during yolo v7 training - 
 cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater.

**Comment by YiLin32Wang** [comment]
Hi, I'm still getting this error with numpy 1.24 and tensorboard 2.15.

**Comment by ShuaibinLi** [comment]
same problem with 
numpy==1.24.3 
torch==1.13.1+cu117
tensorboard==2.13.0

**Comment by yhu9** [comment]
Same problem with
numpy == 1.24.0
tensorboard == 2.14.0
torch == 1.13.1

**Comment by CindyTing** [comment]
Same problem with
numpy == 1.26.4
tensorboard == 2.16.2
torch == 1.13.1+cu116

**Comment by zyl9737** [comment]
Using `from tensorboardX import SummaryWriter` can solve this issue

**Comment by WenhaoRichard** [comment]
same problem when I used `add_histogram()`
with 
numpy==1.26.4
torch==1.13.0
tensorboard==2.16.2

**Comment by Ahmedman60** [comment]
go to the path of the summary like this ->>C:\Users\legion\anaconda3\envs\gan\Lib\site-packages\torch\utils\tensorboard\summary.py

open summary.py and change following line
`cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32)) '
to
`cum_counts = np.cumsum(np.greater(counts, 0)) '
