### ISSUE TITLE
Pytorch install problems on clean Windows 7 system using pip

### ISSUE THREAD

**Issue by Bill-McCormick** [pytorch/pytorch#9818]
## Issue description

Installing PyTorch from PIP on a clean Python3.6 system on Windows 7 fails silently.    The install succeeds, but torch cannot be imported.

(rl-env) D:\>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\rl-env\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
>>>

I've traced this problem down to the fact that Pytorch seems to require OpenMp, which is not included in the PIP wheel, so the torch._C load fails because the dependent library libiomp5md.dll is missing.   There may be further missing dependencies that I am not able to identify.

A workaround to this problem is to use pytorch from an Anaconda install.   

## System Info

- PyTorch or Caffe2:   PYTorch
- How you installed PyTorch (conda, pip, source):  pip
- Build command you used (if compiling from source):  N/A
- OS:  Windows 7
- PyTorch version:  0.40
- Python version:  3.6.6
- CUDA/cuDNN version:   Tried with no Cuda and with Cuda 9.1
- GPU models and configuration:   Nvidia Tesla K20c
- GCC version (if compiling from source):  N/A
- CMake version:  N/A
- Versions of any other relevant libraries:  N/A

**Comment by peterjc123** [comment]
@Bill-McCormick It's a known issue, which is already listed in the master doc and fixed in the upcoming release.

**Comment by Bill-McCormick** [comment]
I see it now.   Here's the link

https://pytorch.org/docs/stable/notes/windows.html

> Import error
from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
The problem is caused by the missing of the essential files. Actually, we include almost all the essential files that PyTorch need except VC2017 redistributable. You can resolve this by typing the following command.
conda install -c peterjc123 vc vs2017_runtime_

Since I'm using pip install I cannot use the conda command.    And torch loads in conda anyway.

This morning I installed the latest VC2017 redistributable which is version 14.14.26429, to try out your workaround, but the problem remains.    Do you have more details?

**Comment by peterjc123** [comment]
`pip install intel-openmp` Have you tried this?

**Comment by Bill-McCormick** [comment]
I just installed intel-openmp-2018.0.3.   The openmp library is installed in Python36\Library\bin, and the problem is still there.

However, if I manually copy the openmp binaries over to Python36\lib\site-packages\torch\lib the problem goes away.    This is a little odd, I would have expected Python to append it's Library\bin directory to the path.

Thanks for your help.

**Comment by arnoldmashava** [comment]
I have an 8th Generation Intel GPU UHD Graphics 620 (which is not supported by PyTorch for GPU computations, since it not NVIDIA Architecture and by default would require the NVIDIA CUDA Framework). The sequential execution of the procedure is, prior to the installation of PyTorch (bundled with TorchVision) in Anaconda Python 3.x, it is best to:

1. pip install intel-openmp (current version: intel-openmp 2021.1.2)
2. append to :\Anaconda 3.x\Library\bin directory in the Environment Variables to the Path
3. conda install pytorch torchvision cpuonly -c pytorch 
(including torchaudio forces Anaconda to download the CUDA Toolkit, which is not compatible with Intel GPUs. Best to omit it in the "conda install" command if the objective is to execute Computer Vision and Deep Learning applications which exclude Natural Language Processing)
4. the rest, will be interactive on the Anaconda 3.x Powershell Prompt
5. query Anaconda to see if PyTorch-CPU and TorchVision have been installed as intended: conda list torch
6. invoke the Python shell and attempt importing all of the Deep Learning platforms (including OpenCV 3.x just to check for conflicts and missing dependencies with Torch)

That was my resolution of this issue. Personally for me, PyTorch is less painful to troubleshoot in comparison to TensorFlow or Apache MXNet.

See my screenshot.

Thanks to everyone that contributed.
![2021-03-21 12_16_51-Greenshot](https://user-images.githubusercontent.com/5759101/111915333-733a0400-8a54-11eb-8b44-56e834f698d3.png)

**Comment by arnoldmashava** [comment]
Will PyTorch include non-NVIDIA GPU Architecture (Intel GPUs and FPGAs) in the future iterations of the PyTorch Computer Vision and Deep Learning platform. In mind, I have the Intel OneAPI Toolkit which comes with the Data Parallel C++ (DPC++) which is derived from the OpenCL framework. On the Intel DevCloud, I can target GPUs and FPGAs for accelerated Deep Learning but not with PyTorch (BigDL for Apache Spark). We need PyTorch...
