### ISSUE TITLE
RuntimeError: unwrapped_count > 0 INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by david-anton** [pytorch/pytorch#99973]
### Bug description
I get the error message:

_RuntimeError: unwrapped_count > 0 INTERNAL ASSERT FAILED at "/root/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp":202, please report a bug to PyTorch. Should have at least one dead wrapper_

### Code
The error is reproduced by the following minimal working example:

```
import torch


def func(x_0: torch.Tensor, x_1: torch.Tensor) -> torch.Tensor:
    return torch.sum(torch.tensor([x_0, x_1]) ** 2)


x = torch.tensor([2.0, 3.0])

grad_x = torch.func.grad(func, argnums=0)(x[0], x[1])
```

### System Info:
- PyTorch version: 2.0.0
- installed via pip
- Python version: 3.10.11
- OS: macOS Ventura, Version 13.3.1

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by kshitij12345** [comment]
This was fixed in https://github.com/pytorch/pytorch/pull/98748 and should be available in nightly.

**Comment by david-anton** [comment]
Unfortunately, the error is also raised when using the nightly PyTorch version.

I installed the nightly version by:

_pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu_

However, according to pip, the installed PyTorch is still version 2.0.0. Is this correct? Or how can I check if the nightly version was installed correctly?

**Comment by david-anton** [comment]
Problem solved, thanks a lot!

**Comment by kshitij12345** [comment]
Great to know that!

Closing the issue

**Comment by dhanushTDS** [comment]
Is this fix also in the stable (2.2.1) release as I have the same error still?

**Comment by david-anton** [comment]
With PyTorch version  2.2.1, I don't get an error for the code in my original post.
